export const environment = {
  production: true,
  firebaseConfig : {
    apiKey: "AIzaSyB7l5QmXf9pxwW2RZxLHQ2VtLJtL2K8OCY",
    authDomain: "aaaa-6d056.firebaseapp.com",
    databaseURL: "https://aaaa-6d056-default-rtdb.firebaseio.com",
    projectId: "aaaa-6d056",
    storageBucket: "aaaa-6d056.appspot.com",
    messagingSenderId: "1021417514491",
    appId: "1:1021417514491:web:22abc3ab52fbafe486d75e",
    measurementId: "G-GEMW853ESY"
    // apiKey: "AIzaSyC_vC_cpFkc0ZiCdey9tEx2TMW0bNQzPjM",
    // authDomain: "royal-stallion.firebaseapp.com",
    // databaseURL: "https://royal-stallion.firebaseio.com",
    // projectId: "royal-stallion",
    // storageBucket: "royal-stallion.appspot.com",
    // messagingSenderId: "296126986485",
    // appId: "1:296126986485:web:ea750bc8e8576b16062dbc",
    // measurementId: "G-EDH0E6EHS1"
  },
  english_translations:{
    Login_your_account:"Login your account",
    Please_enter_your_details_below:"Please enter your details below",
    This_field_is_required:"This field is required",
    Enter_valid_Mobile_Number:"Enter valid Mobile Number",
    LOGIN:"LOGIN",
    Login_with_Mobile_Number:"Login with Mobile Number",
    Login_with_Email:"Login with Email",
    Login_with_Password:"Login with Password",
    Verify_OTP:"Verify OTP",
    A_verification_code_has_been_sent_to:"A verification code has been sent to",
    Please_Enter_valid_OTP:"Please Enter valid OTP",
    Resend_OTP:"Resend OTP",
    bit:"128bit",
    Secured_payment:"Secured payment",
    Copyrights:"Copyrights @ Competitiveness Financial | All Rights Reserved",
    Dashboard:"Dashboard",
    My_Opportunities:"My Opportunities",
    Investments:"Investments",
    Operations:"Operations",
    Add_Opportunity:"Add Opportunity",
    LOGOUT:"LOGOUT",
    Opportunity_details:"Opportunity details",
    Company_tagline_Slogan:"Company tagline/Slogan",
    Companys_share_price:"Company’s share price",
    Total_Valuation:"Total Valuation",
    Min_Investment_per_investor:"Min Investment per investor",
    Max_Investment_per_investor:"Max Investment per investor",
    Upload_pictures_for_the_Opportunity:"Upload pictures for the Opportunity",
    Supported_Format:"Supported Format: Jpeg, Png, Jpg, Max Size 50Kb",
    Add_image:"Add image",
    Fundraise_Opportunity_details:"Fundraise Opportunity details",
    How_much_amount_you_are_expecting_to_raise:"How much amount you are expecting to raise?",
    About_company:"About company",
    Write_Short_Bio_about_your_company:"Write Short Bio about your company",
    Reason_to_invest:"Reason to invest",
    Where_are_you_planning_to_allocate_the_funds:"Where are you planning to allocate the funds?",
    Do_you_want_to_introduce_your_team:"Do you want to introduce your team?",
    Yes:"Yes",
    No:"No",
    UPLOAD_DP:"UPLOAD DP",
    Employee_name:"Employee name",
    Designation:"Designation",
    add_more_team_member:"add more team member",
    Terms_Conditions:"Terms & Conditions",
    Write_your_Terms_Conditions_here:"Write your Terms & Conditions here",
    SUBMIT_START_OPPORTUNITY:"SUBMIT & START OPPORTUNITY",
    Saudi_top_crowdfunding_platform:"Saudi’s top crowdfunding platform",
    We_Know_Your_Needs_Trusted_By:"We Know Your Needs, Trusted By 10 Million People",
    No_Of_Investments:"No. Of Investments",
    Total_Investments:"Total Investments",
    Total_Profit:"Total Profit",
    No_Of_Opportunities:"No. Of Opportunities",
    Active_Opportunities:"Active Opportunities",
    Rejected_Opportunities:"Rejected Opportunities",
    Personal_info:"Personal info",
    View_KYC_Details:"View Account Details",
    I_am_a:"I am a",
    Borrower:"Borrower",
    Invester:"Invester",
    First_name:"First name",
    Last_name:"Last name",
    Optional:"Optional",
    Email:"Email",
    Enter_valid_Email_Id:"Enter valid Email Id",
    Mobile_Number:"Mobile Number",
    Password:"Password",
    Password_Must_contain:"Password Must contain",
    Weak:"Weak",
    At_least_characters:"At least 8 characters",
    A_capital_letter:"A capital letter",
    A_small_letter:"A small letter",
    A_number:"A number",
    A_special_character:"A special character",
    Confirm_Password:"Confirm Password",
    Password_doesnt_matched:"Password doesn't matched",
    I_accept_all:"I accept all",
    terms_conditions:"terms & conditions",
    CREATE_ACCOUNT:"CREATE ACCOUNT",
    Status:"Status",
    Skip:"Skip",
    Upload_pictures_for:"Upload pictures for",
    About:"About",
    Tell_about_your:"Tell about your",
    UPDATE:"UPDATE",
    SUBMIT:"SUBMIT",
    faq_one:"What is CFC Platform ?",
    CFC_answer:"CFC is a digital lending platform that connects established businesses with investor (lenders). The platform uses technology to connect both parties through the principle of crowdfunding, - i.e. raising small amounts of funds from many individuals.",
    faq_two:"How can I know the times of offering opportunities?",
    CFC_answer_two:"You can follow up on the offer of opportunities by visiting CFC  platform, as well as if you are registered on the platform, you will be notified by e-mail periodically of the opportunities.",
    faq_three:"What is meant by the term 'KYC'?",
    CFC_answer_three:"The term KYC stands for “Know Your Customer” and is used throughout the client identification process. The pre-set KYC rules by Capital Market Authority (CMA) are the standard requirements that need to be followed by all regulated entities. This includes identity verification, proof of address, employment information, and other general information. Investors need to clear all KYC requirements prior to being onboarded on the CFC platform. The compliance department will conduct ongoing KYC checks to ensure information is constantly updated.",
    faq_four:"What measures are in place to ensure security around my data and the integrity of your platform?",
    CFC_answer_four:"CFC Platform  has been developed on our proprietary server. CFC Platform has leveraged the “best in breed” security features such as encryption, identity and access management, and network security. These features are applied across the whole platform from the holding of data, application access, web communications, and back office operations. We are committed to implement and continuously improve security-aware software development, operational management, and threat-mitigation practices that are essential to the strong protection of services and data",
    Great_things_need_funds_We_know_you_do_too:"Great things need funds, We know you do too.",
    great_things_cfc:"CFC is a digital lending platform that connects established businesses with investor (lenders). The platform uses technology to connect both parties through the principle of crowdfunding, - i.e. raising small amounts of funds from many individuals.",
    Shariah_Compliance:"100% Shariah Compliance",
    Free_promotion_for_your_campaign:"Free promotion for your campaign",
    withdraw_your_amount_instantly:"withdraw your amount instantly",
    How_to_start_your:"How to start your",
    fundraiser_on_Compp_Fintect:"fundraiser on Competitiveness Financial.",
    Easy_Just_Follow:"Easy, Just Follow The Simple Steps Below",
    Enter_Details:"Enter Details",
    kyc_answer:"You are required to Enter a specific information;personal ,venture info ,just required financial statement according to the regulator terms and for Due diligence purpose.",
    Verify_by_KYC:"Verify by KYC",
    verify_answer:"The Regulator requires to verify your information and data provided by you through the safe channels  and the authorized authorities",
    Get_Approval:"Get Approval",
    approval_answer:"You will get approval and be notified automatically through the platform's CRM system such as email and text messages.",
    ready_to_start:"Ready to start your first Fund raise?",
    Get_approval_in_minutes:"Get approval in 5 mins",
    faq:"Frequently asked questions",
    Give_your_dreams_a_boost:"Give your dreams a boost,",
    Start_your_crowdfunding_today:"Start your crowdfunding today.",
    Easy_Funding_options_For_you:"Easy Funding options For you",
    Funding_made_simple:"Funding made simple, rewarding & fun",
    select_registration_type:"Select Registration type",
    Individual:"Individual",
    Corporate:"Corporate",
    heading:"A promising future vision to contribute to the financial sector in the Kingdom of Saudi Arabia",
    content_one:"through innovative and distinguished technical financial solutions for investment and financing.",
    heading_two:"Competitiveness Financial Company (CFC) was established in September 2021, and the Competitiveness obtained a financial technology permit in securities business from the Capital Market Authority (CMA) in June 2022, to offer and invest in debt instruments.",
    about_content_one:"Competitiveness Financial is an electronic platform for crowdfunding, which aims to connect investors with investment opportunities to finance projects, by arranging the issuance and offering of debt instruments to finance projects of small and medium-sized companies, which in turn contribute to raising the GDP and providing jobs, and presenting those opportunities in the platform to investors and clients Platform.",
    about_content_two:"CMA had launched the Financial Technology Lab in 2018, in order to keep pace with the accelerating technological revolution in the financial market. The financial technology system in the Kingdom is highly attractive, allowing companies to easily provide innovative services.",
    about_content_three:"CFC is one of the international technology competitiveness companies. It is a national institution that aims to provide integrated technical consultancy to government organizations and bodies and participate in restructuring systems and procedures to enhance access to the goals of the vision of the Kingdom of Saudi Arabia.",
    Investor:"Investor",
    plan:"Planning to raise money for your business? Checkout our hassle free options for you.",
    invest:"Invest in fast growing businesses with us, 100% safe and secure investment platform in Saudi arabia.",
    General:"General",
    Explore:"Explore CFC website for info, suggestions and advise on crowdfunding and investment.",
    PRODUCT_FEATURES:"PRODUCT FEATURES",
    FINANCIAL_DIFFERENCE:"The Financial Competitiveness Team harnesses its expertise in the credit analysis of  projects based on quantitative and qualitative analysis of the feasibility of the project and the company, its management and its financial statements, to reach the rating scale for investment risks. After that, the debt instrument, which is the sukuk, is issued, in which the investment is made.",
    What_makes_us_different:"What makes us different?",
    ABOUT_US:"About CFC",
    To_Offer:"To Offer And Invest In Debt Instruments.",
    Details_answer:"Provide your contact information and login your account to start the process.",
    Provide_your_national_ID:"Provide your national ID number and your full name for the KYC verification purpose.",
    Submit_your_KYC:"Submit your KYC and personal details and get approval within 24hrs.",
    shariah:"Sharia compliant",
    Projects:"Projects",
    Total_Raised:"Total Raised",
    Loan_terms:"Loan terms from 1- 36 months",
    Financing:"Financing as quick as 1 day",
    Customised_loan:"Customised loans that fits your needs",
    What_is_Sukuk:"What is Sukuk?",
    Sukuk_answer:"Sukuk are securities issued by companies (or governments) to raise funds from investors for a specified period of time with a specified repayment date, during which period the sukuk usually distribute a profit rate (fixed or variable) periodically. At the end of the life of the instrument, known as the maturity period, the issuer of the security (the borrower) repays the capital raised from the investors.",
    How_do_I_make_profit:"How do I make profit?",
    profit_answer:"Each investment opportunity has a different distribution timing from the other, such as if it is quarterly, semi-annually, or paid in one payment, which is the maturity period at the end of the life of the instrument.",
    Lets_get_in_touch:"Let’s get in touch",
    Type_your_message_here:"Type your message here",
    terms:"التمهيد: يرتبط الاستثمار بالشركات الناشئة بمخاطر عالية، وقد يؤدي إلى الخسارة الكاملة لاستثمارك. يجب ألا تستثمر الأموال التي لا يمكنك تحمل خسارتها، وفي حال الخسارة يُقتصر على المبلغ المستثمر فقط. الاستثمار من خلال التنافسية المالية هو استثمار طويل الأجل ومناسب للمستثمرين على المدى الطويل. إن فرص الاستثمار في الوقت الحالي مخصصة للأشخاص المقيمين في المملكة العربية السعودية. يجب على المستخدم قراءة هذه الاتفاقية بعناية حيث توضح تفاصيل الخدمة التي تقدمها شركة التنافسية المالية وتحدد الالتزامات والحقوق بين التنافسية المالية والمستخدم، ويمنع استخدام المنصة في حال عدم فهم واستيعاب كافة مواد الاتفاقية. فهذه هي اتفاقية استخدام منصة التنافسية المالية وجميع صفحاتها الفرعية ولجميع العلاقات التعاقدية بين شركة التنافسية المالية. المادة الأولى: التعريفات: 1.	التنافسية المالية: شركة التنافسية المالية ذات السجل التجاري رقم (1010818020) وتاريخ 12/01/1444هـ، ومقرها بمدينة الرياض. 2.	المستخدم: هو الشخص الطبيعي أو الاعتباري المستفيد من خدمات منصة التنافسية المالية. 3.	المنصة: هي المنصة الإلكترونية لشركة التنافسية المالية والتي تقدم من خلال الموقع الإلكتروني خدمات إصدار أدوات الدين والاستثمار فيها للمنشآت طالبة التمويل. 4.	مخاطر إعسار المصدر: هي خطر إعسار الشريك -الشركة- ويؤدي ذلك إلى إفلاس حملة الصكوك إلى خسارة كلية. 5.	مخاطر التأرجح: هي سوء تصرف الموظفين أو الأعضاء مما ينتج عنه بشكل مباشر أو غير مباشر وتؤدي إلى إلى الإعسار. 6.	مخاطر عدم توزيع الاستثمار: هي عدم تحقيق المستثمر أي تنويع في المحفظة الاستثمارية، ويمكن تجنيبها بتوزيع مبالغ الاستثمار على شركات متعددة. 7.	صعوبة التخارج: هي ظروف خاصة لقابلية التخارج ولا توجد سوق ثانوية لتداول الصكوك في هذه اللحظة. 8.	نظام مكافحة جرائم المعلوماتية: الصادر بالمرسوم الملكي رقم (م/17) عام 1428هـ. 9.	نظام مكافحة غسل الأموال: الصادر بالمرسوم الملكي رقم (م/20) عام 1439هـ. المادة الثانية: التعريف بالمنصة: 1.	هي منصة عبر الإنترنت تمكن المستخدمين من الوصول إلى العروض المقدمة من قبل الشركات المدرجة في المنصة من خلال إصدار أدوات الدين والاستثمار بها، والاستثمار فيها على أساس اتفاقية استثمار، ولهذا الغرض تنشر الشركات معلوماتها عبر المنصة. 2.	في حالة الاستثمار من قبل المستخدمين لا تصبح التنافسية المالية طرفًا متعاقدًا بنفسها، ويبرم الاستثمار فقط بين المستخدمين والشركة المستثمر بها. 3.	يجب على الشركة المصدرة التي تقدم دعوتها للمستخدمين لتقديم عروضهم بناء على حملة إصدار الصكوك توفير المعلومات الخاصة بالاستثمار الجماعي على منصة التنافسية المالية. 4.	لا تتحمل التنافسية المالية مدى مصداقية البيانات التي تقدمها الشركة المصدرة. 5.	تسعى التنافسية المالية لتطوير خدماتها باستمرار، مما قد يستدعي في بعض الأحيان بإلغاء الخدمة مؤقتا أو بشكل دائم. 6.	يسري استخدام المنصة داخل المملكة العربية السعودية فقط. المادة الثالثة: المشغل والمزود للمنصة: شركة التنافسية المالية هي المشغل والمزود لمنصة التنافسية المالية، والخدمة المقدمة تخضع لشروط التنافسية المالية التالية التي يجب أن تطبق في النسخة السارية وقت تسجيل المستخدم. المادة الرابعة: التسجيل: 1.	يجب التسجيل كمستخدم في بعض أقسام منصة التنافسية المالية. 2.	يدخل المستخدم في عقد استخدام مع شركة التنافسية المالية بمجرد التسجيل. 3.	تقوم التنافسية المالية– في بعض الأحيان – بالتحقق من المستخدم باستخدام خدمة 'يقين' المقدمة من 'علم'. 4.	يجب على المستخدم أن يكون ذا أهلية وقدرة كافية على التعاقد. 5.	لا يجوز للقاصرين التسجيل. 6.	يجوز للتنافسية المالية فتح محفظة تكميلية بطلب من المستخدم ليستخدمها أشخاص دون الثامنة عشرة سنة. 7.	يتحمل من طلب فتح المحفظة التكميلية كامل المسؤولية عن استخدام المحفظة التكميلية، وتعتبرها التنافسية المالية جزءا من حساب محفظة المستخدم. 8.	يمكن لمستخدم المحفظة التكميلية إيداع أو سحب أموال من المحفظة الاستثمارية. 9.	يجب تقديم كافة البيانات المطلوبة من الأفراد أو المنشآت للتنافسية المالية خلال عملية التسجيل، ويتحمل المستخدم المسؤولية الكاملة حال إدخاله البيانات غير الصحيحة خلال عملية التسجيل أو أي مرحلة من مراحل استخدام خدمات المحفظة. 10.	يجب على المستخدم تقديم أي معلومات إضافية للتثبت من هويته أو لإثبات موثوقية أي أداة تمويل يسجلها المستخدم لاستخدامها مع التناقسية المالية. 11.	يجوز للتنافسية المالية أو طرف ثالث تتعاقد معه القيام بكافة التحريات التي تراها ضرورية للتحقق من المعلومات التي يتم تقديمها للتنافسية المالية، على سبيل المثال لا الحصر: فحص قواعد البيانات التجارية أو التقارير الائتمانية. 12.	لا تضمن التنافسية المالية ما يجري أثناء اتخاذ إجراءات التحقق من هوية المستخدم. 13.	يجب على المستخدم تصحيح بياناته فورا في حال تغيرها أو إدخالها بشكل غير كامل أو غير صحيح. 14.	يجب على المستخدم التأكد من سرية كلمة المرور. 15.	يجب إبلاغ التنافسية المالية فورا للاستخدام غير المصرح لكلمة المرور أو حساب المستخدم. 16.	لا يجوز استخدام الحساب لغير المستخدم سواء كان ذلك الشخص طبيعيًا أو معنويًا. 17.	تكون اتفاقية المستخدم واجبة على الطرفين من خلال النقر على رابط التأكيد المرسل عبر البريد الإلكتروني للمستخدم. 18.	تكون مدة اتفاقية المستخدم غير محددة بوقت معين. 19.	يحق للتنافسية المالية أو للمستخدم إنهاء اتفاقية المستخدم بأي وقت دون إشعار مسبق منها على سبيل المثال: حذف حساب المستخدم. 20.	تطبق جميع حدود المسؤولية والتعويضات في هذه الاتفاقية، حتى بعد إنهاء اتفاقية المستخدم. المادة الخامسة: اتفاق الوكالة بالاستثمار: 1.	يجب على المستخدم تعبئة النماذج على منصة التنافسية المالية والنقر على زر 'استثمر' نهاية النموذج. 2.	يقر المستخدم بقبول الاستثمار في الشركة المصدرة ووفقًا لشروطها. 3.	يجب بلوغ الحد الأدنى لمبلغ الاستثمار للجولة والمتفق عليه مع الشركة المصدرة سلفًا لكي تكون اتفاقية الاستثمار نافذة. 4.	يجوز إبرام عقد مكتوب بالإضافة إلى الإجراء المذكور أعلاه. 5.	يلتزم المستخدم باتفاق الاستثمار دون أي مطالبة بإبرام اتفاقية استثمار مستقلة. 6.	تلتزم الشركة بالمدة المحددة لعرض الاستثمارات على منصة التنافسية المالية. 7.	تلتزم التنافسية المالية بتزويد كافة الأطراف المتعاقدة بالبيانات اللازمة للتواصل مع الطرف الآخر. 8.	تلتزم التنافسية المالية بإرسال جميع المستندات إلكترونيًا من خلال البريد الإلكتروني للمستخدم. 9.	يتحمل المستخدم المسؤولية بكافة المستندات المرسلة من تلقاء نفسه بشكل إلكتروني أو مادي. 10.	عملاً بنص المادة (73) من لائحة مؤسسات السوق المالية يلزم على الشركة الاحتفاظ بأموال العميل في حساب باسمه لدى أحد البنوك المحلية ويوافق العميل على أحقية التنافسية المالية بالحصول على جميع العوائد والأرباح العائدة من الاحتفاظ بأموال العملاء في هذه الحسابات. ويجوز للشركة أن تحتفظ بأموال العميل لدى بنك خارجي أو تنفيذ تحويل خارجي خصماً من حسابه لدى البنك المحلي أو من أمواله الأخرى لديها إذا كان ذلك ضرورياً لتسوية صفقة أوراق مالية خارج المملكة. المادة السادسة: حدود المسؤولية: 1.	تتحمل التنافسية المالية المسؤولية نتيجة الإهمال الجسيم أو النية في حالة الإهمال العادي أو إذا فشلت في الوفاء بواجب يكون الوفاء به ضروريًا لأداء العقد على النحو الصحيح والذي يمكن أن يعتمد على الطرف المتعاقد الآخر – الواجب الأساسي -. 2.	في كل الأحوال الأخرى لا يكون الطرفان مسؤولين عن أي أضرار من أي نوع بغض النظر عن موضوع المطالبة بما في ذلك المسؤولية عن العقد. 3.	في حال بطلان اتفاقية الوكالة بالاستثمار تقتصر المطالبات المحتملة للمستخدم ضد التنافسية المالية الناتجة عن هذه الحقيقة على استرداد مبلغ الاستثمار فقط. 4.	لا تتحمل التنافسية المالية أي مسؤولية إضافية على ما ذكر أعلاه، منها الحالات الآتية: خصائص الخدمات أو الأضرار المستحقة وفقا لحدود المسؤولية للمنتج أو الأضرار الناجمة عن فقدان الحياة أو الإصابة الجسدية أو الأضرار بالصحة. 5.	تشمل المسؤولية موظفي التنافسية المالية والوكلاء المباشرين والأطراف الثالثة الأخرى التي تستخدمها التنافسية المالية للوفاء بالعقد. المادة السابعة: المخاطر العامة: 1.	يجب على المستخدم العلم بأن الاستثمار في الشركات الناشئة والمصدرة بمنصة التنافسية المالية ذات مخاطر عالية وقد يؤدي إلى الخسارة الكاملة، فكلما ارتفع معدل العائد المتوقع من الاستثمار كلما زاد خطر الخسارة. 2.	يجب على المستخدم العلم بأن الاستثمار طويل الأجل وذلك من خلال تقييم الفرص وإجمالي مخاطر الخسارة ومخاطر الإعسار ومخاطر التأرجح ومخاطر عدم توزيع الاستثمار وصعوبة التخارج والمخاطر المرتبطة بأنشطة الاستثمار والالتزامات أو التنبؤات حول الأداء المستقبل. 3.	تلتزم التنافسية المالية بدورها في المنصة، ولا تقدم خدمات أعمال الاستشارة. 4.	تلتزم الشركات المصدرة بصحة البيانات المقدمة، وتخلي التنافسية المالية مسؤوليتها عن مدى مصداقية البيانات. 5.	لا تضمن التنافسية المالية التوقعات المستقبلية للتطوير الناجح التي تقدمها الشركات المصدرة، ويتحمل المستخدم كافة القرارات الاستثمارية بشكل مستقل ويتحمل أي مخاطر مستقبلية. 6.	للمستخدم وحده الخيار في الاستثمار في الشركة المطروحة أم لا. 7.	يجب على المستخدم الاطلاع على كافة العواقب النظامية والاقتصادية والضريبية ذات الصلة بالاستثمار قبل الاستثمار وأثناء فترة الاحتفاظ.",
    crafted:"Crafted By Imcrinox Technologies",
    Risk_warning:"Risk warning",
    Risk_warning_answer:"Risk Notice: The user/investor acknowledges and understands with his knowledge and knowledge that investments of all kinds involve a degree of risk, and that investing in securities via the Competitiveness Financial Platform is considered a high-risk investment, and that Competitiveness Financial is not guaranteed or insured in any way, and his investment is subject to all types of risks. Risks and loss in whole or in part, and that investment in it may be subject to restrictions in terms of duration and the possibility of selling or liquidating it.",
    Register_as_Borrower:"Register as Borrower",
    Register_as_Investor:"Register as Investor",
    privacy_policy:"Privacy Policy",
    privacy:"يصف إشعار الخصوصية هذا كيف شركة التنافسية المالية (يشار إليها فيما بعد باسم 'الشركة')، تجمع البيانات الشخصية وكيفية معالجتها واستخدامها وحمايتها داخل المملكة العربية السعودية. تعريفات: أ‌.	في إشعار الخصوصية هذا، ما لم يقتضِ السياق خلاف ذلك، إن المصطلحات التالية المشار إليها لها المعاني التالية: •	الكيان التابع: تعني أي كيان تكون فيه الشركة في هذا الكيان داخل المملكة العربية السعودية. •	البيانات الشخصية: تعني البيانات التي قد تؤدي إلى تحديد هوية الشخص، بشكل مباشر أو غير مباشر، بما في ذلك على سبيل المثال لا الحصر: الاسم الأول والاسم الأخير أو العائلة ورقم الهوية الوطنية السعودية والعناوين ورقم الهاتف ورقم الحساب المصرفي ورقم البطاقة الائتمانية. ب‌.	الإشارة إلى 'الشركة' أو 'نحن' أو 'لنا'، بشكل فردي وجماعي، تشمل جميع الفروع والمكاتب والشركات الفرعية والشركات التابعة لأي من أعضاء المجموعة التي تجمع وتستخدم بياناتك الشخصية داخل المملكة العربية السعودية. البيانات الشخصية التي نجمعها: تختلف البيانات التي نجمعها بناءً على الغرض من استخدامها. ومع ذلك، فيما يلي أمثلة على البيانات التي نجمعها: •	البيانات التي يتم جمعها من خلال نماذج الطلبات أو الاستبيانات أو غيرها من الوثائق أو الاتصالات. على سبيل المثال لا الحصر الاسم الكامل وتاريخ الميلاد وأرقام الهوية. •	بيانات عن معاملاتك ومنتجاتك معنا، مثل نشاط الحساب واستخدام المنتجات. •	البيانات التي يتم جمعها من خلال استخدامك لخدماتنا أو موقعنا الإلكتروني أو تطبيقات الهواتف المحمولة (مثل ملفات تعريف الارتباط). •	البيانات التي يتم تبادلها أثناء تواصلنا معك، مثل طلبات خدمة العملاء والمرئيات التي تصلنا منك إما من خلال موقعنا الإلكتروني أو تطبيقات الهاتف المحمول أو حسابات وسائل التواصل الاجتماعي أو أي قنوات نستخدمها للتواصل مع العملاء. الأساس القانوني وأغراض جمع واستخدام بياناتك الشخصية: نقوم بجمع واستخدام البيانات وفقاً لما هو متطلب بناء على طبيعة الخدمات والأعمال. في معظم الحالات، يتضمن أساسنا القانوني وأغراضنا، على سبيل المثال لا الحصر: •	الامتثال لأية التزامات ومتطلبات صادرة عن الجهات القانونية والتنظيمية داخل المملكة العربية السعودية. •	السماح لنا بتقديم المنتجات أو الخدمات. •	لحمايتك من الاحتيال عن طريق إجراء عمليات التحقق من الهوية والائتمان أو التحقق من عدم وجود تعارض. •	تحسين منتجاتنا وخدماتنا وتجربتك المقدمة عبر قنواتنا. •	فهم احتياجاتك كعميل وأهليتك للمنتجات والخدمات. •	الترويج لمنتجات وخدمات استثمارية ومالية جديدة قد تهمك. كيف يتم جمع بياناتك الشخصية: هناك العديد من نقاط الاتصال التي تساعدنا في جمع بياناتك، وبعض الأمثلة: •	عند انشاء العلاقة والاستفادة من الخدمة - عندما تستخدم خدماتنا وتصبح عميلاً وتستفيد من منتجاتنا. •	تبادل المعلومات - عند إكمال نموذج ورفعه على موقعنا الإلكتروني أو تطبيقات الهاتف المحمول أو البريد الإلكتروني أو منشورات وسائل التواصل الاجتماعي أو عبر الاتصال بمركز العملاء أو المشاركة في الحملات الترويجية. •	التفاعل (وسائل التواصل الاجتماعي) - أي منشورات أو تفاعل أو تواصل تجريها معنا بشكل مباشر على قنوات التواصل الاجتماعي. •	نمط التصفح - بيانات حول كيفية استكشافك لموقعنا على الانترنت، وتوقيت زيارتك، وأنواع متصفح الإنترنت، وكيف تمت إحالتك إلى موقعنا. •	الاستطلاعات - استطلاعات الويب عبر الإنترنت التي تمكننا من جمع الآراء بشأن المواضيع. مثل، ما يعجبك وما لا يعجبك بشأن شكل ومظهر موقعنا الإلكتروني وتطبيقات الأجهزة المحمولة. ملاحظاتك القيمة تمكننا من تحسين جودة التجربة التي نقدمها لك كمنظمة. •	منك شخصياً أو من وكيلك المعتمد أومن ممثلك القانوني. •	في الحالات المقبولة قانونياً، من أطراف ثالثة ومصادر عامة. وهذا يشمل الجهات الحكومية وشركات ووكالات المعلومات الائتمانية. تخزين بياناتك الشخصية: ستكون بياناتك الشخصية: •	محتفظ بها طالما كان ذلك ضروريًا لتحقيق الغرض الذي تم جمعها من أجله. •	محتفظ بها داخل المملكة العربية السعودية. •	محتفظ بها لتلبية أي متطلبات قانونية وتنظيمية. حماية بياناتك الشخصية: نحن نضمن حماية بياناتك بشكل مناسب من خلال استخدام الإجراءات والاحتياطات الأمنية المادية والتقنية والإدارية والإجرائية اللازمة لمنع الوصول غير المصرح به أو الجمع أو الاستخدام أو الكشف أو النسخ أو التعديل أو التخلص منها. نحمي بياناتك بطريقة تتوافق مع أنظمة ولوائح حماية البيانات ذات العلاقة السارية بها في المملكة العربية السعودية. ومع ذلك، فإن الإنترنت ليس آمنًا بشكل كامل. الإفصاح عن بياناتك الشخصية: أ‌.	قد نشارك بيناتك مع أي من الأطراف المذكورة أدناه: 1.	أي محكمة أو أي جهة حكومية أو تنظيمية للامتثال لأي التزامات ومتطلبات صادرة عن جهات قانونية وتنظيمية داخل المملكة العربية السعودية. 2.	أي وكيل تحصيل ديون أو جهة مرخصة بتقديم خدمة المعلومات الائتمانية أو شركة تأمين. 3.	أي مزود خدمة مرتبط بالشركة بغرض تزويدك بالمنتجات أو الخدمات، وتحسين منتجاتنا وخدماتنا وتجربتك عبر قنواتنا، والترويج لمنتجات وخدمات الاستثمار المالي الجديدة التي قد تهمك. ب‌.	قد يتم التواصل معك و/أو إرسال إشعارات إليك عبر قنوات مختلفة مثل الرسائل القصيرة (SMS) و/أو البريد الإلكتروني و/أو الهاتف فيما يتعلق بمنتجاتنا وخدماتنا. التغييرات على إشعار الخصوصية نحتفظ بالحق في تعديل إشعار الخصوصية هذا في أي وقت. يشير تاريخ نفاذ إشعار الخصوصية، كما هو مذكور أدناه، إلى أحدث تاريخ تمت فيه مراجعة إشعار الخصوصية هذا أو تعديله. يتيح لك التحقق من تاريخ النفاذ أدناه تحديد ما إذا كانت هناك تغييرات منذ آخر مرة قمت فيها بمراجعة إشعار الخصوصية. لذلك، ننصحك بالتحقق بشكل دوري على إشعار الخصوصية هذا لضمان اطلاعك على النسخة المحدثة. استخدام ملفات تعريف الارتباط من أجل تحسين تجربة عملائنا، يستخدم موقعنا الإلكتروني تقنية قياسية تسمى 'ملفات تعريف الارتباط' لجمع معلومات حول كيفية استخدام موقعنا الإلكتروني، والتي قد تتضمن بياناتك. يعد استخدام ملفات تعريف الارتباط أمرًا ضروريًا لتشغيل موقعنا الإلكتروني. اتصل بنا في حالة وجود أي أسئلة، يمكنك التواصل معنا من خلال أي من المقر الرئيسي للشركة، والبريد الإلكتروني، والمحادثة الفورية، ووسائل التواصل الاجتماعي أو من خلال موقعنا الإلكتروني وتطبيق الهاتف المحمول. تاريخ النفاذ تم تعديل هذا الإشعار بتاريخ ,,,,,,, إخلاء مسئولية لا يهدف إشعار الخصوصية هذا إلى إنشاء أي حقوق تعاقدية من أي نوع أو أي حقوق قانونية أخرى، أو ينشئ أي التزامات علينا فيما يتعلق بأي طرف آخر أو نيابة عن أي طرف. عندما تقوم بتسجيل الدخول إلى مواقع الانترنت الخاصة بأي طرف ثالث، لن يسري إشعار الخصوصية هذا. إضافة إلى ذلك، نحن لسنا مسؤولين عن محتوى مواقع الويب الخاصة بأي طرف ثالث ولا نمثل أي طرف ثالث. لذلك، نوصيك بمراجعة سياسة الخصوصية والأمان لكل رابط تقوم بتسجيل الدخول إليه.",
    Settings:"Settings",
    value_cannot_exceed:"Value cannot exceed more than ",
    characters:"characters",
    User_Name:"User Name",
    Full_Name:"Full Name",

  },
  arabic_translations:{
    "Login_your_account":"تسجيل الدخول",
    "Please_enter_your_details_below":"الرجاء إدخال التفاصيل ",
    "This_field_is_required":"هذه الخانة مطلوبه",
    "Enter_valid_Mobile_Number":"ادخل رقم جوال صحيح وفعال",
    "LOGIN":"تسجيل الدخول",
    "Login_with_Mobile_Number":"تسجيل الدخول باستخدام رقم الجوال",
    "Login_with_Email":"تسجيل الدخول بالبريد الإلكتروني",
    "Login_with_Password":"تسجيل الدخول باستخدام كلمة المرور",
    "Verify_OTP":"التحقق من OTP",
    "A_verification_code_has_been_sent_to":"تم إرسال رمز التحقق إلى",
    "Please_Enter_valid_OTP":"الرجاء إدخال OTP صحيح",
    "Resend_OTP":"إعادة إرسال OTP",
    "bit":"128bit",
    "Secured_payment":"دفع آمن",
    "Copyrights":"حقوق النشر @ التنافسية المالية |جميع الحقوق محفوظة",
    "Dashboard":"لوحة القيادة",
    "My_Opportunities":"فرصي الاستثمارية",
    "Investments":"الاستثمارات",
    "Operations":"العمليات",
    "Add_Opportunity":"أضف فرصة استثمارية",
    "LOGOUT":"تسجيل خروج",
    "Opportunity_details":"تفاصيل الفرصة الاستثمارية",
    "Company_tagline_Slogan":"شعار الشركة / الشعار",
    "Companys_share_price":"سعر سهم الشركة",
    "Total_Valuation":"التقييم الإجمالي",
    "Min_Investment_per_investor":"الحد الأدنى للاستثمار لكل مستثمر",
    "Max_Investment_per_investor":"الحد الأقصى للاستثمار لكل مستثمر",
    "Upload_pictures_for_the_Opportunity":"تحميل الصور للفرصة لاستثمارية",
    "Supported_Format":"صيغةالملف المدعوم: Jpeg، Png، Jpg، Max Size 50kb",
    "Add_image":"إضافة صورة",
    "Fundraise_Opportunity_details":"تفاصيل تمويل الفرصة الاستثمارية",
    "How_much_amount_you_are_expecting_to_raise":"كم المبلغ الذي تتوقعه للتمويل؟",
    "About_company":"عن الشركة",
    "Write_Short_Bio_about_your_company":"اكتب نبذة مختصرة عن شركتك",
    "Reason_to_invest":"سبب الاستثمار",
    "Where_are_you_planning_to_allocate_the_funds":"أين تخطط ان تخصص مبلغ التمويل ؟",
    "Do_you_want_to_introduce_your_team":"هل تريد تقديم فريقك؟",
    "Yes":"نعم",
    "No":"لا",
    "UPLOAD_DP":"تحميل صورة الملف التعريفي",
    "Employee_name":"اسم الموظف",
    "Designation":"المسمى الوظيفي",
    "add_more_team_member":"إضافة المزيد من أعضاء الفريق",
    "Terms_Conditions":"الشروط والأحكام",
    "Write_your_Terms_Conditions_here":"اكتب الشروط والأحكام الخاصة بك هنا",
    "SUBMIT_START_OPPORTUNITY":"قدم وابدأ  فرصتك الاستثمارية",
    "Saudi_top_crowdfunding_platform":"أفضل منصة تمويل جماعي في السعودية",
    "We_Know_Your_Needs_Trusted_By":"نحن نعرف احتياجاتك ، يثق به 10 ملايين شخص",
    "No_Of_Investments":"عدد الاستثمارات",
    "Total_Investments":"إجمالي الاستثمارات",
    "Total_Profit":"اجمالي الربح",
    "No_Of_Opportunities":"عدد الفرص",
    "Active_Opportunities":"الفرص النشطة",
    "Rejected_Opportunities":"الفرص المرفوضة",
    "Personal_info":"معلومات شخصية",
    "View_KYC_Details":"عرض تفاصيل معلومات الحساب",
    "I_am_a":"أنا",
    "Borrower":"طالب النمويل",
    "Invester":"المستثمر",
    "First_name":"الاسم الاول",
    "Last_name":"العائله(الاسم الاخير)",
    "Optional":"اختياري",
    "Email":"البريد الإلكتروني",
    "Enter_valid_Email_Id":"أدخل بريد إلكتروني صالح",
    "Mobile_Number":"رقم الجواال",
    "Password":"كلمة المرور",
    "Password_Must_contain":" كلمة المرور يجب أن تحتوي على",
    "Weak":"ضعيف",
    "At_least_characters":"8 أحرف على الأقل",
    "A_capital_letter":"حرف انجليزي كبير",
    "A_small_letter":"حرف انجليزي صغير",
    "A_number":"رقم",
    "A_special_character":"رمز",
    "Confirm_Password":"تأكيد كلمة المرور",
    "Password_doesnt_matched":"كلمة المرور غير متطابقة",
    "I_accept_all":"موافق",
    "terms_conditions":"الشروط والأحكام",
    "CREATE_ACCOUNT":"انشاء حساب",
    "Status":"حالة",
    "Skip":"يتخطى ",
    "Upload_pictures_for":"تحميل الصور لـ",
    "About":"حول",
    "Tell_about_your":"أخبر عنك",
    "UPDATE":"تحديث",
    "SUBMIT":"إرسال",
    "faq_one":"ما هي منصة التنافسية المالية؟",
    "CFC_answer":"CFC منصة التنافسية المالية هي منصة إقراض رقمية تربط الشركات القائمة بالمستثمرين (المقرضين). تستخدم المنصة التكنولوجيا لربط الطرفين من خلال مبدأ التمويل الجماعي ، أي جمع مبالغ صغيرة من الأموال من العديد من الأفراد.",
    "faq_two":"كيف يمكن معرفة أوقات طرح الفرص؟",
    "CFC_answer_two":"يمكنك متابعة طرح الفرص من خلال زيارتك للمنصة,وكذلك اذا كنت مسجلا بالمنصة سوف يتم اشعارك ببريد الكتروني بشكل دوري للفرص المطروحه",
    "faq_three":"ما المقصود بمصطلح 'اعرف عميلك'؟",
    "CFC_answer_three":"يشير مصطلح 'اعرف عميلك' للقواعد المحددة مسبقًا من قبل هيئة السوق المالية (CMA) ويستخدم طوال عملية تحديد هوية العميل. وهي المتطلبات القياسية التي يجب اتباعها من قبل جميع الكيانات الخاضعة للتنظيم. يتضمن ذلك التحقق من الهوية وإثبات العنوان ومعلومات التوظيف والمعلومات العامة الأخرى. يحتاج المستثمرون إلى معرفة جميع متطلبات 'اعرف عميلك' قبل الانضمام إلى منصة CFC. سيجري قسم الامتثال فحوصات KYC المستمرة لضمان تحديث المعلومات باستمرار.",
    "faq_four":"ماهي الإجراءات المتخذة لضمان حماية بياناتي الخاصة ولحماية النظام في المنصة؟",
    "CFC_answer_four":"تم تطوير منصة التنافسية المالية على الخادم الخاص بنا. استخدمت التنافسية المالية اعلى ميزات الأمان 'الأفضل في فئتها' مثل التشفير وإدارة الهوية والوصول وأمن الشبكة. ويتم تطبيق هذه الميزات عبر النظام الأساسي بأكمله بدءًا من الاحتفاظ بالبيانات والوصول إلى التطبيقات واتصالات الويب والعمليات الداخلية. ونحن ملتزمون بالتنفيذ والتحسين المستمر وتطوير البرامج المحسنة للأمان ، والإدارة التشغيلية ، وممارسات التخفيف من التهديدات التي تعتبر ضرورية لحماية قوية للخدمات والبيانات",
    "Great_things_need_funds_We_know_you_do_too":" نجاح فرصتك بقدرة ادوات تقييم فرصتك وحجم تمويلك",
    "great_things_cfc":"CFC منصة التنافسية المالية هي منصة إقراض رقمية تربط الشركات القائمة بالمستثمرين (المقرضين). تستخدم المنصة التكنولوجيا لربط الطرفين من خلال مبدأ التمويل الجماعي ، أي جمع مبالغ صغيرة من الأموال من العديد من الأفراد.",
    "Shariah_Compliance":"منتجاتنا متوافقة100% مع الشريعه الاسلامية",
    "Free_promotion_for_your_campaign":" ترويج مجاني لحملتك",
    "withdraw_your_amount_instantly":"السحب الفوري لمبالغك",
    "How_to_start_your":"كيف تبدأ ملف",
    "fundraiser_on_Compp_Fintect":"لجمع التبرعات على Financial التنافسية.",
    "Easy_Just_Follow":"سهل ، ما عليك سوى اتباع الخطوات البسيطة أدناه",
    "Enter_Details":"ادخل تفاصيل معلوماتك",
    "kyc_answer":" قم بإدخال معلومات محددة ؛ معلومات شخصية ، معلومات عن المشروع ، البيانات الماليه المطلوب فقط وفقًا لشروط الجهة التنظيمية ولغرض دراسة الفرصه",
    "Verify_by_KYC":"التحقق من 'معلومات اعرف عميلك'",
    "verify_answer":"لجهة المنظمة تشترط التحقق من المعلومات والبيانات المقدمه من خلالك بواسطة الطرق الامنه ومن الجهات المرخص لها بذلك",
    "Get_Approval":"الحصول على موافقة",
    "approval_answer":" سوف تحصل على الموافقة واشعارك اليا من خلال نظام  ادارة علاقات العملاء في المنصة مثل البريد الالكتروني  والرسائل النصية.",
    "ready_to_start":"هل انت مستعد لتبدأ رحلة تمويل فرصتك⸮",
    "Get_approval_in_minutes":"احصل على الموافقة في 5 دقائق",
    "faq":"أسئلة مكررة",
    "Give_your_dreams_a_boost":"أعط دفعة لأحلامك ،",
    "Start_your_crowdfunding_today":"ابدأ التمويل الجماعي اليوم.",
    "Easy_Funding_options_For_you":"نوفر لك منتجات للتمويل واضحه تناسب مشروعك",
    "Funding_made_simple":"أصبح التمويل بسيطًا ومجزٍ ومريح",
    "select_registration_type":"حدد نوع التسجيل",
    "Individual":"الفرد",
    "Corporate":"شركة كبرى",
    "heading":"رؤية مستقبلية واعدة للمساهمة في القطاع المالي في المملكة العربية السعودية",
    "content_one":"من خلال حلول مالية تقنية مبتكرة ومتميزة للاستثمار والتمويل",
    "heading_two":"تأسست شركة التنافسية المالية في سبتمبر 2021م، وحصلت التنافسية على تصريح التقنية المالية في أعمال الأوراق المالية​ من هيئة السوق المالية في يونيه 2022م، لطرح أدوات الدين والاستثمار فيها.",
    "about_content_one":"التنافسية المالية هي منصة إلكترونية للتمويل الجماعي، تهدف إلى وصل المستثمرين بالفرص الاستثمارية لتمويل المشاريع، من خلال ترتيب إصدار وطرح أدوات الدين لتمويل مشاريع الشركات الصغيرة والمتوسطة، اﻟﺘﻲ ﺗﺴﺎﻫﻢ بدورها ﻓﻲ رﻓﻊ اﻟﻨﺎﺗﺞ اﻟﻤﺤﻠﻲ الإجمالي و ﺗﻮﻓﻴﺮ الوظائف، وعرض تلك الفرص في المنصة على المستثمرين عملاء المنصة",
    "about_content_two":"وكانت الهيئة قد إطلقت مختبر التقنية المالية عام 2018م، حرصاً منها على مواكبـــة الثورة التقنية المتســـارعة فـــي الســـوق الماليـــة. حيث تمتاز منظومة التقنية المالية في المملكة بجاذبية عالية مما يتيح للشركات تقديم الخدمات المبتكرة بسهولة",
    "about_content_three":"التنافسية المالية هي أحدى شركات التنافسية الدولية للتقنية وهي مؤسسة وطنية تهدف إلى تقديم الاستشارات التقنية المتكاملة للمنظمات والهيئات الحكومية والمشاركة في إعادة هيكلة الأنظمة والإجراءات لتعزيز الوصول لأهداف رؤية المملكة العربية السعودية ",
    "FINANCIAL_DIFFERENCE":"ويقوم فريق عمل التنافسية المالية بتسخير خبراته في التحليل الائتماني لمشاريع الشركات بناء على التحليل الكمي والتحليل النوعي لجدوى المشروع والشركة وإدارتها وقوائمها المالية، للوصول إلى النطاق التصنيفي لمخاطر الاستثمار. بعد ذلك، يتم إصدار أداة الدين وهي الصكوك، التي يتم الاستثمار فيها",
    "ABOUT_US":"حول التنافسية المالية ",
    "shariah":"التوافق مع الشريعه الاسلامية",
    "What_is_Sukuk":"ما هي الصكوك؟",
    "Sukuk_answer":"الصكوك  هي أوراق مالية تصدرها  الشركات (أو الحكومات)  لجمع الأموال من المستثمرين لفترة زمنية محددة بتاريخ سداد محدد، وخلال هذه الفترة عادةً ما توزع الصكوك معدل ربح (ثابت أو متغير) بشكل دوري. وفي نهاية عمر الصك، المعروفة بفترة الاستحقاق، يقوم مصدر الورقة المالية (المقترض) بسداد رؤوس الأموال التي تم جمعها من المستثمرين.",
    "How_do_I_make_profit":"كيف أحصل على الأرباح من هذه الفرص؟",
    "profit_answer":"لكل ﻓﺮﺻﺔ استثمارية توقيت توزيع مختلف عن الأخرى، كأن يكون رﺑﻊ ﺳﻨﻮي أو ﻧﺼﻒ ﺳﻨﻮي أو تسدد دﻓﻌﺔ واحدة، وهي فترة الاستحقاق في نهاية عمر الصك.",
    "terms":"التمهيد: يرتبط الاستثمار بالشركات الناشئة بمخاطر عالية، وقد يؤدي إلى الخسارة الكاملة لاستثمارك. يجب ألا تستثمر الأموال التي لا يمكنك تحمل خسارتها، وفي حال الخسارة يُقتصر على المبلغ المستثمر فقط. الاستثمار من خلال التنافسية المالية هو استثمار طويل الأجل ومناسب للمستثمرين على المدى الطويل. إن فرص الاستثمار في الوقت الحالي مخصصة للأشخاص المقيمين في المملكة العربية السعودية. يجب على المستخدم قراءة هذه الاتفاقية بعناية حيث توضح تفاصيل الخدمة التي تقدمها شركة التنافسية المالية وتحدد الالتزامات والحقوق بين التنافسية المالية والمستخدم، ويمنع استخدام المنصة في حال عدم فهم واستيعاب كافة مواد الاتفاقية. فهذه هي اتفاقية استخدام منصة التنافسية المالية وجميع صفحاتها الفرعية ولجميع العلاقات التعاقدية بين شركة التنافسية المالية. المادة الأولى: التعريفات: 1.	التنافسية المالية: شركة التنافسية المالية ذات السجل التجاري رقم (1010818020) وتاريخ 12/01/1444هـ، ومقرها بمدينة الرياض. 2.	المستخدم: هو الشخص الطبيعي أو الاعتباري المستفيد من خدمات منصة التنافسية المالية. 3.	المنصة: هي المنصة الإلكترونية لشركة التنافسية المالية والتي تقدم من خلال الموقع الإلكتروني خدمات إصدار أدوات الدين والاستثمار فيها للمنشآت طالبة التمويل. 4.	مخاطر إعسار المصدر: هي خطر إعسار الشريك -الشركة- ويؤدي ذلك إلى إفلاس حملة الصكوك إلى خسارة كلية. 5.	مخاطر التأرجح: هي سوء تصرف الموظفين أو الأعضاء مما ينتج عنه بشكل مباشر أو غير مباشر وتؤدي إلى إلى الإعسار. 6.	مخاطر عدم توزيع الاستثمار: هي عدم تحقيق المستثمر أي تنويع في المحفظة الاستثمارية، ويمكن تجنيبها بتوزيع مبالغ الاستثمار على شركات متعددة. 7.	صعوبة التخارج: هي ظروف خاصة لقابلية التخارج ولا توجد سوق ثانوية لتداول الصكوك في هذه اللحظة. 8.	نظام مكافحة جرائم المعلوماتية: الصادر بالمرسوم الملكي رقم (م/17) عام 1428هـ. 9.	نظام مكافحة غسل الأموال: الصادر بالمرسوم الملكي رقم (م/20) عام 1439هـ. المادة الثانية: التعريف بالمنصة: 1.	هي منصة عبر الإنترنت تمكن المستخدمين من الوصول إلى العروض المقدمة من قبل الشركات المدرجة في المنصة من خلال إصدار أدوات الدين والاستثمار بها، والاستثمار فيها على أساس اتفاقية استثمار، ولهذا الغرض تنشر الشركات معلوماتها عبر المنصة. 2.	في حالة الاستثمار من قبل المستخدمين لا تصبح التنافسية المالية طرفًا متعاقدًا بنفسها، ويبرم الاستثمار فقط بين المستخدمين والشركة المستثمر بها. 3.	يجب على الشركة المصدرة التي تقدم دعوتها للمستخدمين لتقديم عروضهم بناء على حملة إصدار الصكوك توفير المعلومات الخاصة بالاستثمار الجماعي على منصة التنافسية المالية. 4.	لا تتحمل التنافسية المالية مدى مصداقية البيانات التي تقدمها الشركة المصدرة. 5.	تسعى التنافسية المالية لتطوير خدماتها باستمرار، مما قد يستدعي في بعض الأحيان بإلغاء الخدمة مؤقتا أو بشكل دائم. 6.	يسري استخدام المنصة داخل المملكة العربية السعودية فقط. المادة الثالثة: المشغل والمزود للمنصة: شركة التنافسية المالية هي المشغل والمزود لمنصة التنافسية المالية، والخدمة المقدمة تخضع لشروط التنافسية المالية التالية التي يجب أن تطبق في النسخة السارية وقت تسجيل المستخدم. المادة الرابعة: التسجيل: 1.	يجب التسجيل كمستخدم في بعض أقسام منصة التنافسية المالية. 2.	يدخل المستخدم في عقد استخدام مع شركة التنافسية المالية بمجرد التسجيل. 3.	تقوم التنافسية المالية– في بعض الأحيان – بالتحقق من المستخدم باستخدام خدمة 'يقين' المقدمة من 'علم'. 4.	يجب على المستخدم أن يكون ذا أهلية وقدرة كافية على التعاقد. 5.	لا يجوز للقاصرين التسجيل. 6.	يجوز للتنافسية المالية فتح محفظة تكميلية بطلب من المستخدم ليستخدمها أشخاص دون الثامنة عشرة سنة. 7.	يتحمل من طلب فتح المحفظة التكميلية كامل المسؤولية عن استخدام المحفظة التكميلية، وتعتبرها التنافسية المالية جزءا من حساب محفظة المستخدم. 8.	يمكن لمستخدم المحفظة التكميلية إيداع أو سحب أموال من المحفظة الاستثمارية. 9.	يجب تقديم كافة البيانات المطلوبة من الأفراد أو المنشآت للتنافسية المالية خلال عملية التسجيل، ويتحمل المستخدم المسؤولية الكاملة حال إدخاله البيانات غير الصحيحة خلال عملية التسجيل أو أي مرحلة من مراحل استخدام خدمات المحفظة. 10.	يجب على المستخدم تقديم أي معلومات إضافية للتثبت من هويته أو لإثبات موثوقية أي أداة تمويل يسجلها المستخدم لاستخدامها مع التناقسية المالية. 11.	يجوز للتنافسية المالية أو طرف ثالث تتعاقد معه القيام بكافة التحريات التي تراها ضرورية للتحقق من المعلومات التي يتم تقديمها للتنافسية المالية، على سبيل المثال لا الحصر: فحص قواعد البيانات التجارية أو التقارير الائتمانية. 12.	لا تضمن التنافسية المالية ما يجري أثناء اتخاذ إجراءات التحقق من هوية المستخدم. 13.	يجب على المستخدم تصحيح بياناته فورا في حال تغيرها أو إدخالها بشكل غير كامل أو غير صحيح. 14.	يجب على المستخدم التأكد من سرية كلمة المرور. 15.	يجب إبلاغ التنافسية المالية فورا للاستخدام غير المصرح لكلمة المرور أو حساب المستخدم. 16.	لا يجوز استخدام الحساب لغير المستخدم سواء كان ذلك الشخص طبيعيًا أو معنويًا. 17.	تكون اتفاقية المستخدم واجبة على الطرفين من خلال النقر على رابط التأكيد المرسل عبر البريد الإلكتروني للمستخدم. 18.	تكون مدة اتفاقية المستخدم غير محددة بوقت معين. 19.	يحق للتنافسية المالية أو للمستخدم إنهاء اتفاقية المستخدم بأي وقت دون إشعار مسبق منها على سبيل المثال: حذف حساب المستخدم. 20.	تطبق جميع حدود المسؤولية والتعويضات في هذه الاتفاقية، حتى بعد إنهاء اتفاقية المستخدم. المادة الخامسة: اتفاق الوكالة بالاستثمار: 1.	يجب على المستخدم تعبئة النماذج على منصة التنافسية المالية والنقر على زر 'استثمر' نهاية النموذج. 2.	يقر المستخدم بقبول الاستثمار في الشركة المصدرة ووفقًا لشروطها. 3.	يجب بلوغ الحد الأدنى لمبلغ الاستثمار للجولة والمتفق عليه مع الشركة المصدرة سلفًا لكي تكون اتفاقية الاستثمار نافذة. 4.	يجوز إبرام عقد مكتوب بالإضافة إلى الإجراء المذكور أعلاه. 5.	يلتزم المستخدم باتفاق الاستثمار دون أي مطالبة بإبرام اتفاقية استثمار مستقلة. 6.	تلتزم الشركة بالمدة المحددة لعرض الاستثمارات على منصة التنافسية المالية. 7.	تلتزم التنافسية المالية بتزويد كافة الأطراف المتعاقدة بالبيانات اللازمة للتواصل مع الطرف الآخر. 8.	تلتزم التنافسية المالية بإرسال جميع المستندات إلكترونيًا من خلال البريد الإلكتروني للمستخدم. 9.	يتحمل المستخدم المسؤولية بكافة المستندات المرسلة من تلقاء نفسه بشكل إلكتروني أو مادي. 10.	عملاً بنص المادة (73) من لائحة مؤسسات السوق المالية يلزم على الشركة الاحتفاظ بأموال العميل في حساب باسمه لدى أحد البنوك المحلية ويوافق العميل على أحقية التنافسية المالية بالحصول على جميع العوائد والأرباح العائدة من الاحتفاظ بأموال العملاء في هذه الحسابات. ويجوز للشركة أن تحتفظ بأموال العميل لدى بنك خارجي أو تنفيذ تحويل خارجي خصماً من حسابه لدى البنك المحلي أو من أمواله الأخرى لديها إذا كان ذلك ضرورياً لتسوية صفقة أوراق مالية خارج المملكة. المادة السادسة: حدود المسؤولية: 1.	تتحمل التنافسية المالية المسؤولية نتيجة الإهمال الجسيم أو النية في حالة الإهمال العادي أو إذا فشلت في الوفاء بواجب يكون الوفاء به ضروريًا لأداء العقد على النحو الصحيح والذي يمكن أن يعتمد على الطرف المتعاقد الآخر – الواجب الأساسي -. 2.	في كل الأحوال الأخرى لا يكون الطرفان مسؤولين عن أي أضرار من أي نوع بغض النظر عن موضوع المطالبة بما في ذلك المسؤولية عن العقد. 3.	في حال بطلان اتفاقية الوكالة بالاستثمار تقتصر المطالبات المحتملة للمستخدم ضد التنافسية المالية الناتجة عن هذه الحقيقة على استرداد مبلغ الاستثمار فقط. 4.	لا تتحمل التنافسية المالية أي مسؤولية إضافية على ما ذكر أعلاه، منها الحالات الآتية: خصائص الخدمات أو الأضرار المستحقة وفقا لحدود المسؤولية للمنتج أو الأضرار الناجمة عن فقدان الحياة أو الإصابة الجسدية أو الأضرار بالصحة. 5.	تشمل المسؤولية موظفي التنافسية المالية والوكلاء المباشرين والأطراف الثالثة الأخرى التي تستخدمها التنافسية المالية للوفاء بالعقد. المادة السابعة: المخاطر العامة: 1.	يجب على المستخدم العلم بأن الاستثمار في الشركات الناشئة والمصدرة بمنصة التنافسية المالية ذات مخاطر عالية وقد يؤدي إلى الخسارة الكاملة، فكلما ارتفع معدل العائد المتوقع من الاستثمار كلما زاد خطر الخسارة. 2.	يجب على المستخدم العلم بأن الاستثمار طويل الأجل وذلك من خلال تقييم الفرص وإجمالي مخاطر الخسارة ومخاطر الإعسار ومخاطر التأرجح ومخاطر عدم توزيع الاستثمار وصعوبة التخارج والمخاطر المرتبطة بأنشطة الاستثمار والالتزامات أو التنبؤات حول الأداء المستقبل. 3.	تلتزم التنافسية المالية بدورها في المنصة، ولا تقدم خدمات أعمال الاستشارة. 4.	تلتزم الشركات المصدرة بصحة البيانات المقدمة، وتخلي التنافسية المالية مسؤوليتها عن مدى مصداقية البيانات. 5.	لا تضمن التنافسية المالية التوقعات المستقبلية للتطوير الناجح التي تقدمها الشركات المصدرة، ويتحمل المستخدم كافة القرارات الاستثمارية بشكل مستقل ويتحمل أي مخاطر مستقبلية. 6.	للمستخدم وحده الخيار في الاستثمار في الشركة المطروحة أم لا. 7.	يجب على المستخدم الاطلاع على كافة العواقب النظامية والاقتصادية والضريبية ذات الصلة بالاستثمار قبل الاستثمار وأثناء فترة الاحتفاظ.",
    "Risk_warning":"التحذيرات من المخاطر",
    "Risk_warning_answer":"إشعار المخاطر: يقر ويدرك المستخدم/المستثمر بعلمه واطلاعه بأن الاستثمارات بجميع أنواعها تنطوي على درجة من المخاطر، وأن الاستثمار في الأوراق المالية عبر منصة التنافسية المالية يعتبر استثمار عالي المخاطر، وأن الصكوك ليست مضمونة أو مؤمن عليها بأي شكل، كما أن استثماره عرضة لجميع أنواع المخاطر والخسارة بشكل كلي أو جزئي، وأن الاستثمار فيها قد يخضع لقيود من حيث المدة وإمكانية البيع أو التسييل.",
    

    "Investor":"مستثمر",
    "plan":"تخطط لجمع المال لأعمالك؟ تحقق من خياراتنا الخالية من المتاعب لك.",
    "invest":"استثمر في أعمال سريعة النمو معنا ، منصة استثمار آمنة ومأمونة بنسبة 100٪ في المملكة العربية السعودية.",
    "General":"عام",
    "Explore":"استكشف موقع CFC للحصول على معلومات واقتراحات ونصائح حول التمويل الجماعي والاستثمار.",
    "PRODUCT_FEATURES":"مواصفات المنتج",
    "What_makes_us_different":"ما الذي يجعلنا مختلفين؟",
    "To_Offer":"لعرض أدوات الدين والاستثمار فيها.",
    "Details_answer":"قدم معلومات الاتصال الخاصة بك وقم بتسجيل الدخول إلى حسابك لبدء العملية.",
    "Provide_your_national_ID":"أدخل رقم هويتك الوطنية واسمك الكامل لغرض التحقق من KYC.",
  "Submit_your_KYC":"أرسل بيانات KYC وبياناتك الشخصية واحصل على الموافقة في غضون 24 ساعة.",
    "Projects":"المشاريع",
    "Total_Raised":"إجمالي ما تم تحصيله",
    "Loan_terms":"مدة التمويل من 1 إلى 36 شهرًا",
    "Financing":"تمويل سريع خلال يوم واحد",
    "Customised_loan":"تمويل مخصص يناسب احتياجاتك",
    "Lets_get_in_touch":"نتشرف بالتواصل معك",
    "Type_your_message_here":"اكتب رسالتك هنا",
    "crafted":" بواسطة Imcrinox Technologies",
    "Register_as_Borrower":"تسجيل طالب التمويل",
    "Register_as_Investor":"تسجيل مستثمر",
    "privacy_policy":"إشعار الخصوصية",
    "privacy":"يصف إشعار الخصوصية هذا كيف شركة التنافسية المالية (يشار إليها فيما بعد باسم 'الشركة')، تجمع البيانات الشخصية وكيفية معالجتها واستخدامها وحمايتها داخل المملكة العربية السعودية. تعريفات: أ‌.	في إشعار الخصوصية هذا، ما لم يقتضِ السياق خلاف ذلك، إن المصطلحات التالية المشار إليها لها المعاني التالية: •	الكيان التابع: تعني أي كيان تكون فيه الشركة في هذا الكيان داخل المملكة العربية السعودية. •	البيانات الشخصية: تعني البيانات التي قد تؤدي إلى تحديد هوية الشخص، بشكل مباشر أو غير مباشر، بما في ذلك على سبيل المثال لا الحصر: الاسم الأول والاسم الأخير أو العائلة ورقم الهوية الوطنية السعودية والعناوين ورقم الهاتف ورقم الحساب المصرفي ورقم البطاقة الائتمانية. ب‌.	الإشارة إلى 'الشركة' أو 'نحن' أو 'لنا'، بشكل فردي وجماعي، تشمل جميع الفروع والمكاتب والشركات الفرعية والشركات التابعة لأي من أعضاء المجموعة التي تجمع وتستخدم بياناتك الشخصية داخل المملكة العربية السعودية. البيانات الشخصية التي نجمعها: تختلف البيانات التي نجمعها بناءً على الغرض من استخدامها. ومع ذلك، فيما يلي أمثلة على البيانات التي نجمعها: •	البيانات التي يتم جمعها من خلال نماذج الطلبات أو الاستبيانات أو غيرها من الوثائق أو الاتصالات. على سبيل المثال لا الحصر الاسم الكامل وتاريخ الميلاد وأرقام الهوية. •	بيانات عن معاملاتك ومنتجاتك معنا، مثل نشاط الحساب واستخدام المنتجات. •	البيانات التي يتم جمعها من خلال استخدامك لخدماتنا أو موقعنا الإلكتروني أو تطبيقات الهواتف المحمولة (مثل ملفات تعريف الارتباط). •	البيانات التي يتم تبادلها أثناء تواصلنا معك، مثل طلبات خدمة العملاء والمرئيات التي تصلنا منك إما من خلال موقعنا الإلكتروني أو تطبيقات الهاتف المحمول أو حسابات وسائل التواصل الاجتماعي أو أي قنوات نستخدمها للتواصل مع العملاء. الأساس القانوني وأغراض جمع واستخدام بياناتك الشخصية: نقوم بجمع واستخدام البيانات وفقاً لما هو متطلب بناء على طبيعة الخدمات والأعمال. في معظم الحالات، يتضمن أساسنا القانوني وأغراضنا، على سبيل المثال لا الحصر: •	الامتثال لأية التزامات ومتطلبات صادرة عن الجهات القانونية والتنظيمية داخل المملكة العربية السعودية. •	السماح لنا بتقديم المنتجات أو الخدمات. •	لحمايتك من الاحتيال عن طريق إجراء عمليات التحقق من الهوية والائتمان أو التحقق من عدم وجود تعارض. •	تحسين منتجاتنا وخدماتنا وتجربتك المقدمة عبر قنواتنا. •	فهم احتياجاتك كعميل وأهليتك للمنتجات والخدمات. •	الترويج لمنتجات وخدمات استثمارية ومالية جديدة قد تهمك. كيف يتم جمع بياناتك الشخصية: هناك العديد من نقاط الاتصال التي تساعدنا في جمع بياناتك، وبعض الأمثلة: •	عند انشاء العلاقة والاستفادة من الخدمة - عندما تستخدم خدماتنا وتصبح عميلاً وتستفيد من منتجاتنا. •	تبادل المعلومات - عند إكمال نموذج ورفعه على موقعنا الإلكتروني أو تطبيقات الهاتف المحمول أو البريد الإلكتروني أو منشورات وسائل التواصل الاجتماعي أو عبر الاتصال بمركز العملاء أو المشاركة في الحملات الترويجية. •	التفاعل (وسائل التواصل الاجتماعي) - أي منشورات أو تفاعل أو تواصل تجريها معنا بشكل مباشر على قنوات التواصل الاجتماعي. •	نمط التصفح - بيانات حول كيفية استكشافك لموقعنا على الانترنت، وتوقيت زيارتك، وأنواع متصفح الإنترنت، وكيف تمت إحالتك إلى موقعنا. •	الاستطلاعات - استطلاعات الويب عبر الإنترنت التي تمكننا من جمع الآراء بشأن المواضيع. مثل، ما يعجبك وما لا يعجبك بشأن شكل ومظهر موقعنا الإلكتروني وتطبيقات الأجهزة المحمولة. ملاحظاتك القيمة تمكننا من تحسين جودة التجربة التي نقدمها لك كمنظمة. •	منك شخصياً أو من وكيلك المعتمد أومن ممثلك القانوني. •	في الحالات المقبولة قانونياً، من أطراف ثالثة ومصادر عامة. وهذا يشمل الجهات الحكومية وشركات ووكالات المعلومات الائتمانية. تخزين بياناتك الشخصية: ستكون بياناتك الشخصية: •	محتفظ بها طالما كان ذلك ضروريًا لتحقيق الغرض الذي تم جمعها من أجله. •	محتفظ بها داخل المملكة العربية السعودية. •	محتفظ بها لتلبية أي متطلبات قانونية وتنظيمية. حماية بياناتك الشخصية: نحن نضمن حماية بياناتك بشكل مناسب من خلال استخدام الإجراءات والاحتياطات الأمنية المادية والتقنية والإدارية والإجرائية اللازمة لمنع الوصول غير المصرح به أو الجمع أو الاستخدام أو الكشف أو النسخ أو التعديل أو التخلص منها. نحمي بياناتك بطريقة تتوافق مع أنظمة ولوائح حماية البيانات ذات العلاقة السارية بها في المملكة العربية السعودية. ومع ذلك، فإن الإنترنت ليس آمنًا بشكل كامل. الإفصاح عن بياناتك الشخصية: أ‌.	قد نشارك بيناتك مع أي من الأطراف المذكورة أدناه: 1.	أي محكمة أو أي جهة حكومية أو تنظيمية للامتثال لأي التزامات ومتطلبات صادرة عن جهات قانونية وتنظيمية داخل المملكة العربية السعودية. 2.	أي وكيل تحصيل ديون أو جهة مرخصة بتقديم خدمة المعلومات الائتمانية أو شركة تأمين. 3.	أي مزود خدمة مرتبط بالشركة بغرض تزويدك بالمنتجات أو الخدمات، وتحسين منتجاتنا وخدماتنا وتجربتك عبر قنواتنا، والترويج لمنتجات وخدمات الاستثمار المالي الجديدة التي قد تهمك. ب‌.	قد يتم التواصل معك و/أو إرسال إشعارات إليك عبر قنوات مختلفة مثل الرسائل القصيرة (SMS) و/أو البريد الإلكتروني و/أو الهاتف فيما يتعلق بمنتجاتنا وخدماتنا. التغييرات على إشعار الخصوصية نحتفظ بالحق في تعديل إشعار الخصوصية هذا في أي وقت. يشير تاريخ نفاذ إشعار الخصوصية، كما هو مذكور أدناه، إلى أحدث تاريخ تمت فيه مراجعة إشعار الخصوصية هذا أو تعديله. يتيح لك التحقق من تاريخ النفاذ أدناه تحديد ما إذا كانت هناك تغييرات منذ آخر مرة قمت فيها بمراجعة إشعار الخصوصية. لذلك، ننصحك بالتحقق بشكل دوري على إشعار الخصوصية هذا لضمان اطلاعك على النسخة المحدثة. استخدام ملفات تعريف الارتباط من أجل تحسين تجربة عملائنا، يستخدم موقعنا الإلكتروني تقنية قياسية تسمى 'ملفات تعريف الارتباط' لجمع معلومات حول كيفية استخدام موقعنا الإلكتروني، والتي قد تتضمن بياناتك. يعد استخدام ملفات تعريف الارتباط أمرًا ضروريًا لتشغيل موقعنا الإلكتروني. اتصل بنا في حالة وجود أي أسئلة، يمكنك التواصل معنا من خلال أي من المقر الرئيسي للشركة، والبريد الإلكتروني، والمحادثة الفورية، ووسائل التواصل الاجتماعي أو من خلال موقعنا الإلكتروني وتطبيق الهاتف المحمول. تاريخ النفاذ تم تعديل هذا الإشعار بتاريخ ,,,,,,, إخلاء مسئولية لا يهدف إشعار الخصوصية هذا إلى إنشاء أي حقوق تعاقدية من أي نوع أو أي حقوق قانونية أخرى، أو ينشئ أي التزامات علينا فيما يتعلق بأي طرف آخر أو نيابة عن أي طرف. عندما تقوم بتسجيل الدخول إلى مواقع الانترنت الخاصة بأي طرف ثالث، لن يسري إشعار الخصوصية هذا. إضافة إلى ذلك، نحن لسنا مسؤولين عن محتوى مواقع الويب الخاصة بأي طرف ثالث ولا نمثل أي طرف ثالث. لذلك، نوصيك بمراجعة سياسة الخصوصية والأمان لكل رابط تقوم بتسجيل الدخول إليه.",
    "Settings":"إعدادات",
    "value_cannot_exceed":"لا يمكن أن تتجاوز القيمة أكثر من",
    "characters":"الشخصيات",
    "User_Name":"اسم االمستخدم",
    "Full_Name":"الاسم بالكامل",




  },
};
