// This file can be replaced during build by using the `fileReplacements` array.
// `ng build` replaces `environment.ts` with `environment.prod.ts`.
// The list of file replacements can be found in `angular.json`.

export const environment = {
  production: false,
  firebaseConfig: {
    apiKey: "AIzaSyAkw7ImOFHF3I5y52W2yydQb9ANhpuR-3E",//I had to change this to not have 403 ERROR - done by rashed rabadi
    authDomain: "aaaa-6d056.firebaseapp.com",
    databaseURL: "https://aaaa-6d056-default-rtdb.firebaseio.com",
    projectId: "aaaa-6d056",
    storageBucket: "aaaa-6d056.appspot.com",
    messagingSenderId: "1021417514491",
    appId: "1:1021417514491:web:22abc3ab52fbafe486d75e",
    measurementId: "G-GEMW853ESY"
  },
  english_translations: {
    Login_your_account: "Login your account",
    Please_enter_your_details_below: "Please enter your details below",
    This_field_is_required: "This field is required",
    Enter_valid_Mobile_Number: "Enter valid Mobile Number",
    LOGIN: "LOGIN",
    Login_with_Mobile_Number: "Login with Mobile Number",
    Login_with_Email: "Login with Email",
    Login_with_Password: "Login with Password",
    Verify_OTP: "Verify OTP",
    A_verification_code_has_been_sent_to: "A verification code has been sent to",
    Please_Enter_valid_OTP: "Please Enter valid OTP",
    Resend_OTP: "Resend OTP",
    bit: "128bit",
    Secured_payment: "Secured payment",
    Copyrights: "Copyrights @ Competitiveness Financial | All Rights Reserved",
    Dashboard: "Dashboard",
    My_Opportunities: "My Opportunities",
    Investments: "Investments",
    Operations: "Operations",
    Add_Opportunity: "Add Opportunity",
    LOGOUT: "LOGOUT",
    Opportunity_details: "Opportunity details",
    Company_tagline_Slogan: "Company tagline/Slogan",
    Companys_share_price: "Company’s share price",
    Total_Valuation: "Total Valuation",
    Min_Investment_per_investor: "Min Investment per investor",
    Max_Investment_per_investor: "Max Investment per investor",
    Upload_pictures_for_the_Opportunity: "Upload Opportunity Logo",
    Supported_Format: "Supported Format: Jpeg, Png, Jpg, Max Size 50Kb",
    Add_image: "Add image",
    Upload_Files:"Upload Files",
    Fundraise_Opportunity_details: "Fundraise Opportunity details",
    How_much_amount_you_are_expecting_to_raise: "How much amount you are expecting to raise?",
    About_company: "About company",
    Write_Short_Bio_about_your_company: "Write Short Bio about your company",
    Reason_to_invest: "Reason to invest",
    Where_are_you_planning_to_allocate_the_funds: "Where are you planning to allocate the funds?",
    Do_you_want_to_introduce_your_team: "Do you want to introduce your team?",
    Yes: "Yes",
    No: "No",
    UPLOAD_DP: "UPLOAD DP",
    Employee_name: "Employee name",
    Designation: "Designation",
    add_more_team_member: "add more team member",
    Terms_Conditions: "Terms & Conditions",
    Write_your_Terms_Conditions_here: "Write your Terms & Conditions here",
    SUBMIT_START_OPPORTUNITY: "SUBMIT & START OPPORTUNITY",
    Saudi_top_crowdfunding_platform: "Saudi’s top crowdfunding platform",
    We_Know_Your_Needs_Trusted_By: "We Know Your Needs, Trusted By 10 Million People",
    No_Of_Investments: "No. Of Investments",
    Total_Investments: "Total Investments",
    Total_Profit: "Total Profit",
    No_Of_Opportunities: "No. Of Opportunities",
    Active_Opportunities: "Active Opportunities",
    Rejected_Opportunities: "Rejected Opportunities",
    Personal_info: "Personal info",
    View_KYC_Details: "View Account Details",
    I_am_a: "I am a",
    Borrower: "Finance seeker",
    Invester: "Invester",
    First_name: "First name",
    Last_name: "Last name",
    Optional: "Optional",
    Email: "Email",
    Enter_valid_Email_Id: "Enter valid Email Id",
    Mobile_Number: "Mobile Number",
    Password: "Password",
    Password_Must_contain: "Password Must contain",
    Weak: "Weak",
    At_least_characters: "At least 8 characters",
    A_capital_letter: "A capital letter",
    A_small_letter: "A small letter",
    A_number: "A number",
    A_special_character: "A special character",
    Confirm_Password: "Confirm Password",
    Password_doesnt_matched: "Password doesn't matched",
    Number_of_Oppertunity: "Number of Oppertunity",
    Total_Amount_Raised: "Total Amount Raised",
    Total_Repayment: "Total Repayment",
    Profile_Info: "Profile Info",
    I_accept_all: "I accept all",
    terms_conditions: "terms & conditions",
    CREATE_ACCOUNT: "CREATE ACCOUNT",
    Status: "Status",
    Skip: "Skip",
    Upload_pictures_for: "Upload pictures for",
    About: "About",
    Tell_about_your: "Tell about your",
    UPDATE: "UPDATE",
    SUBMIT: "SUBMIT",
    faq_one: "What is CFC Platform ?",
    CFC_answer: "CFC is a digital lending platform that connects established businesses with investor (lenders). The platform uses technology to connect both parties through the principle of crowdfunding, - i.e. raising small amounts of funds from many individuals.",
    faq_two: "How can I know the times of offering opportunities?",
    CFC_answer_two: "You can follow up on the offer of opportunities by visiting CFC  platform, as well as if you are registered on the platform, you will be notified by e-mail periodically of the opportunities.",
    faq_three: "What is meant by the term 'KYC'?",
    CFC_answer_three: "The term KYC stands for “Know Your Customer” and is used throughout the client identification process. The pre-set KYC rules by Capital Market Authority (CMA) are the standard requirements that need to be followed by all regulated entities. This includes identity verification, proof of address, employment information, and other general information. Investors need to clear all KYC requirements prior to being onboarded on the CFC platform. The compliance department will conduct ongoing KYC checks to ensure information is constantly updated.",
    faq_four: "What measures are in place to ensure security around my data and the integrity of your platform?",
    CFC_answer_four: "CFC Platform  has been developed on our proprietary server. CFC Platform has leveraged the “best in breed” security features such as encryption, identity and access management, and network security. These features are applied across the whole platform from the holding of data, application access, web communications, and back office operations. We are committed to implement and continuously improve security-aware software development, operational management, and threat-mitigation practices that are essential to the strong protection of services and data",
    Great_things_need_funds_We_know_you_do_too: "Great things need funds, We know you do too.",
    great_things_cfc: "CFC is a digital lending platform that connects established businesses with investor (lenders). The platform uses technology to connect both parties through the principle of crowdfunding, - i.e. raising small amounts of funds from many individuals.",
    Shariah_Compliance: "100% Shariah Compliance",
    Free_promotion_for_your_campaign: "Free promotion for your campaign",
    withdraw_your_amount_instantly: "withdraw your amount instantly",
    How_to_start_your: "How to start your",
    fundraiser_on_Compp_Fintect: "fundraiser on Competitiveness Financial.",
    Easy_Just_Follow: "Easy, Just Follow The Simple Steps Below",
    Enter_Details: "Enter Details",
    kyc_answer: "You are required to Enter a specific information;personal ,venture info ,just required financial statement according to the regulator terms and for Due diligence purpose.",
    Verify_by_KYC: "Verify by KYC",
    verify_answer: "The Regulator requires to verify your information and data provided by you through the safe channels  and the authorized authorities",
    Get_Approval: "Get Approval",
    approval_answer: "You will get approval and be notified automatically through the platform's CRM system such as email and text messages.",
    ready_to_start: "Ready to start your first Fund raise?",
    Get_approval_in_minutes: "Get approval in 5 mins",
    faq: "Frequently asked questions",
    Give_your_dreams_a_boost: "Give your dreams a boost,",
    Start_your_crowdfunding_today: "Start your crowdfunding today.",
    Easy_Funding_options_For_you: "Easy Funding options For you",
    Funding_made_simple: "Funding made simple, rewarding & fun",
    select_registration_type: "Select Registration type",
    Individual: "Individual",
    Corporate: "Corporate",
    heading: "A promising future vision to contribute to the financial sector in the Kingdom of Saudi Arabia",
    content_one: "through innovative and distinguished technical financial solutions for investment and financing.",
    heading_two: "Competitiveness Financial Company (CFC) was established in September 2021, and the Competitiveness obtained a financial technology permit in securities business from the Capital Market Authority (CMA) in June 2022, to offer and invest in debt instruments.",
    about_content_one: "Competitiveness Financial is an electronic platform for crowdfunding, which aims to connect investors with investment opportunities to finance projects, by arranging the issuance and offering of debt instruments to finance projects of small and medium-sized companies, which in turn contribute to raising the GDP and providing jobs, and presenting those opportunities in the platform to investors and clients Platform.",
    about_content_two: "CMA had launched the Financial Technology Lab in 2018, in order to keep pace with the accelerating technological revolution in the financial market. The financial technology system in the Kingdom is highly attractive, allowing companies to easily provide innovative services.",
    about_content_three: "CFC is one of the international technology competitiveness companies. It is a national institution that aims to provide integrated technical consultancy to government organizations and bodies and participate in restructuring systems and procedures to enhance access to the goals of the vision of the Kingdom of Saudi Arabia.",
    Investor: "Investor",
    plan: "Planning to raise money for your business? Checkout our hassle free options for you.",
    invest: "Invest in fast growing businesses with us, 100% safe and secure investment platform in Saudi arabia.",
    General: "General",
    Explore: "Explore CFC website for info, suggestions and advise on crowdfunding and investment.",
    PRODUCT_FEATURES: "PRODUCT FEATURES",
    FINANCIAL_DIFFERENCE: "The Financial Competitiveness Team harnesses its expertise in the credit analysis of  projects based on quantitative and qualitative analysis of the feasibility of the project and the company, its management and its financial statements, to reach the rating scale for investment risks. After that, the debt instrument, which is the sukuk, is issued, in which the investment is made.",
    What_makes_us_different: "What makes us different?",
    ABOUT_US: "About CFC",
    To_Offer: "To Offer And Invest In Debt Instruments.",
    Details_answer: "Provide your contact information and login your account to start the process.",
    Provide_your_national_ID: "Provide your national ID number and your full name for the KYC verification purpose.",
    Submit_your_KYC: "Submit your KYC and personal details and get approval within 24hrs.",
    shariah: "Sharia compliant",
    Projects: "Projects",
    Total_Raised: "Total Raised",
    Loan_terms: "Loan terms from 1- 36 months",
    Financing: "Financing as quick as 1 day",
    Customised_loan: "Customised loans that fits your needs",
    What_is_Sukuk: "What is Sukuk?",
    Sukuk_answer: "Sukuk are securities issued by companies (or governments) to raise funds from investors for a specified period of time with a specified repayment date, during which period the sukuk usually distribute a profit rate (fixed or variable) periodically. At the end of the life of the instrument, known as the maturity period, the issuer of the security (the Finance seeker) repays the capital raised from the investors.",
    How_do_I_make_profit: "How do I make profit?",
    profit_answer: "Each investment opportunity has a different distribution timing from the other, such as if it is quarterly, semi-annually, or paid in one payment, which is the maturity period at the end of the life of the instrument.",
    Lets_get_in_touch: "Let’s get in touch",
    Type_your_message_here: "Type your message here",
    crafted: "Crafted By Imcrinox Technologies",
    Risk_warning: "Risk warning",
    Risk_warning_answer: "Risk Notice: The user/investor acknowledges and understands with his knowledge and knowledge that investments of all kinds involve a degree of risk, and that investing in securities via the Competitiveness Financial Platform is considered a high-risk investment, and that Competitiveness Financial is not guaranteed or insured in any way, and his investment is subject to all types of risks. Risks and loss in whole or in part, and that investment in it may be subject to restrictions in terms of duration and the possibility of selling or liquidating it.",
    Register_as_Borrower: "Register as Finance seeker",
    Register_as_Investor: "Register as Investor",
    privacy_policy: "Privacy Policy",
    "terms_head_one": "التمهيد:",
    "terms_head_two": "المادة الأولى: التعريفات:",
    "terms_head_three": "المادة الثانية: التعريف بالمنصة:",
    "terms_head_four": "المادة الثالثة: المشغل والمزود للمنصة:",
    "terms_head_five": "المادة الرابعة: التسجيل:",
    "terms_head_six": "المادة الخامسة: اتفاق الوكالة بالاستثمار:",
    "terms_head_seven": "المادة السادسة: حدود المسؤولية:",
    "terms_head_eight": "المادة السابعة: المخاطر العامة:",
    "terms_content_one": "يرتبط الاستثمار بالشركات الناشئة بمخاطر عالية، وقد يؤدي إلى الخسارة الكاملة لاستثمارك. يجب ألا تستثمر الأموال التي لا يمكنك تحمل خسارتها، وفي حال الخسارة يُقتصر على المبلغ المستثمر فقط. الاستثمار من خلال التنافسية المالية هو استثمار طويل الأجل ومناسب للمستثمرين على المدى الطويل. إن فرص الاستثمار في الوقت الحالي مخصصة للأشخاص المقيمين في المملكة العربية السعودية. يجب على المستخدم قراءة هذه الاتفاقية بعناية حيث توضح تفاصيل الخدمة التي تقدمها شركة التنافسية المالية وتحدد الالتزامات والحقوق بين التنافسية المالية والمستخدم، ويمنع استخدام المنصة في حال عدم فهم واستيعاب كافة مواد الاتفاقية. فهذه هي اتفاقية استخدام منصة التنافسية المالية وجميع صفحاتها الفرعية ولجميع العلاقات التعاقدية بين شركة التنافسية المالية",
    "terms_content_four": "شركة التنافسية المالية هي المشغل والمزود لمنصة التنافسية المالية، والخدمة المقدمة تخضع لشروط التنافسية المالية التالية التي يجب أن تطبق في النسخة السارية وقت تسجيل المستخدم.",
    "privacy_heading": "يصف إشعار الخصوصية هذا كيف شركة التنافسية المالية (يشار إليها فيما بعد باسم 'الشركة')، تجمع البيانات الشخصية وكيفية معالجتها واستخدامها وحمايتها داخل المملكة العربية السعودية.",
    "privacy_heading_one": "تعريفات:",
    "privacy_heading_two": "البيانات الشخصية التي نجمعها:",
    "privacy_heading_three": "الأساس القانوني وأغراض جمع واستخدام بياناتك الشخصية:",
    "privacy_heading_four": "كيف يتم جمع بياناتك الشخصية:",
    "privacy_heading_five": "تخزين بياناتك الشخصية:",
    "privacy_heading_six": "حماية بياناتك الشخصية:",
    "privacy_heading_seven": "الإفصاح عن بياناتك الشخصية:",
    "privacy_heading_eight": "التغييرات على إشعار الخصوصية",
    "privacy_heading_nine": "استخدام ملفات تعريف الارتباط",
    "privacy_heading_ten": "اتصل بنا",
    "privacy_heading_eleven": "تاريخ النفاذ",
    "privacy_heading_tewlve": "إخلاء مسئولية",
    "Settings": "Settings",
    "value_cannot_exceed": "Value cannot exceed more than ",
    "characters": "characters",
    "User_Name": "User Name",
    "Full_Name": "Full Name",
    "investment": "Invist now",
    "setting": "Setting",
    //Added By Qaysar For Translate the sit
    Envist: "Envist",
    Investers: "Investors",
    Price_Per_Share: "Price Per Share",
    Valuation: "Valuation",
    Min_Investment: "Min Investment",
    Max_Investment: "Max Investment",
    Team: "Team Work",
    Terms: "Terms",
    Reasons_to_Invest: "Reasons to Invest",
    Invest: "Invest",
    Enter_Amount: "Enter Amount",
    All_Opportunities: "All Opportunities",
    Closed_Opportunities: "Closed Opportunities",
    Sorry_No_data_to_display: "Sorry, No data to display!",
    All_Campaign: "All Campaign",
    Closed_Campaign: "Closed Campaign",
    Raised: "Raised",
    Modal_title: "Payment Screen",
    Amount: "Amount",
    Close: "Close",
    Pay: "Pay",
    Save_changes: "Save changes",
    Allocation: "Allocation",
    Updates: "Updates",
    Funds_allocation: "Funds allocation",
    Please_enter_your_payment_details: "Please enter your payment details",
    Credit_Card: "Credit Card",
    Card_Number: "Card Number",
    Expiry_Month: "Expiry Month",
    Expiry_Year: "Expiry Year",
    Security_Code: "Security Code",
    Cardholder_Name: "Cardholder Name",
    Kyc_Details: "Kyc Details",
    Edit_Profiel: "Edit Profiel",
    // Number_of_Oppertunity: "Number of Oppertunity",
    // Total_Amount_Raised: "Total Amount Raised",
    // Total_Repayment: "Total Repayment",
    // Profile_Info: "Profile Info",
    Name: "Name",
    Email_ID: "Email ID",
    Contact_Number: "Contact Number",
    View_Opportunity: "View Opportunity",
    Total_Amount_Invested: "Total Amount Invested",
    Number_of_Investment: "Number of Investment",
    // Total_Amount_Invested: "Total Amount Invested",
    Account_Number: "Account Number",
    Retail_And_Sophisticated_Investors: "Retail And Sophisticated Investors (Only Saudis & Iqama Holders)",
    Total_Opportunities: "Total Opportunities",
    Funded: "Funded",
    Pledged_Of_SAR: "Total Funding SAR",
    Goal: "",
    Fundin_Status: "Fundin Status",
    Closedp: "Closedp",
    Total_Invested: "Total Invested",
    Closed_investment: "Closed investment",
    PREVIEW: "PREVIEW",
    Back: "Back",
    Received_Investment: "Received Investment",
    Date: "Date",
    Transaction_ID: "Transaction ID",
    Invested: "Invested",
    Raised_amount: "Raised amount",
    Pending_amount: "Pending amount",
    Edit_Profile: "Edit Profile",
    Approved: "Approved",
    Pending: "Pending",
    verify: "verify",
    Check_Data: "Check Data",
    Next: "Next",
    Password_must_be_8_characters_or_more: "Password must be 8 characters or more",
    Forget_Password: "Forget Password",
    Investment_opportunities: "Investment opportunities",
    Open_and_ongoing_popular_croudfungings_for_you_to_choose_from: "Open and ongoing popular croudfungings for you to choose from",
    Close_Date: "Close Date",
    Open_Date:"Open Date",
    View_Details: "View Details",
    EXPLORE_ALL: "EXPLORE ALL",
    Upcoming_opportunities: "Upcoming opportunities",
    WeatherFlow_Tempest_Inc: "WeatherFlow-Tempest, Inc",
    Controlling_the_Cost_of_Weather: "Controlling the Cost of Weather",
    Amount_Paid: "Amount Paid",
    Transaction_History: "Transaction History",
    Upcoming_Payments: "Upcoming Payments",
    Sort_By_Recent: "Sort By : Recent",
    Recent: "Recent",
    Monthly_Installment: "Monthly Installment",
    Amount_paid: "Amount paid",
    Principle_paid: "Principle paid",
    Principle_Left: "Principle Left",
    Due_payment: "Due payment",
    PAY_NOW: "PAY NOW",
    Installment_paid: "Installment paid",
    Available_cash_in_your_CFC_wallet: "Available cash in your CFC wallet",
    ADD_AMOUNT: "ADD AMOUNT",
    Your_active_funds: "Your active funds",
    FlyForward_Corp: "FlyForward Corp",
    The_Next_Tech_Of_Aviation: "The Next Tech Of Aviation",
    Amount_Raised: "Amount Raised",
    Due_this_month: "Due this month",
    Share_Price: "Share Price",
    Minimum_Investment: "Minimum Investment",
    Maximum_Investment: "Maximum Investment",
    Invested_Date: "Invested Date",
    Invested_Amount: "Invested Amount",
    Due_Date: "Due Date",
    Principle_Expected: "Principle Expected",
    Interest_Expected: "Interest Expected",
    Fees_Expected: "Fees Expected",
    Total_Expected: "Total Expected",
    Principle_Paid: "Principle Paid",
    Interest_Paid: "Interest Paid",
    Fees_Paid: "Fees Paid",
    Total_Paid: "Total Paid",
    Paid_Date: "Paid Date",
    Principle_Due: "Principle Due",
    Interest_Due: "Interest Due",
    Fees_Due: "Fees Due",
    Total_Due: "Total Due",
    Profit: "Profit",
    Priciple: "Priciple",
    Total: "Total",
    MyProfile: "My Profile",
    change_password: "change password",
    Old_Passsword: "Old Passsword",
    New_Password: "New Password",
    Save: "Save",
    CopyWrightCfC: "Copyrights @ Competitiveness Financial | All Rights Reserved",
    Principle_Amount: "Principle Amount",
    Profit_Amount: "Profit Amount",
    Total_Amount: "Total Amount",
    Enter_Valid_Mobile_Number_Ex: "Enter Valid Mobile Number (Ex: 0551234567 or 551235678)",
    Debit_History: "Debit History",
    Credit_History: "Credit History",
    Amount_Raised_Intrese: "Amount Raised Intrese",
    Final_Amount: "Final Amount",
    Upvoming_Transaction_History: "Upvoming Transaction History",
    Installment_To_Pay: "Installment To Pay",
    Total_Amount_to_be_Paid: "Total Amount to be Paid",
    amountYetToReceive: "Amount Yet to Receive",
    Withdraw_on: "Withdraw On",
    Final_Reciveable: "Final Reciveable",
    Recieved_Amount: "Recieved Amount",
    Withdrawl_Amount: "Withdrawl Amount",
    Profit_Received: "Profit Received",
    Credited_Amount: "Credited Amount",
    My_Wallet: "My Wallet",
    amountYetToPay: "Amount Yet to Pay",
    Enter_the_Amount: "Enter the Amount",
    Amount_Received: "Amount Received",
    Thank_You_Application_recieved: "Thank you, We have received your application",
    Review_profile_msg: "We’re reviewing your profile, Our representatives will reach out to you soon!",
    OK_Thanks_Btn: "OKAY, THANKS",
    Competitiveness_Financial:"Competitiveness Financial",
    Investment:"Investment",
    Raise:"Rais",
    Legal:"Legal",
    Account:"Account",
    Sign_Out:"Sign Out",
    Wallet:"Wallet",
    Payments:"Payments",
    Opportunity_List:"Opportunity List",
    ID:"ID",
    Attachment:"Attachment",
    //Added for sukuk documents page
    tar7_document_note_title_1_a:" مستند الطرح – صكوك المرابحة 1-111-22 ",
    tar7_document_note_title_1_b:" والمطروحة على منصة شركة التنافسية المالية ",
    tar7_document_note_1_1:" تحتوي النشرة على معلومات المصدر والمستفيد ",
    tar7_document_note_1_2:" والمعلومات المتعلقة بالإصدار الأول ",
    tar7_document_note_1_3:" يعمل المستفيد وفقا للرقم الموحد رقم ",
    tar7_document_note_1_3_1:" تجاوزت مبيعات المستفيد حسب القوائم المالية ",
    tar7_document_note_1_4:" لعامي ",
    tar7_document_note_1_5:" وهامش صافي أرباح ",
    tar7_document_note_1_6:" على التوالي من إجمالي المبيعات ",
    tar7_document_note_1_7:" لدى المستفيد نسبة سيولة جارية تبلغ ",
    tar7_document_note_1_8:" وعائد على الاصول يبلغ ",
    tar7_document_note_1_9:" وإجمالي الديون على الاصول ",
    tar7_document_note_1_10:" حسب القوائم المالية لعام ",
    tar7_document_note_1_11:" يعتزم المستفيد طرح برنامج لإصدار صكوك مرابحة بقيمة ",
    tar7_document_note_1_12:" ريال سعودي، بناء عليه، سيكون طرح الإصدار الأول من البرنامج بقيمة ",
    tar7_document_note_1_13:" ريال سعودي تستحق بتاريخ ",
    tar7_document_note_1_14:" بعائد سنوي ",
    tar7_document_note_1_15:" على القيمة الاسمية للصك ",
    tar7_document_note_1_16:" ريال سعودي ويتم توزيع الأرباح بشكل دوري، كما سيتم إطفاء صكوك كل إصدار ذي صلة دفعة واحدة في تاريخ الإطفاء ",
    tar7_document_note_1_17:" على المستثمرين الراغبين بالاستثمار في الإصدار التسجيل كمستثمر في منصة التنافسية المالية للاستثمار على الرابط التالي ",
    tar7_document_note_1_18:" الحد الأعلى للمستثمرين المؤهلين هو تغطية كامل قيمة الإصدار، بينما الحد الأعلى للمستثمر الفرد هو ( 20,000 ) عشرون ألف ريال سعودي لكل 'مستفيد' للسنة الواحدة، علماً أن الحد الأدنى للاستثمار هو صك واحد بقيمة (1,000) ألف ريال سعودي.",

    tar7_document_note_title_2:"إشعار هام",
    tar7_document_note_2_1:"تحتوي نشرة الإصدار 'النشرة' على معلومات يتحمل المستفيد والراعي الذي يظهر اسمه في فقرة الراعي من ملخص معلومات الإصدار مجتمعًا مع المستفيد أو منفردًا كامل المسؤولية عن دقة المعلومات الواردة في نشرو الإصدار هذه، ويؤكد المستفيد والراعي بحسب علمهما واعتقادهما، بعد إجراء جميع الدراسات الممكنة وإلى الحد المعقول، أنه لاتوجد أي وقائع أخرى يمكن أن يؤدي عدم تضمينها في النشرة إلى جعل أي إفادة واردة فيها مضللة. ولا تتحمل هيئة السوق المالية أو شركة التنافسية المالية للاستثمار مجتمعين أو منفردين أي مسؤولية عن محتويات هذه النشرة، ولا تعطيان أي تأكيدات تتعلق بدقتها أو اكتمالها، وتخليان نفسيهما صراحة من أي مسؤولية مهما كانت عن أي خسارة تنتج عما ورد في هذه النشرة أو عن الاعتماد على أي جزء منها.",
    tar7_document_note_2_2:"الأوراق المالية المطروحة صادرة عن منشأة ذات أغراض خاصة مرخص لها من قبل هيئة السوق المالية. وتحتفظ هيئة السوق المالية بسجل للمنشأة ذات الأغراض الخاصة وتنظمها. ولا تصدر هيئة السوق المالية موافقة على، ولاتكون مسؤولة عن، مستندات الطرح ولا الموافقة عليها ، ولا أحكام الأوراق المالية التي تصدرها المنشأة ذات الأغراض الخاصة أو هياكل التمويل التي تستخدمها، أو مخاطر الاستثمار أو العوائد المرتبطة بالأوراق المالية. ولا تنظم هيئة السوق المالية ولا تراقب قيمة أصول المنشأة ذات الأغراض الخاصة أو قدرتها على الوفاء بالتزاماتها، ولا تقدم أي اعتمادات أو توصيات عن الأوراق المالية.",
    tar7_document_note_title_3 :"برنامج إصدار صكوك المرابحة",
    tar7_document_note_3_1_a :"سيمكن برنامج إصدار صكوك المرابحة",
    tar7_document_note_3_1_b :"من طرح مجموعة من إصدارات الصكوك من حين لآخر و ذلك وفقاً للأنظمة والتعليمات ذات الصلة",
    tar7_document_note_3_2 :"تُصدر الصكوك وتسجل إلكترونياً بالقيمة الاسمية المحددة للصك الواحد وفقاً للشروط النهائية الخاصة بالإصدار.",
    tar7_document_note_3_3 :"كما هو موضح في الشروط والأحكام للطرح، فإن الصكوك تمنح لحملتها الحق في الحصول على مبالغ مالية تتولد من أصول الصكوك الخاصة بالإصدار ذي الصلة. ويمثل كل صك حصة ملكية مشاعة في أصول الصكوك، وتُرتب هذه الصكوك لحملتها حقوقاً متساوية فيما بينهم طوال الوقت دون تفضيل.",
    tar7_document_note_3_4 :"ستحدد الشروط النهائية لكل إصدار القيمة الاسمية للصكوك ذات الصلة، وسعر إصدارها، ومعدل العائد وغيرها من المعدومات المتعدقة بالإصدار ذي الصلة.",
    tar7_document_note_3_5 :"أجازت اللجنة الشرعية لشركة التنافسية المالية للاستثمار نموذج عمل الصكوك المصدرة من خلال منصة التنافسية المالية للاستثمار. ولن تكون قابدة للتداول على منصة الصكوك، وذلك بحسب أنظمة هيئة السوق المالية، وأحكام الشريعة الإسلامية المتعلقة بصكوك المرابحة، إلا من خلال آلية التخارج في ضوء الإجراءات الداخلية لشركة التنافسية المالية للاستثمار المتوافقة مع الضوابط المعتمدة من اللجنة الشرعية لشركة التنافسية المالية للاستثمار.",
    tar7_document_note_3_6 :"عند قراءة هذا المستند وتفسيره يجب مراعاة أي تعديل أو إضافة تطرأ عليه ويجب كذلك مراعاة أي معلومات خارجية مشار إليها فيه. وفيما يخص كل إصدار ضمن البرنامج، فيجب مراعاة وقراءة الشروط النهائية المتعلقة بالإصدار ذي الصلة.",
    this_document_prepared:"صدرت مذكرة المعلومات هذه في ",
    On_Date:"الموافق ",

    //Investment agency agreement
    investment_agency_agreement_title:" اﺗﻔﺎﻗﻴﺔ وﻛﺎﻟﺔ ﺑﺎﻻﺳﺘﺜﻤﺎر ",
    inves_agency_intruduction: "اﻟﻤُﻘﺪﻣﺔ",
    inves_agency_ThanksGod:" اﻟﺤﻤﺪ ﻟﻠﻪ، واﻟﺼﻼة واﻟﺴﻼم ﻋﻠﻰ ﻧﺒﻴﻨﺎ ﻣﺤﻤﺪ، وﻋﻠﻰ آﻟﻪ وﺻﺤﺒﻪ، وﺑﻌﺪ ",
    inves_agency_inDay:" إﻧﻪ ﻓﻲ ﻳﻮم ",
    inves_agency_in:" اﻟﻤﻮاﻓﻖ ",
    inves_agency_doingThis: " أُﺑﺮﻣﺖ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﺑﻴﻦ ﻛﻞ ﻣﻦ: ",
    inves_agency_Competitiveness_info: " ﺷﺮﻛﺔ التنافسية اﻟﻤﺎﻟﻴﺔ وﻫﻲ ﺷﺮﻛﺔ ﻗﺎﺋﻤﺔ ﺑﻤﻮﺟﺐ ﻗﻮاﻧﻴﻦ اﻟﻤﻤﻠﻜﺔ اﻟﻌﺮﺑﻴﺔ اﻟﺴﻌﻮدﻳﺔ، وﻋﻨﻮان ﻣﻘﺮﻫﺎ اﻟﺮﺋﻴﺴﻲ: اﻟﻤﻤﻠﻜــﺔ اﻟﻌﺮﺑﻴــﺔ اﻟﺴــﻌﻮدﻳﺔ، ﻣﺪﻳﻨــﺔ اﻟﺮﻳــﺎض ﻃﺮﻳــﻖ الأمير عبدالعزيز بن مساعد بن جلوي ﺣــﻲ المربع، ص. ب. 12626، وﻫــﻲ ﺷﺮﻛــﺔ ﻣﺼـﺮﺣﺔ ﻣـﻦ ﻗﺒـﻞ ﻫﻴﺌـﺔ اﻟﺴـﻮق اﻟﻤﺎﻟﻴـﺔ ﻹﻧﺸـﺎء ﻣﻨﺼـﺔ ﻃـﺮح أدوات اﻟـﺪﻳﻦ واﻻﺳـﺘﺜﻤﺎر ﻓﻴﻬـﺎ ﻓـﻲ ﻣﺨﺘـﺒﺮ اﻟﺘﻘﻨﻴـﺔ اﻟﻤﺎﻟﻴﺔ. وﻳُﺸﺎر إﻟﻴﻬﺎ ﻓﻲ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﺑـــــــــ)اﻟﺸﺮﻛﺔ. ",
    inves_agency_Mr: " السيد ",
    inves_agency_Saudi: " (سعودي) ",
    inves_agency_national_id : " رقم الهوية ",
    inves_agency_in_date:" بتاريخ ",
    inves_agency_invester_address:" وعنوانه الرئيسي :المملكة العربية السعودية - ",
    inves_agency_indicate_data:" وﻳُﺸﺎر إﻟﻴﻪ ﻓﻲ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﺑــأي من المصطلحات التالية:(اﻟﻄﺮف اﻟﺜﺎﻧﻲ-اﻟﻌﻤﻴﻞ، اﻟﻤﻮﻛﱢﻞ-اﻟﻤﺴﺘﺜﻤﺮ). وﻳُﺸﺎر إﻟﻰ اﻟﻄﺮف اﻷول واﻟﻄﺮف اﻟﺜﺎﻧﻲ ﻣﺠﺘﻤﻌﻴﻦ ﻓﻴﻤﺎ ﺑﻌﺪ ﺑـــــــ(اﻟﻄﺮﻓﺎن-اﻟﻄﺮﻓﻴﻦ)  ",
    inves_agency_definition_appendex:" ملحق التعريفات ",
    inves_agency_definition_appendex_word :" ﻳﻘﺼﺪ ﺑﺎﻟﻌﺒﺎرات اﻟﺘﺎﻟﻴﺔ أﻳﻨﻤﺎ وردت ﻓﻲ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ",
    inves_agency_defin_appen_1:" اﺗﻔﺎﻗﻴﺔ اﻟﻮﻛﺎﻟﺔ ﺑﺎﻻﺳﺘﺜﻤﺎر : ﻋﻼﻗﺔ ﺗﻌﺎﻗﺪﻳﺔ ﺑﻴﻦ ﻣﻮﻛﱢﻞ ووﻛﻴﻞ ﻳﻘﻮم اﻟﻤﻮﻛﱢﻞ ﺑﻤﻮﺟﺒﻬﺎ ﺑﺘﻌﻴﻴﻦ اﻟﻮﻛﻴﻞ ﻟﻠﻘﻴﺎم ﺑﺄﻋﻤﺎل ﻣﺤﺪدة ﻧﻴﺎﺑﺔ ﻋﻨﻪ، وﻓﻘٍﺎ ﻟﻤﺎ ﺟﺎء ﻓﻲ اﻟﺘﻤﻬﻴﺪ واﻟﻤﺎدة اﻟﺜﺎﻟﺜﺔ ﻣﻦ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ، ﻓﻲ ﻣﻘﺎﺑﻞ أﺟﺮة ﻣﺤﺪدة ﻳﺪﻓﻌﻬﺎ اﻟﻤﻮﻛﻞ ﻟﻠﻮﻛﻴﻞ ",
    inves_agency_defin_appen_2:" أﺟﺮة اﻟﻮﻛﻴﻞ :  ﻧﺴﺒﺔ ﻣﺌﻮﻳﺔ ﻣﻦ ﺻﺎﻓﻲ اﻟﺮﺑﺢ اﻟﻔﻌﻠﻲ ﻟﻺﺻﺪار.، وذﻟﻚ ﻣﻘﺎﺑﻞ ﻗﻴﺎم اﻟﻮﻛﻴﻞ ﺑﺈدارة اﻹﺻﺪار ﻋﻠﻰ ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك ",
    inves_agency_defin_appen_3:" إﺟﻤـﺎﻟﻲ ﺣﺼـﻴﻠﺔ اﻻﻛﺘﺘـﺎب: ﻣﺠﻤـﻮع اﻟﻤﺒـﺎﻟﻎ اﻟﻤﺴـﺘﻠﻤﺔ ﻣـﻦ اﻟﻤﺴـﺘﺜﻤﺮﻳﻦ ﻓـﻲ اﻟﻤﻨﺼـﺔ، ﻟﻼﺳـﺘﺜﻤﺎر ﻓـﻲ إﺻـﺪار ﺻﻜﻮك اﻟﻤﺮاﺑﺤﺔ ",
    inves_agency_defin_appen_4:" إﺻـﺪار اﻟﺼـﻜﻮك: اﺳـﺘﺜﻤﺎر ﻣُﻌﻠـﻦ ﻋﻨـﻪ ﻣـﻦ ﻗﺒـﻞ اﻟﺸﺮﻛـﺔ، ﻣـﻦ ﺧﻼل ﻣﻨﺼـﺔ إﺻـﺪار اﻟﺼـﻜﻮك، وﻳﻘـﻮم إﺻـﺪار اﻟﺼﻜﻮك ﻋﻠﻰ أﺳﺎس ﻋﻤﻠﻴﺔ ﻣﺮاﺑﺤﺔ ﻣﺘﻮاﻓﻘﺔ ﻣﻊ أﺣﻜﺎم اﻟﺸﺮﻋﻴﺔ اﻹﺳﻼﻣﻴﺔ ",
    inves_agency_defin_appen_5:" اﻟﺘﺎرﻳﺦ اﻟﻔﻌﻠﻲ ﻟﻠﺴﺪاد: ﻫﻮ اﻟﺘﺎرﻳﺦ اﻟﺬي ﻳﺘﻌﺪى ﺗﺎرﻳﺦ اﻻﺳﺘﺤﻘﺎق اﻟﻤﻌﻠﻦ ﻋﻨﻪ ﻓﻲ إﺻﺪار اﻟﺼﻜﻮك",
    inves_agency_defin_appen_6:" اﻟﺴﺪاد اﻟﻤﺒﻜﺮ: ﻫﻲ ﻋﻤﻠﻴﺔ ﺗﺴﺪﻳﺪ ﻛﺎﻣﻞ اﻟﻤﺒﻠﻎ ﻣﻦ ﻗﺒﻞ اﻟﻤﺴﺘﻔﻴﺪ ﻗﺒﻞ ﺗﺎرﻳﺦ اﻻﺳﺘﺤﻘﺎق. ",
    inves_agency_defin_appen_7:" اﻟﻌﺎﺋـﺪ اﻟﻤﺴـﺘﺤﻖ: اﻟﻌﺎﺋـﺪ اﻟﻤﺴـﺘﺤﻖ ﻟﻠﻤﻮﻛـﻞ ﺑﺤﺴـﺐ ﺣﺼـﺘﻪ ﻓـﻲ إﺟﻤـﺎﻟﻲ رﺑـﺢ اﻟﺘﻤﻮﻳـﻞ اﻟﻨـﺎﺗﺞ ﻋـﻦ اﻟﺼـﻔﻘﺔ اﻻﺳﺘﺜﻤﺎرﻳﺔ ﺑﺎﻟﻨﻈﺮ إﻟﻰ إﺟﻤﺎﻟﻲ ﺣﺼﻴﻠﺔ اﻻﻛﺘﺘﺎب ",
    inves_agency_defin_appen_8:" اﻟﻤﺴﺘﺜﻤﺮون: اﻷﺷﺨﺎص اﻟﺮاﻏﺒﻮن ﺑﺎﻻﺳﺘﺜﻤﺎر ﻓﻲ اﻟﺼﻜﻮك اﻟﻤﻄﺮوﺣﺔ ﻣﻦ ﺧﻼل ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك ",
    inves_agency_defin_appen_9:" اﻟﻤﺴﺘﻔﻴﺪ: اﻟﻌﻤﻴﻞ اﻟﻤﺘﻤﻮل ﻣﻦ ﺣﺼﻴﻠﺔ اﻻﻛﺘﺘﺎب ﻓﻲ اﻟﺼﻜﻮك ﺑﻤﻮﺟﺐ ﻋﻘﺪ اﻟﻤﺮاﺑﺤﺔ.",
    inves_agency_defin_appen_10:" ﺗﺎرﻳﺦ اﻻﺳﺘﺤﻘﺎق: ﺗﺎرﻳﺦ ﺳﺪاد ﺛﻤﻦ اﻟﺒﻴﻊ اﻟﻤﺆﺟﻞ ﻓﻲ ﺣﺴﺎﺑﺎت وﻛﻴﻞ اﻟﺪﻓﻊ وﻓﻘًﺎ ﻟﻤﺎ ﻫﻮ ﻣﻌﻠﻦ ﻓﻲ ﻧﺸﺮة اﻹﺻﺪار اﻟﻤﺘﺎﺣﺔ ﻋﻠﻰ اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ ﻟﻠﻤﻨﺼﺔ. ",
    inves_agency_defin_appen_11: " ﺗﺎرﻳﺦ اﻟﺘﻮزﻳﻊ اﻟﺪوري: ﻫﻮ ﻋﻤﻠﻴﺔ إﻳﺪاع اﻟﻤﺒﺎﻟﻎ اﻟﻤﺴﺘﺤﻘﺔ ﻓﻲ ﺣﺴﺎﺑﺎت اﻟﻤﺴﺘﺜﻤﺮﻳﻦ ﺧﻼل(5) ﺧﻤﺴﺔ أﻳﺎم ﻋﻤﻞ ﻣﻦ ﺗﺎرﻳﺦ إﻳﺪاع أي ﻗﺴﻂ ﻣﺤﺼﱠﻞ ﻣﻦ ﺛﻤﻦ اﻟﺒﻴﻊ اﻟﻤﺆﺟﻞ ﻣﻦ ﻗﺒﻞ اﻟﻤﺴﺘﻔﻴﺪ ﻓﻲ ﺣﺴﺎﺑﺎت وﻛﻴﻞ اﻟﺪﻓﻊ",
    inves_agency_defin_appen_12:" ﺣﺴﺎب اﻟﻤﺴﺘﺜﻤﺮ اﻻﻓﺘﺮاﺿﻲ: ﺣﺴﺎب ﻣﺎﻟﻲ إﻟﻜﺘﺮوﻧﻲ، ﻳﻘﺮ اﻟﻤﺴﺘﺨﺪم ﺑﻤﻮﺟﺒﻪ ﺑﺄﻧﻪ ﻟﻴﺲ ﺣﺴﺎﺑًﺎ ﻣﺼﺮﻓﻴًﺎ وﻻ ﻳﻮﻓﺮ اﻟﺨﺪﻣﺎت اﻟﻤﺼﺮﻓﻴﺔ ﻏﻴﺮ اﻟﺘﻲ ﺗﻨﺺ ﻋﻠﻴﻬﺎ اﺗﻔﺎﻗﻴﺔ ﻓﺘﺢ اﻟﺤﺴﺎب ﻋﻠﻰ اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ ﻟﻠﻤﻨﺼﺔ ",
    inves_agency_defin_appen_13:" ﺻﺎﻓﻲ اﻟﺮﺑﺢ اﻟﻔﻌﻠﻲ: ﻣﻘﺪار اﻟﺮﺑﺢ اﻟﺤﻘﻴﻘﻲ اﻟﺬي ﺗﻢ ﺗﺤﻘﻴﻘﻪ ﻣﻦ اﻟﺼﻜﻮك ",
    inves_agency_defin_appen_14:" ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر: اﻟﻤﺒﻠﻎ اﻟﺬي ﻳﻮد اﻟﻄﺮف اﻟﺜﺎﻧﻲ اﺳﺘﺜﻤﺎره وﻓﻘًﺎ ﻟﺸﺮوط وأﺣﻜﺎم ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﻓﻲ ﺻﻜﻮك إﺳﻼﻣﻴﺔ ﺧﻼل اﻟﻤﻨﺼﺔ",
    inves_agency_defin_appen_15:" ﻣﻌﺪﱠل اﻟﺮﺑﺢ اﻟﻤﺘﻮﻗﻊ: ﻣﻌﺪل اﻟﺮﺑﺢ اﻟﺬي ﻳﺘﻮﻗﻊ اﻟﻤﺴﺘﺜﻤﺮ اﺳﺘﻼﻣﻪ ﻓﻲ ﺗﺎرﻳﺦ اﻟﺘﻮزﻳﻊ اﻟﺪوري، واﻟﻤﻌﻠﻦ ﻣﻦ ﻗﺒﻞ ﻣﺴﺆول اﻟﻤﻨﺼﺔ ﻋﻠﻰ ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك ",
    inves_agency_defin_appen_16:" ﻧﺸﺮة اﻹﺻﺪار: ﻣﻠﻒ اﻟﻤﻌﻠﻮﻣﺎت اﻟﺮﺋﻴﺴﺔ ﻟﻜﻞ ﻓﺮﺻﺔ اﺳﺘﺜﻤﺎرﻳﺔ ﻣﻌﻠﻦ ﻋﻨﻬﺎ ﻓﻲ اﻟﻤﻮﻗﻊ اﻻﻟﻜﺘﺮوﻧﻲ ",
    inves_agency_defin_appen_17:" ﺻﻜﻮك اﻟﻤﺮاﺑﺤﺔ: ﻫﻲ وﺛﺎﺋﻖ ﻣﺘﺴﺎوﻳﺔ اﻟﻘﻴﻤﺔ ﻳﺘﻢ إﺻﺪارﻫﺎ ﻟﺘﻤﻮﻳﻞ ﺷﺮاء ﺳﻠﻌﺔ اﻟﻤﺮاﺑﺤﺔ وﺑﻴﻌﻬﺎ ﻟﻠﻤﺴﺘﻔﻴﺪ، وﻳﻤﺜﻞ اﻟﺼﻚ ﺣﺼﺔ ﺷﺎﺋﻌﺔ ﻓﻲ ﻣﻠﻜﻴﺔ ﺳﻠﻌﺔ اﻟﻤﺮاﺑﺤﺔ ﺑﻌﺪ ﺷﺮاﺋﻬﺎ وﻗﺒﻞ ﺑﻴﻌﻬﺎ وﺗﺴﻠﻴﻤﻬﺎ ﻟﻤﺸﺘﺮﻳﻬﺎ وﻓﻲ ﺛﻤﻨﻬﺎ ﺑﻌﺪ ﺑﻴﻌﻬﺎ ﻟﻠﻤﺴﺘﻔﻴﺪ، وﻋﺎﺋﺪ ﻫﺬه اﻟﺼﻜﻮك ﻫﻮ اﻟﻔﺮق ﺑﻴﻦ ﺛﻤﻦ ﺷﺮاء ﺳﻠﻌﺔ اﻟﻤﺮاﺑﺤﺔ وﺛﻤﻦ ﺑﻴﻌﻬﺎ ﻟﻠﻤﺴﺘﻔﻴﺪ ",
    inves_agency_defin_appen_18:" اﻟﻘﻴﻤﺔ اﻻﺳﻤﻴﺔ ﻟﻠﺼﻚ: ﺛﻤﻦ ﺑﻴﻊ اﻟﺼﻚ ﻟﻠﻤﺴﺘﺜﻤﺮ واﻟﻤﻌﻠﻦ ﻋﻨﻪ ﻓﻲ ﻧﺸﺮة اﻹﺻﺪار ",
    inves_agency_defin_appen_19:" ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك (اﻟﻤﻨﺼﺔ:( اﻟﻤﻨﺼﺔ اﻹﻟﻜﺘﺮوﻧﻴﺔ ﻟﺸﺮﻛﺔ التنافسية اﻟﻤﺎﻟﻴﺔ اﻟﻤﺘﺎﺣﺔ ﻟﻼﺳﺘﻌﻤﺎل ﻣﻦ ﺧﻼل اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ واﻟﺘﻲ ﺗﻘﺪم ﻣﻦ ﺧﻼﻟﻬﺎ ﺷﺮﻛﺔ التنافسية اﻟﻤﺎﻟﻴﺔ ﺧﺪﻣﺎت إﺻﺪار اﻟﺼﻜﻮك ",
    inves_agency_defin_appen_20:" وﻛﻴﻞ ﺣﻤﻠﺔ اﻟﺼﻜﻮك/اﻟﻮﻛﻴﻞ: ﺷﺮﻛﺔ التنافسية اﻟﻤﺎﻟﻴﺔ ",

    inves_agency_preface_title:" اﻟﺘﻤﻬﻴﺪ ",
    inves_agency_preface_1 :" ﺣﻴﺚ إن اﻟﻄﺮف اﻷول ﺷﺮﻛﺔ ﻣﺼﺮﺣﺔ ﻣﻦ ﻗﺒﻞ ﻫﻴﺌﺔ اﻟﺴﻮق اﻟﻤﺎﻟﻴﺔ ﻹﻧﺸﺎء ﻣﻨﺼﺔ ﻃﺮح أدوات اﻟﺪﻳﻦ واﻻﺳﺘﺜﻤﺎر ﻓﻴﻬﺎ ﻓﻲ ﻣﺨﺘﺒﺮ اﻟﺘﻘﻨﻴﺔ اﻟﻤﺎﻟﻴﺔ، وﻣﺘﻮاﻓﻘﺔ ﻣﻊ اﻷﻧﻈﻤﺔ اﻟﻤﻌﻤﻮل ﺑﻬﺎ ﻓﻲ اﻟﻤﻤﻠﻜﺔ اﻟﻌﺮﺑﻴﺔ اﻟﺴﻌﻮدﻳﺔ. ",
    inves_agency_preface_2 :" وﺣﻴﺚ ﻳﺮﻏﺐ اﻟﻄﺮف اﻟﺜﺎﻧﻲ ﻓﻲ اﺳﺘﺜﻤﺎر أﻣﻮاﻟﻪ ﻣﻦ ﺧﻼل ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك اﻟﺘﻲ ﻳﺪﻳﺮﻫﺎ اﻟﻄﺮف اﻷول وﻓﻖ ﺷﺮوط وأﺣﻜﺎم ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ",
    inves_agency_preface_3 :" ﻟﺬا ﻓﻘﺪ اﺗﻔﻖ اﻟﻄﺮﻓﺎن وﻫﻤﺎ ﺑﻜﺎﻣﻞ أﻫﻠﻴﺘﻬﻤﺎ اﻟﻤﻌﺘﺒﺮة ﺷﺮﻋًﺎ وﻧﻈﺎﻣًﺎ ﻋﻠﻰ اﻟﺪﺧﻮل ﻓﻲ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ اﻟﺘﻲ ﺗﺤﺪد ﺷﺮوط وأﺣﻜﺎم اﺗﻔﺎﻗﻴﺔ اﻟﻮﻛﺎﻟﺔ ﺑﺎﻻﺳﺘﺜﻤﺎر، وذﻟﻚ ﻋﻠﻰ اﻟﻨﺤﻮ اﻵﺗﻲ ",
    inves_agency_article1 :" اﻟﻤﺎدة اﻷوﻟﻰ: ﺣﺠﻴﺔ اﻟﻤﻘﺪﻣﺔ واﻟﺘﻤﻬﻴﺪ واﻟﻤﻼﺣﻖ ",
    inves_agency_article1_1 :" ﺗُﻌﺪ اﻟﻤﻘﺪﻣﺔ واﻟﺘﻤﻬﻴﺪ أﻋﻼه ﺟﺰءًا ﻻ ﻳﺘﺠﺰأ ﻣﻦ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ وﻣﺘﻤﻤﺔً ﻟﻬﺎ ",
    inves_agency_article2 :" اﻟﻤﺎدة اﻟﺜﺎﻧﻴﺔ: ﻣﺤﻞ اﻻﺗﻔﺎﻗﻴﺔ ",
    inves_agency_article2_1 :" وﻛﱠﻞ اﻟﻤﺴﺘﺜﻤﺮُ ﺑﻤﻮﺟﺐ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ اﻟﺸﺮﻛﺔَ ﺑﺎﺳﺘﺜﻤﺎر اﻟﻘﻴﻤﺔ اﻻﺳﻤﻴﺔﻟﻠﺼﻚ/اﻟﺼﻜﻮك اﻟﻤﻤﻠﻮﻛﺔ ﻟﻠﻤﺴﺘﺜﻤﺮ ﻓﻲ ﺷﺮاء ﺳﻠﻊ ﻗﺎﺑﻠﺔ ﻟﻠﺘﺴﻴﻴﻞوﺑﻴﻌﻬﺎ ﻣﺮاﺑﺤﺔ ﻟﻠﻤﺴﺘﻔﻴﺪ ﺑﺎﺳﻢ اﻟﺸﺮﻛﺔ وﻟﺼﺎﻟﺢ اﻟﻤﺴﺘﺜﻤﺮ وﻧﻴﺎﺑﺔً ﻋﻨﻪ، وﺑﻤﺎ ﻻ ﻳﺘﻌــﺎرض ﻣــﻊ أﺣﻜــﺎم وﻣﺒــﺎدئ اﻟﺸﺮﻳﻌــﺔ اﻹﺳﻼﻣﻴــﺔ، ﻛﻤــﺎ ﻳﺨــﻮل اﻟﻤﺴــﺘﺜﻤﺮُ اﻟﺸﺮﻛــﺔَ ﺑﻤﻤﺎرﺳــﺔ ﺟﻤﻴــﻊ اﻟﺤﻘــﻮق واﻟﺴﻠﻄﺎت واﻟﺼﻼﺣﻴﺎت اﻷﺧﺮى ذات اﻟﻌﻼﻗﺔ، واﻟﺘﻲ ﻣﻦ ﺑﻴﻨﻬﺎ ﺗﺤﺼﻴﻞ ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎرﻣﻦ اﻟﻤﺴﺘﻔﻴﺪ، ورﻓﻊ اﻟﺪﻋﺎوى ﻧﻴﺎﺑﺔً ﻋﻨﻪ، وذﻟﻚ ﻟﻴﺘﻤﻜﻦ ﻣﻦ اﻟﻮﻓﺎء ﺑﺎﻟﺘﺰاﻣﺎﺗﻪ اﻟﻨﺎﺷﺌﺔ ﺑﻤﻮﺟﺐ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ، وﻗﺒﻞ اﻟﻄﺮف اﻷول ذﻟﻚ ",
    inves_agency_article3 :" اﻟﻤﺎدة اﻟﺜﺎﻟﺜﺔ: ﻃﺒﻴﻌﺔ اﻟﻨﺸﺎط اﻻﺳﺘﺜﻤﺎري وإدارﺗﻪ: ",
    inves_agency_article3_1 :" اﺗﻔـﻖ اﻟﻄﺮﻓـﺎن ﻋﻠـﻰ أن ﻳُﻘﻴﱠـﺪ ﻧﺸـﺎط اﻻﺳـﺘﺜﻤﺎر ﻓـﻲ ﻋﻤﻠﻴـﺎت ﺗﻤﻮﻳـﻞ ﻣﺮاﺑﺤـﺔ ﺑﺎﻵﺟـﻞ ﻣـﻊ اﻟﻤﺴـﺘﻔﻴﺪ ﺑﺎﺳـﺘﺨﺪام ﺣﺼﻴﻠﺔ اﻻﻛﺘﺘﺎب ﻓﻲ اﻟﺼﻜﻮك، وذﻟﻚ ﻣﻦ ﺧﻼل ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك، وذﻟﻚ ﻓﻲ أي إﺻﺪار ﻣﺘﺎح ﻋﻠﻰ اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ ﻟﻠﺸﺮﻛﺔ ﻳﺤﺪده اﻟﻌﻤﻴﻞ. وﻳﻜﻮن اﻟﺘﻤﻮﻳﻞ ﺑﺎﻵﺟﻞ ﻣﻦ ﺧﻼل ﻗﻴﺎم اﻟﺸﺮﻛﺔ ﺑﺸﺮاء ﺳﻠﻊ وﺑﻴﻌﻬﺎ ﺑﺎﻵﺟﻞ ﻣﺮاﺑﺤـﺔً ﻟﻠﻤﺴـﺘﻔﻴﺪ، وﻻ ﻳﺤـﻖ ﻟﻠﺸﺮﻛـﺔ اﻟﺘﺼـﺮف ﺑﻤﺒﻠـﻎ اﻻﺳـﺘﺜﻤﺎر ﻓـﻲ ﻏﻴـﺮ اﻟﻨﺸـﺎط اﻟﻤﻨﺼـﻮص ﻋﻠﻴـﻪ ﻓـﻲ ﻫـﺬه اﻻﺗﻔﺎﻗﻴﺔ ",
    inves_agency_article3_2 :" ﺗﺘﻌﻬﺪ اﻟﺸﺮﻛﺔ ﻟﻠﻤﺴﺘﺜﻤﺮ ﺑﻤﻮﺟﺐ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ أﻧﻬﺎ ﺳﺘﺪﻳﺮ ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر ﺑﺎﻟﻜﻔﺎءة واﻟﻌﻨﺎﻳﺔ اﻟﻼزﻣﺔ، وذﻟﻚ وﻓﻘًﺎ ﻟﻠﺴﻴﺎﺳﺎت اﻻﺋﺘﻤﺎﻧﻴﺔاﻟﻤﻌﺘﻤﺪة ﻟﺪى اﻟﺸﺮﻛﺔ ",
    inves_agency_article3_3 :" يفويض الموكل  اﻠﺸﺮﻛﺔ ﻓﻲ اﺗﺨﺎذ اﻹﺟﺮاءات اﻟﻼزﻣﺔ ﻟﻼﺳﺘﺜﻤﺎر  بحرية مطلقة ودون الرجوع للموكل ، ﺑﻤﺎ ﻓﻲ ذﻟﻚ: ﺗﻮﻗﻴﻊ اﻟﻌﻘــﻮد، واﻟﺘﻔــﺎوض ﻣــﻊ اﻵﺧﺮﻳــﻦ، ودﻓــﻊ ﻗﻴﻤــﺔ اﻟﻌﻤﻠﻴــﺎت واﻟﻤﺼــﺎرﻳﻒ اﻟﻼزﻣــﺔ ﻟﺘﻨﻔﻴﺬﻫــﺎ، وﺗﺤﺼــﻴﻞ اﻟﻤﺒــﺎﻟﻎ ودﻓﻌﻬﺎ، وأﻳﺔ إﺟﺮاءات أﺧﺮى ﻳﺘﻄﻠﺒﻬﺎ اﺳﺘﺜﻤﺎر أﻣﻮال اﻟﻤﺴﺘﺜﻤﺮ، وﻟﻠﺸﺮﻛﺔ اﻟﺤﻖ ﻓﻲ إﺳﻨﺎد وﺗﻔﻮﻳﺾ ﺑﻌﺾ أو ﻛﻞ اﻟﺼﻼﺣﻴﺎت إﻟﻰ ﻃﺮف آﺧﺮ إذا دﻋﺖ اﻟﺤﺎﺟﺔ ﻟﺬﻟﻚ، ووﻓﻘًﺎ ﻟﺘﻘﺪﻳﺮﻫﺎ اﻟﻤﻄﻠﻖ ",
    inves_agency_article3_4 :" اﺗﻔﻖ اﻟﻄﺮﻓﺎن ﺑﺄﻧﱠ وكالة الطرف الاول مطلقة فيما اوكل فيه و ﻟﻴﺲ ﻟﻠﻤﻮﻛﱢﻞ اﻟﺤﻖ ﻓﻲ ﻣﺮاﺟﻌﺔ اﻟﻮﻛﻴﻞ ﻹﻟﺰاﻣﻪ ﺑﺒﻌﺾ اﻷﻋﻤﺎل، أو اﺷﺘﺮاط أﺧﺬ ﻣﻮاﻓﻘﺔ اﻟﻤﻮﻛﻞ ﻋﻠﻰ ﺑﻌﺾ اﻟﺘﺼﺮﻓﺎت ﺑﻌﺪ اﻟﺘﻮﻗﻴﻊ ﻋﻠﻰ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ، ﻛﻤﺎ ﻻ ﻳﺤﻖ ﻟﻠﻤﻮﻛﱢﻞ اﻟﺘﻮاﺻﻞ ﻣﻊ اﻟﻤﺴﺘﻔﻴﺪ ﻹﻟﺰاﻣﻪ ﺑﺎﻟﺪﻓﻊ أو رﻓﻊ دﻋﻮى ﻗﻀﺎﺋﻴﺔ أو أي إﺟﺮاءات أﺧﺮى دون اﻟﺮﺟﻮع ﻟﻠﻮﻛﻴﻞ ",
    inves_agency_article3_5 :" اﺗﻔﻖ اﻟﻄﺮﻓﺎن ﺑﺄنﱠ ﻟﻠﻮﻛﻴﻞ اﻟﺤﻖ اﻟﻤﻄﻠﻖ ﻓﻲ اﻟﺘﻮاﺻﻞ ﻣﻊ اﻟﻤﺴﺘﻔﻴﺪ واﻟﻤﺴﺘﺜﻤﺮﻳﻦ اﻵﺧﺮﻳﻦ اﻟﻤﺸﺎرﻛﻴﻦ ﻓﻲ إﺻﺪار اﻟﺼﻜﻮك، وﻟﻴﺲ ﻟﻠﻤﻮﻛﱢﻞ اﻟﺤﻖ ﻓﻲ ﻣﺮاﺟﻌﺔ اﻟﻤﺴﺘﺜﻤﺮﻳﻦ اﻵﺧﺮﻳﻦ أو اﻟﻤﺴﺘﻔﻴﺪ ",
    inves_agency_article4 :" اﻟﻤﺎدة اﻟﺮاﺑﻌﺔ: ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر ",
    inves_agency_article4_1 :" ﻋﻠـﻰ اﻟﻤﺴـﺘﺜﻤﺮ إﻳـﺪاع رأس اﻟﻤـﺎل ﻓـﻲ ﺣﺴـﺎﺑﻪ اﻻﺳـﺘﺜﻤﺎري ﺣﺴـﺎب اﻟﻤﺴـﺘﺜﻤﺮ اﻻﻓﺘﺮاﺿـﻲ اﻟﻤﺴـﺠﻞ ﻓـﻲ ﺻﻔﺤﺘﻪ اﻟﺸﺨﺼﻴﺔ ﻋﻠﻰ اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ ﻟﻠﻤﻨﺼﺔ ",
    inves_agency_article4_2 :" تلتزم شركة التنافسية المالية بأحكام الفصلين الثاني والثالث من الباب السابع من لائحة مؤسسات السوق المالية المتعلقة بأصول وأموال العملاء ",
    inves_agency_article5 :" اﻟﻤﺎدة اﻟﺨﺎﻣﺴﺔ: ﻣﺪة اﻻﺳﺘﺜﻤﺎر ",
    inves_agency_article5_1 :" ﻳﺠﺐ أﻻ ﻳﻜﻮن إﻧﻬﺎء اﻻﺗﻔﺎﻗﻴﺔ أو اﻧﺘﻬﺎﺋﻬﺎ ﻣﺆﺛﱢﺮًا ﻋﻠﻰ ﺣﻘﻮق واﻟﺘﺰاﻣﺎت أيﱟ ﻣﻦ اﻟﻄﺮﻓﻴﻦ، ﻓﻴﻤﺎ ﻳﺘﻌﻠﻖ ﺑﺄي إﺻﺪار ﺻـﻜﻮك ﻗـﺎﺋﻢ وﻣﺴـﺘﺤﻖ ﻗﺒـﻞ اﻧﺘﻬـﺎء ﻫـﺬه اﻻﺗﻔﺎﻗﻴـﺔ، ﺣﻴـﺚ ﺳـﺘﻈﻞ ﺷـﺮوط وأﺣﻜـﺎم ﻫـﺬه اﻻﺗﻔﺎﻗﻴـﺔ ﺳﺎرﻳـﺔ ﺣﺘـﻰ اﻻﻧﺘﻬﺎء ﻣﻦ ﺗﺴﻮﻳﺔ اﻟﺼﻜﻮك اﻟﻘﺎﺋﻤﺔ ",
    inves_agency_article6 :" اﻟﻤﺎدة اﻟﺴﺎدﺳﺔ: أﺟﺮة اﻟﺸﺮﻛﺔ ",
    inves_agency_article6_1 :" اﺗﻔﻖ اﻟﻄﺮﻓﺎن ﻋﻠﻰ أنﱠ اﻟﺸﺮﻛﺔ ﺗﺴﺘﺤﻖ رﺳﻮﻣًﺎ ﻣﻘﺎﺑﻞ ﻋﻤﻠﻬﺎ ﻧﻴﺎﺑﺔً ﻋﻦ اﻟﻤﺴﺘﺜﻤﺮ ﺗﻘﺪﱠر ﺑﻨﺴﺒﺔ ﻣﺌﻮﻳﺔ ﻣﻦ ﺻﺎﻓﻲ اﻟﺮﺑﺢ اﻟﻔﻌﻠﻲ، ﺗُﺤﺪدﻫﺎ اﻟﺸﺮﻛﺔ ﻓﻲ اﻟﻨﺸﺮة اﻟﺨﺎﺻﺔ ﺑﻜﻞ إﺻﺪار ",
    inves_agency_article7 :" اﻟﻤﺎدة اﻟﺴﺎﺑﻌﺔ: ﻋﻮاﺋﺪاﻟﺼﻜﻮك ",
    inves_agency_article7_1 :" ﻳﺘﻌﻬﺪ اﻟﻮﻛﻴﻞ ﺑﻌﺪ اﺳﺘﻼم ﻣﺒﺎﻟﻎ اﻟﺘﻮزﻳﻌﺎت اﻟﺪورﻳﺔ اﻟﻤﺤﺪدة ﻓﻲ ﺟﺪول اﻟﺴﺪاد اﻟﺨﺎص ﺑﺎﻹﺻﺪار وﻓﻘًﺎ ﻟﻤﺎ ﻫﻮ ﻣﻌﻠﻦ ﻋﻨﻪ ﻓﻲ ﻧﺸﺮة اﻹﺻﺪار اﻟﺨﺎﺻﺔ ﺑﺎﻹﺻﺪار. وذﻟﻚ ﻣﻦ اﻟﻤﺴﺘﻔﻴﺪ ﺑﺈﻳﺪاع اﻟﻤﺒﻠﻎ ﻓﻲ ﺣﺴﺎب اﻟﻤﺴﺘﺜﻤﺮ ﺑﻌﺪ ﺧﺼﻢ أﺟﺮة اﻟﻮﻛﻴﻞ أو أي ﻣﺼﺎرﻳﻒ ﺗﺘﻌﻠﻖ ﺑﺎﻟﺘﺤﺼﻴﻞ واﻟﻤﺤﺎﻣﺎة ",
    inves_agency_article7_2 :" ﻓﻲ ﺣﺎل ﺣﺼﻮل ﺧﺴﺎرة ﻓﻲ إﺻﺪار اﻟﺼﻜﻮك ﻓﻴﺘﻌﻬﺪ اﻟﻮﻛﻴﻞ ﺑﺈﻋﺎدة ﻣﺎ ﺗﺒﻘﻰ ﻣﻦ ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر إﻟﻰ اﻟﻤﻮﻛﱢﻞ، وذﻟﻚ ﻣﻊ ﻣﺮاﻋﺎة ﻣﺎ ورد ﻓﻲ اﻟﻔﻘﺮة اﻟﺜﺎﻧﻴﺔ ﻟﻠﻤﺎدة اﻟﺘﺎﺳﻌﺔ ﺑﻌﺪ ﺧﺼﻢ ﻛﺎﻓﺔ ﻣﺼﺎرﻳﻒ اﻟﺘﺤﺼﻴﻞ واﻟﻤﺤﺎﻣﺎة ",
    inves_agency_article7_3 :" ﻓــﻲ ﺣــﺎل اﻟﺴــﺪاد اﻟﻤﺒﻜــﺮ ﻓﻴﺘــﻢ إﻋــﺎدة اﺣﺘﺴــﺎب اﻟﻌﺎﺋــﺪ اﻟﻤﺴــﺘﺤﻖ ﻟﻠﻤﺴــﺘﺜﻤﺮ ﺑﻨــﺎءً ﻋﻠــﻰ اﻟﺘــﺎرﻳﺦ اﻟﻔﻌﻠــﻲ ﻟﻠﺴﺪاد ",
    inves_agency_article8 :" اﻟﻤﺎدة اﻟﺜﺎﻣﻨﺔ: ﻧﻄﺎق اﻟﻤﺴﺆوﻟﻴﺔ: ",
    inves_agency_article8_1 :" ﻳﻘﺮ اﻟﻤﺴﺘﺜﻤﺮ وﻳﻌﻲ ﻛﺎﻣﻞ اﻟﻤﺨﺎﻃﺮ اﻟﻨﺎﺷﺌﺔ ﻋﻦ ﻋﻤﻠﻴﺎت اﻟﺘﻤﻮﻳﻞ ﻣﻦ ﺧﻼل اﻟﻤﻨﺼﺔ، واﺣﺘﻤﺎل ﺧﺴﺎرة ﻛﺎﻣﻞ ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر أو ﺟﺰء ﻣﻨﻪ ",
    inves_agency_article8_2 :" ﻳﻘﺮ اﻟﻤﻮﻛﱢﻞ ﺑﺄن اﻟﻮﻛﻴﻞ أﻣﻴﻦ ﻋﻠﻰ ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر وإدارﺗﻪ، ﻻ ﻳﻀﻤﻨﻪ ﻓﻲ ذﻣﺘﻪ ﻣﺎ ﻟﻢ ﻳﺘﻌﺪ أو ﻳﻔﺮط أو ﻳﺨﺎﻟﻒ ﺷﺮوط ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ، وﻋﻠﻴﻪ ﻓﻘﺪ واﻓﻖ اﻟﻤﻮﻛﱢﻞ ﺑﺄن ﺣﺪود اﻟﻤﺴﺆوﻟﻴﺔ اﻟﻘﺎﻧﻮﻧﻴﺔ ﻟﻠﻮﻛﻴﻞ وﻣﺪﻳﺮﻳﻪ وﻣﻮﻇﻔﻴﻪ ﻋﻦ اﻟﺨﺴﺎﺋﺮ أو اﻟﺘﻜﺎﻟﻴﻒ أو اﻷﺿﺮار الناتجة عن التفريط او التعدي  ﻣﻬﻤﺎ ﻛﺎﻧﺖ ﻃﺒﻴﻌﺘﻬﺎ أو اﻟﻤﻄﺎﻟﺒﺎت أو اﻟﻤﺼﺮوﻓﺎت ﻷي ﺳﺒﺐ ﻛﺎن، ﺑﻤﺎ ﻓﻲ ذﻟﻚ اﻷﺗﻌﺎب اﻟﻘﺎﻧﻮﻧﻴﺔ، ﻻ ﺗﺘﺠﺎوز ﺑﺤﺎل ﻣﻦ اﻷﺣﻮال ﻣﻘﺪار ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر اﻟﻤﺪﻓﻮع ﻟﻠﻮﻛﻴــﻞ ﺑﻤــﻮﺟﺐ ﻫــﺬه اﻻﺗﻔﺎﻗﻴــﺔ، ﻋﻠــﻰ أن ﻻ ﻳﺘــﻢ ﺗﻌــﻮﻳﺾ اﻟﻤﻮﻛﱢــﻞ إﻻ ﺑﻤــﻮﺟﺐ ﺣﻜــﻢ ﻗﻀــﺎﺋﻲ ﻣﻜﺘﺴــﺐ اﻟﻘﻄﻌﻴﺔ ",
    inves_agency_article8_3 :" ﻓــﻲ ﺣــﺎل اﻟﺴــﺪاد اﻟﻤﺒﻜــﺮ ﻓﻴﺘــﻢ إﻋــﺎدة اﺣﺘﺴــﺎب اﻟﻌﺎﺋــﺪ اﻟﻤﺴــﺘﺤﻖ ﻟﻠﻤﺴــﺘﺜﻤﺮ ﺑﻨــﺎءً ﻋﻠــﻰ اﻟﺘــﺎرﻳﺦ اﻟﻔﻌﻠــﻲ ﻟﻠﺴﺪاد ",
    inves_agency_article8_4 :" ﻓﻲ ﺣﺎل ﺣﺼﻮل ﺧﺴﺎرة-ﻻ ﻗﺪر ﷲ- ﻓﻲ إﺻﺪار اﻟﺼﻜﻮك ﻓﺈن اﻟﺨﺴﺎرة ﺗﻮزﱠع ﻋﻠﻰ ﺟﻤﻴﻊ اﻟﻤﺴﺘﺜﻤﺮﻳﻦ ﻓﻲ اﻹﺻﺪار ﺑﺤﺴﺐ ﺣﺼﺔ ﻛﻞ ﻃﺮف ﻓﻲ إﺟﻤﺎﻟﻲ ﺣﺼﻴﻠﺔ اﻻﻛﺘﺘﺎب، وﻻ ﻳﺤﻖ ﻟﻠﺸﺮﻛﺔ ﻣﻄﺎﻟﺒﺔ اﻟﻤﺴﺘﺜﻤﺮ ﺑﺄي ﺗﻌﻮﻳﺾ ﻋﻦ ﺟﻬﺪه وﻋﻤﻠﻪ ﻓﻲ ﻫﺬه اﻟﺤﺎل ",
    inves_agency_article9 :" اﻟﻤﺎدة اﻟﺘﺎﺳﻌﺔ: ﻋﺪم ﻣﻤﺎرﺳﺔ اﻟﺤﻘﻮق ",
    inves_agency_article9_1 :" ﻻ ﻳُﻌــﺪ ﻋــﺪم ﻗﻴــﺎم اﻟﻄــﺮف اﻷول أو ﺗــﺄﺧﺮه ﺑﺎﻟﻤﻄﺎﻟﺒــﺔ ﺑﺤﻘــﻮﻗﻪ أو ﻣﻤﺎرﺳــﺘﻪ ﻷي ﺣــﻖ ﻣــﻦ ﺣﻘــﻮﻗﻪ اﻟﻨﺎﺷﺌــﺔ ﺑﻤﻮﺟﺐ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﺗﻨﺎزﻟًﺎ ﻣﻦ ﺟﻬﺘﻪ، وﻳﺤﻖ ﻟﻠﻄﺮف اﻷول أن ﻳﺘﺨﺬ ﻛﺎﻓﺔ اﻹﺟﺮاءات اﻟﺘﻲ ﺗﻜﻔﻞ ﻟﻪ ﺗﺤﺼﻴﻞ ﺣﻘﻮﻗﻪ ﻣﻦ اﻟﻄﺮف اﻟﺜﺎﻧﻲ ﻓﻲ أي وﻗﺖ ",
    inves_agency_article9_2 :" ﻟﻦ ﻳﻜﻮن اﻟﻄﺮف اﻷول ﻣﺴﺆوﻟًﺎ ﻋﻦ أيﱢ ﺧﺴﺎﺋﺮ أو أﺿﺮار ﻳﺘﻌﺮض ﻟﻬﺎ اﻟﻄﺮف اﻟﺜﺎﻧﻲ ﺑﺴﺒﺐ ﻣﻤﺎرﺳﺔ أو ﻋﺪم ﻣﻤﺎرﺳﺔ اﻟﻄﺮف اﻷول ﻷي ﻣﻦ ﺣﻘﻮﻗﻪ اﻟﻨﺎﺷﺌﺔ ﻋﻦ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ أو اﻻﺗﻔﺎﻗﻴﺎت اﻟﻤﺮﺗﺒﻄﺔ ﺑﻬﺎ ",
    inves_agency_article9_3 :" ﻓــﻲ ﺣــﺎل اﻟﺴــﺪاد اﻟﻤﺒﻜــﺮ ﻓﻴﺘــﻢ إﻋــﺎدة اﺣﺘﺴــﺎب اﻟﻌﺎﺋــﺪ اﻟﻤﺴــﺘﺤﻖ ﻟﻠﻤﺴــﺘﺜﻤﺮ ﺑﻨــﺎءً ﻋﻠــﻰ اﻟﺘــﺎرﻳﺦ اﻟﻔﻌﻠــﻲ ﻟﻠﺴﺪاد ",
    inves_agency_article10 :" اﻟﻤﺎدة اﻟﻌﺎﺷﺮة: ﺗﺤﻮﻳﻞ اﻟﺤﻘﻮق ",
    inves_agency_article10_1 :" يحق ﻟﻠﻄــﺮف اﻷول اﻟﺘﻨــﺎزل أو ﺗﺤﻮﻳﻞ ﻛــﻞ أو ﺑﻌــﺾ ﺣﻘــﻮﻗﻪ واﻟﺘﺰاﻣــﺎﺗﻪ اﻟﻨﺎﺗﺠـﺔ ﻋـﻦ ﻫـﺬه اﻻﺗﻔﺎﻗﻴـﺔ واﻻﺗﻔﺎﻗﻴـﺎت اﻟﻤﺮﺗﺒﻄـﺔ ﺑﻬـﺎ إﻟـﻰ ﻣـﻦ ﻳﺸـﺎء، ويقر الطرف الثاني أن توقيغه على هذه الاتفاقية بمثابة الموافقة المسبقة على حق الطرف الأول في احالة حقوقه دون ﺗﻮﻗـﻒ ذﻟـﻚ ﻋﻠـﻰ رﺿـﺎ اﻟﻄـﺮف اﻟﺜﺎﻧﻲ ",
    inves_agency_article10_2 :" ﻻ ﻳﺤﻖ ﻟﻠﻄﺮف اﻟﺜﺎﻧﻲ أن ﻳﺘﻨﺎزل ﻋﻦ ﻛﻞ أو ﺑﻌﺾ أو أن ﻳﺤﻮل اﻟﺘﺰاﻣﺎﺗﻪ اﻟﻤﺘﺮﺗﺒﺔ ﻋﻠﻴﻪ ﺑﻤﻮﺟﺐ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ إﻟﻰ أي ﺟﻬﺔ أﺧﺮى دون ﻣﻮاﻓﻘﺔ ﺧﻄﻴﺔ ﻣﺴﺒﻘﺔ ﻣﻦ اﻟﻄﺮف اﻷول ",
    inves_agency_article11 :" اﻟﻤﺎدة اﻟﺤﺎدﻳﺔ ﻋﺸﺮة: اﻟﻨﻈﺎم واﺟﺐ اﻟﺘﻄﺒﻴﻖ وﺗﺴﻮﻳﺔ اﻟﻤﻨﺎزﻋﺎت ",
    inves_agency_article11_1 :" ﺗﺨﻀﻊ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ وﺗﻔﺴﺮ وﻓﻘًﺎ ﻟﻸﻧﻈﻤﺔ واﻟﻠﻮاﺋﺢ اﻟﻤﻌﻤﻮل ﺑﻬﺎ ﻓﻲ اﻟﻤﻤﻠﻜﺔ اﻟﻌﺮﺑﻴﺔ اﻟﺴﻌﻮدﻳﺔ ",
    inves_agency_article11_2 :" ﻛﻞ ﺧﻼف ﻳﻨﺸﺄ ﺑﻴﻦ اﻟﻄﺮﻓﻴﻦ ﺣﻮل ﺗﻔﺴﻴﺮ أو ﺗﻨﻔﻴﺬ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ أو أي ﺑﻨﺪ ﻣﻦ ﺑﻨﻮدﻫﺎ ﻳﺘﻢ ﺣﻠﻪ ﺑﺎﻟﻄﺮق اﻟﻮدﻳﺔ، ﻓﺈذا ﺗﻌﺬﱠر ذﻟﻚ ﻓﻴﺘﻢ ﺣﻠﻪ ﻋﻦ ﻃﺮﻳﻖ اﻟﻠﺠﻮء إﻟﻰ اﻟﺠﻬﺎت اﻟﻘﻀﺎﺋﻴﺔ اﻟﻤﺨﺘﺼﺔ ﻓﻲ اﻟﻤﻤﻠﻜﺔ اﻟﻌﺮﺑﻴﺔ اﻟﺴﻌﻮدﻳﺔ، ﺑﻤﺪﻳﻨﺔ اﻟﺮﻳﺎض ",
    inves_agency_article12 :" اﻟﻤﺎدة اﻟﺜﺎﻧﻴﺔ ﻋﺸﺮة: أﺣﻜﺎم ﻋﺎﻣﱠﺔ ",
    inves_agency_article12_1 :" ﺗﺴـﺮي اﻷﺣﻜـﺎم واﻟﺸـﺮوط اﻟـﻮاردة ﻓـﻲ ﻫـﺬه اﻻﺗﻔﺎﻗﻴـﺔ ﻋﻠـﻰ أﻃﺮاﻓﻬـﺎ اﻟﻤﻮﺿﺤـﺔ ﺑﻴﺎﻧـﺎﺗﻬﻢ ﻓـﻲ ﺻـﺪرﻫﺎ، ﻛﻤـﺎ ﺗﺴـﺮي ﻋﻠـﻰ ﺧﻠﻔـﺎﺋﻬﻢ اﻟﺸﺮﻋﻴﻴـﻦ واﻟﻘـﺎﻧﻮﻧﻴﻴﻦ، وﺑﻤـﺎ ﻻ ﻳﺘﻌـﺎرض أو ﻳﺨـﺎﻟﻒ اﻷﺣﻜـﺎم واﻟﺸـﺮوط اﻟـﻮاردة ﻓـﻲ اﺗﻔﺎﻗﻴﺔ ﻓﺘﺢ اﻟﺤﺴﺎب ﻋﻠﻰ اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ ﻟﻠﺸﺮﻛﺔ ",
    inves_agency_article12_2 :" تاريخ النفاذ: تم التعديل في ديسمبر 2022 ",
    inves_agency_article12_3 :" ﻳﻘــﺮ اﻟﻄﺮﻓــﺎن ﺑﺄﻧﻬﻤــﺎ ﻗــﺪ اﻃﻠﻌــﺎ ﻋﻠــﻰ ﻛﺎﻓــﺔ ﺑﻨــﻮد ﻫــﺬه اﻻﺗﻔﺎﻗﻴــﺔ وﻣــﺎ ﻳﺮﺗﺒــﻂ ﺑﻬــﺎ ﻣــﻦ اﺗﻔﺎﻗﻴــﺎت، وﻓﻬﻤــﺎ ﻣﺤﺘﻮﻳﺎﺗﻬﺎ، وأﻧﻬﻢ ﻣﻠﺘﺰﻣﻮن ﺑﻜﻞ ﻣﺎ ورد ﻓﻴﻬﺎ ﻣﻦ ﺷﺮوط وأﺣﻜﺎم ",
    inves_agency_article12_4 :" إذا ﺗﺒﻴﻦ أن أيﱠ ﺣﻜﻢ ﻣﻦ أﺣﻜﺎم ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﻣﺨﺎﻟﻒ ﻟﻸﻧﻈﻤﺔ اﻟﻤﻌﻤﻮل ﺑﻬﺎ أو أﺻﺒﺢ ﻛﺬﻟﻚ ﺑﻤﻮﺟﺐ أي ﻧﻈﺎم أو ﺣﻜﻢ ﻗﻀﺎﺋﻲ ﻓﺈن اﻟﺒﻄﻼن ﻳﺮد ﻋﻠﻰ ذﻟﻚ اﻟﺤﻜﻢ أو اﻟﺸﺮط، وﻻ ﻳﺆﺛﺮ ذﻟﻚ ﻋﻠﻰ ﺳﺮﻳﺎن ﺑﺎﻗﻲ اﻷﺣﻜﺎم واﻟﺸﺮوط اﻟﻮاردة ﻓﻲ اﻻﺗﻔﺎﻗﻴﺔ ",
    inves_agency_article12_5 :" ﻳﺘﻢ ﺗﻨﻔﻴﺬ اﻟﻌﻤﻠﻴﺎت ﺧﻼل أﻳﺎم وأوﻗﺎت اﻟﻌﻤﻞ اﻟﺮﺳﻤﻴﺔ، وﻻ ﺗﺪﺧﻞ أﻳﺎم اﻟﻌﻄﻞ واﻹﺟﺎزات اﻟﺮﺳﻤﻴﺔ ﺿﻤﻦ أﻳﺎم اﻟﻌﻤﻞ ﻫﺬه ",
    inves_agency_article12_6 :" ﻓﻲ ﺣﺎﻟﺔ وﻓﺎة اﻟﻤﻮﻛﻞ ﻓﻠﻮرﺛﺘﻪ اﻟﺤﻖ ﻓﻲ إﻣﻀﺎء اﻟﻮﻛﺎﻟﺔ أو ﻓﺴﺨﻬﺎ ﺑﻤﻮﺟﺐ إﺷﻌﺎر ﺧﻄﻲ ﻟﻠﻮﻛﻴﻞ، ﻋﻠﻰ أن ﺗُﺮاﻋﻰ اﻷﺣﻜﺎم اﻟﻮاردة اﻟﻤﺎدة اﻟﺴﺎدﺳﺔ ﻣﻦ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ",
    inves_agency_article12_7 :" يــﺪرك وﻳﻘــﺮ اﻟﻤﻮﻛﱢــﻞ أﻧﱠــﻪ ﻓــﻲ ﺣــﺎل ﺗــﻢ اﻟﺘﺤﻘــﻖ أو اﻻﺷﺘﺒــﺎه ﺑــﺄي ﻋﻤﻠﻴــﺔ ﻣﺘﻌﻠﻘــﺔ ﺑﻐﺴــﻞ اﻷﻣــﻮال وﺗﻤﻮﻳــﻞ اﻹرﻫــﺎب، ﻓﺴــﻴﺘﻢ إﻳﻘــﺎف اﻟﺤﺴــﺎب اﻻﺳــﺘﺜﻤﺎري ﻣﺆﻗﺘًــﺎ أو ﺑﺸﻜــﻞ داﺋــﻢ، وﻓــﻖ ﺳــﻴﺎﺳﺎت اﻹﺑﻼغ ﻋــﻦ ﺗﻠــﻚ اﻟﻮاﻗﻌﺔ، وذﻟﻚ ﺑﻤﻮﺟﺐ ﻧﻈﺎم ﻣﻜﺎﻓﺤﺔ ﻏﺴﻞ اﻷﻣﻮال اﻟﺼﺎدر ﺑﺎﻟﻤﺮﺳﻮم اﻟﻤﻠﻜﻲ رﻗﻢ(20) ﻋﺎم(1439ه)، وﻧﻈـﺎم ﻣﻜﺎﻓﺤـﺔ اﻹرﻫـﺎب وﺗﻤـﻮﻳﻠﻪ اﻟﺼـﺎدر ﺑـﺎﻟﻤﺮﺳﻮم اﻟﻤﻠﻜـﻲ رﻗـﻢ(21) وﺗـﺎرﻳﺦ (12/02/1439ﻫــ)، واﻟﻼﺋﺤـﺔ اﻟﺘﻨﻔﻴﺬﻳﺔ ﻟﻨﻈﺎم ﻣﻜﺎﻓﺤﺔ اﻹرﻫﺎب وﺗﻤﻮﻳﻠﻪ اﻟﺼﺎدرة ﺑﻘﺮار ﻣﺠﻠﺲ اﻟﻮزراء رﻗﻢ(228) وﺗﺎرﻳﺦ (02/05/1440ﻫـ)،وﻧﻈﺎم ﻣﻜﺎﻓﺤﺔ ﺟﺮاﺋﻢ اﻟﻤﻌﻠﻮﻣﺎﺗﻴﺔ: اﻟﺼﺎدر ﺑﺎﻟﻤﺮﺳﻮم اﻟﻤﻠﻜﻲ رﻗﻢ(17) ﻋﺎم(1428ﻫ) ",
    inves_agency_article13 :" اﻟﻤﺎدة اﻟﺜﺎﻟﺜﺔ ﻋﺸﺮة: اﻹﺧﻄﺎرات واﻟﻤﺮاﺳﻼت ",
    inves_agency_article13_1 :" اﻟﻌﻨﺎوﻳﻦ اﻟﻤﺒﻴﻨﺔ ﺑﺼﺪر ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﻟﻜﻞ ﻃﺮف ﻫﻲ ﻋﻨﻮاﻧﻪ اﻟﻨﻈﺎﻣﻲ، وﺗﺘﻢ ﺟﻤﻴﻊ اﻟﻤﺮاﺳﻼت ﻣﻦ ﻃﻠﺒﺎت أو إﺷﻌﺎرات أو إﻗﺮارات أو ﻣﻮاﻓﻘﺎت أو أي ﻣﺴﺘﻨﺪات أﺧﺮى ﻋﻦ ﻃﺮﻳﻘﻬﺎ، أو ﻋﻦ ﻃﺮﻳﻖ اﻟﺒﺮﻳﺪ اﻟﻤﺴﺠﻞ أو اﻟﻔﺎﻛﺲ أو اﻟﺒﺮﻳﺪ اﻹﻟﻜﺘﺮوﻧﻲ أو ﺗﺴﻠﻢ ﺑﺎﻟﻴﺪ أو ﺑﺄي ﻃﺮﻳﻘﺔ ﻣﻦ اﻟﻄﺮق اﻟﻤﻌﺘﻤﺪة ﻟﺪى اﻟﻄﺮف اﻷول، وﺗﻌﺪ اﻟﻤﺮاﺳﻼت اﻟﺘﻲ ﺗﺘﻢ ﻋﻦ ﻃﺮﻳﻖ ﻫﺬه اﻟﻌﻨﺎوﻳﻦ ﻣُﻠﺰﻣﺔ ﻟﻠﻄﺮف اﻟﺜﺎﻧﻲ، وﻻ ﻳُﻌﺘﺪ ﺑﺄي ﺗﻐﻴﻴﺮ ﻟﻬﺬه اﻟﻌﻨﺎوﻳﻦ إﻻ ﺑﻤﻮﺟﺐ ﺧﻄﺎب ﻛﺘﺎﺑﻲ ﺳﺎﺑﻖ إﻟﻰ ﻣﻮﺟﻪ إﻟﻰ اﻟﻄﺮف اﻷول ",
    //Program Information
    prog_info_program_number:"رقم البرنامج",
    prog_info_sukuk_murabha:"صكوك المرابحة",
    prog_info_mansha2a_private:"المنشأة ذات الغرض الخاص 'المصدر'",
    prog_info_Allowance:"الترخيص",
    prog_info_Reason_Allowance:"الغرض من الترخيص",
    prog_info_Provider_Name:"وصي المنشأة ذات الغرض الخاص",
    prog_info_Borrower_teams:"أعضاء مجلس إدارة المنشأة ذات الغرض الخاص",
    prog_info_Member_relation:"العلاقة",
    prog_info_Nationality:"الجنسية",
    prog_info_Sukuk_Form:"هيكل الصكوك",
    prog_info_Sukuk_Paid_Agent:"وكيل حملة الصكوك ووكيل الدفع",
    prog_info_Portal_Admin:"مسؤول المنصة",
    prog_info_Sukuk:"الصكوك",
    prog_info_value_of_instrument:"القيمة الاسمية للصك",
    prog_info_total_instrument_prog_value:"إجمالي القيمة الاسمية للبرنامج",
    prog_info_m7slat_tar7_uses:"استخدام متحصلات الطرح",
    prog_info_Investor_Applied_Condition:"شروط تقديم الخدمات للمستثمرين",
    prog_info_borrowing_reason:"الغرض من الحصول على التمويل",
    prog_info_shepherd:"الراعي",
    prog_info_shepherd_responsibility:"وصف دور الراعي",
    prog_info_shepherd_Comitment:"التزام الراعي",
    prog_info_shepherd_representative:"ممثل الراعي",
    prog_info_Company_Beneficiary:"الشركة (المستفيد)",
    prog_info_Beneficiary_Legal_Entity:"الكيان القانوني للمستفيد",
    prog_info_Beneficiary_Activity:"نشاطات المستفيد",
    prog_info_Beneficiary_Capital:"رأس مال المستفيد",
    prog_info_Company_Owners:"ملاك الشركة",
    prog_info_Ektetab_Type:"طريقة الاكتتاب",
    prog_info_Min_Max_Ektetab:"الحد الأدنى والأعلى للاكتتاب",
    prog_info_Allocation_Subtraction_Limitations:"قيود التخصيص والطرح",
    prog_info_early_refund_right:"حق الاسترداد المبكر",
    prog_info_terminate_sukuk_date:"تاريخ إطفاء الصكوك",
    prog_info_Periodic_destribution_amount:"مبلغ التوزيع الدوري",
    prog_info_desc_role_custodian:"وصف دور أمين الحفظ",
    prog_info_restriction_sukuk:"القيود المفروضة على الصكوك",
    prog_info_sukuk_assets:"موجودات الصكوك",
    prog_info_murabaha_contract:"عقد المرابحة",
    prog_info_sanad_owners_beneficiary:"السند لأمر على ملاك المستفيد",
    prog_info_bond_order_beneficiary_owner:"السند لامر على المستفيد",
    prog_info_instrument_doc:"وثيقة الصك",
    prog_info_regime:"النظام الحاكم",
    prog_info_Refund_Muktatbeen:"اعادة الاموال للمكتتبين",
    prog_info_risk_factor:"عوامل المخاطرة",
    Operation:"العمليات",
    MustanadAltarh:"مستند الطرح",
    Campaign_Attachements:"Campaign Attachements",
    Program_Information:"Program Information",
    Investment_Agreement:"Investment Agreement",
    Sukuk_Murabaha:"Sukuk Murabaha",
    Annual_return_rate:"Annual return rate",
    Please_Fill_your_information:"Please complete your information or waiting for approve",
    Be_Qualified_Investor:"Be Qualified Investor",
    //End Add by Qaysar

  },
  //******************************************************* Start Arabic array *******************************************//
  arabic_translations: {
    "Login_your_account": "تسجيل الدخول",
    "Please_enter_your_details_below": "الرجاء إدخال تفاصيل بياناتك",
    "This_field_is_required": "هذه الخانة مطلوبة",
    "Enter_valid_Mobile_Number": "ادخل رقم جوال صحيح وفعال",
    "LOGIN": "تسجيل الدخول",
    "Login_with_Mobile_Number": "تسجيل الدخول باستخدام رقم الجوال",
    "Login_with_Email": "تسجيل الدخول بالبريد الإلكتروني",
    "Login_with_Password": "تسجيل الدخول باستخدام كلمة المرور",
    "Verify_OTP": "التحقق من  رمز التحقق",
    "A_verification_code_has_been_sent_to": "تم إرسال رمز التحقق إلى",
    "Please_Enter_valid_OTP": "الرجاء إدخال رمز التحقق الصحيح",
    "Resend_OTP": "إعادة إرسال رمز التحقق",
    "bit": "128bit",
    "Secured_payment": "دفع آمن",
    "Copyrights": "حقوق النشر @ التنافسية المالية |جميع الحقوق محفوظة",
    "Dashboard": "لوحة المعلومات",
    "My_Opportunities": "فرصي الاستثمارية",
    "Investments": "الاستثمارات",
    "Operations": "العمليات",
    "Add_Opportunity": "أضف فرصة استثمارية",
    "LOGOUT": "تسجيل خروج",
    "Opportunity_details": "تفاصيل الفرصة الاستثمارية",
    "Company_tagline_Slogan": "إسم المشروع",
    "Companys_share_price": "سعر السهم",
    "Total_Valuation": "قيمة التمويل المطلوب",
    "Min_Investment_per_investor": "الحد الأدنى للاستثمار لكل مستثمر",
    "Max_Investment_per_investor": "الحد الأقصى للاستثمار لكل مستثمر",
    "Upload_pictures_for_the_Opportunity": "تحميل ملفات وصور المشروع",
    "Supported_Format": "صيغةالملف المدعوم: Jpeg، Png، Jpg",
    "Add_image": "إضافة صورة",
    "Upload_Files":"تحميل المرفقات",
    "Fundraise_Opportunity_details": "تفاصيل تمويل الفرصة الاستثمارية",
    "How_much_amount_you_are_expecting_to_raise": "كم المبلغ الذي تتوقعه للتمويل؟",
    "About_company": "عن الشركة",
    "Write_Short_Bio_about_your_company": "اكتب نبذة مختصرة عن شركتك",
    "Reason_to_invest": "سبب الاستثمار",
    "Where_are_you_planning_to_allocate_the_funds": "أين تخطط ان تخصص مبلغ التمويل ؟",
    "Do_you_want_to_introduce_your_team": "هل تريد تقديم فريقك؟",
    "Yes": "نعم",
    "No": "لا",
    "UPLOAD_DP": "تحميل شعار المشروع",
    "Employee_name": "اسم الموظف",
    "Designation": "المسمى الوظيفي",
    "add_more_team_member": "إضافة المزيد من أعضاء الفريق",
    "Terms_Conditions": "الشروط والأحكام",
    "Write_your_Terms_Conditions_here": "اكتب الشروط والأحكام الخاصة بك هنا",
    "SUBMIT_START_OPPORTUNITY": "قدم وابدأ  فرصتك الاستثمارية",
    "Saudi_top_crowdfunding_platform": "أفضل منصة تمويل جماعي في السعودية",
    "We_Know_Your_Needs_Trusted_By": "نحن نعرف احتياجاتك ، يثق بنا 10 ملايين شخص",
    "No_Of_Investments": "عدد الاستثمارات",
    "Total_Investments": "إجمالي الاستثمارات",
    "Total_Profit": "اجمالي الربح",
    "No_Of_Opportunities": "عدد الفرص",
    "Active_Opportunities": "الفرص النشطة",
    "Rejected_Opportunities": "الفرص المرفوضة",
    "Personal_info": "معلومات شخصية",
    "View_KYC_Details": "عرض تفاصيل معلومات الحساب",
    "I_am_a": "أنا",
    "Borrower": "طالب النمويل",
    "Invester": "المستثمر",
    "First_name": "الاسم الاول",
    "Last_name": "العائله(الاسم الاخير)",
    "Optional": "اختياري",
    "Email": "البريد الإلكتروني",
    "Enter_valid_Email_Id": "أدخل بريد إلكتروني صحيح",
    "Mobile_Number": "رقم الجوال",
    "Password": "كلمة المرور",
    "Password_Must_contain": " كلمة المرور يجب أن تحتوي على",
    "Weak": "ضعيفة",
    "At_least_characters": "8 أحرف على الأقل",
    "A_capital_letter": "حرف انجليزي كبير",
    "A_small_letter": "حرف انجليزي صغير",
    "A_number": "رقم",
    "A_special_character": "رمز",
    "Confirm_Password": "تأكيد كلمة المرور",
    "Password_doesnt_matched": "كلمة المرور غير متطابقة",
    "I_accept_all": "موافق على",
    "terms_conditions": "الشروط والأحكام",
    "CREATE_ACCOUNT": "انشاء حساب",
    "Status": "حالة",
    "Skip": "تخطى ",
    "Upload_pictures_for": "تحميل الصور لـ",
    "About": "عن",
    "Tell_about_your": "أكتب عن ",
    "UPDATE": "تحديث",
    "SUBMIT": "إرسال",
    "faq_one": "ما هي منصة التنافسية المالية؟",
    "CFC_answer": "CFC منصة التنافسية المالية هي منصة إقراض رقمية تربط الشركات القائمة بالمستثمرين (المقرضين). تستخدم المنصة التكنولوجيا لربط الطرفين من خلال مبدأ التمويل الجماعي ، أي جمع مبالغ صغيرة من الأموال من العديد من الأفراد.",
    "faq_two": "كيف يمكن معرفة أوقات طرح الفرص؟",
    "CFC_answer_two": "يمكنك متابعة طرح الفرص من خلال زيارتك للمنصة,وكذلك اذا كنت مسجلا بالمنصة سوف يتم اشعارك ببريد الكتروني بشكل دوري للفرص المطروحه",
    "faq_three": "ما المقصود بمصطلح 'اعرف عميلك'؟",
    "CFC_answer_three": "يشير مصطلح 'اعرف عميلك' للقواعد المحددة مسبقًا من قبل هيئة السوق المالية (CMA) ويستخدم طوال عملية تحديد هوية العميل. وهي المتطلبات القياسية التي يجب اتباعها من قبل جميع الكيانات الخاضعة للتنظيم. يتضمن ذلك التحقق من الهوية وإثبات العنوان ومعلومات التوظيف والمعلومات العامة الأخرى. يحتاج المستثمرون إلى معرفة جميع متطلبات 'اعرف عميلك' قبل الانضمام إلى منصة CFC. سيجري قسم الامتثال فحوصات KYC المستمرة لضمان تحديث المعلومات باستمرار.",
    "faq_four": "ماهي الإجراءات المتخذة لضمان حماية بياناتي الخاصة ولحماية النظام في المنصة؟",
    "CFC_answer_four": "تم تطوير منصة التنافسية المالية على الخادم الخاص بنا. استخدمت التنافسية المالية اعلى ميزات الأمان 'الأفضل في فئتها' مثل التشفير وإدارة الهوية والوصول وأمن الشبكة. ويتم تطبيق هذه الميزات عبر النظام الأساسي بأكمله بدءًا من الاحتفاظ بالبيانات والوصول إلى التطبيقات واتصالات الويب والعمليات الداخلية. ونحن ملتزمون بالتنفيذ والتحسين المستمر وتطوير البرامج المحسنة للأمان ، والإدارة التشغيلية ، وممارسات التخفيف من التهديدات التي تعتبر ضرورية لحماية قوية للخدمات والبيانات",
    "Great_things_need_funds_We_know_you_do_too": " نجاح فرصتك بقدرة ادوات تقييم فرصتك وحجم تمويلك",
    "great_things_cfc": "CFC منصة التنافسية المالية هي منصة إقراض رقمية تربط الشركات القائمة بالمستثمرين (المقرضين). تستخدم المنصة التكنولوجيا لربط الطرفين من خلال مبدأ التمويل الجماعي ، أي جمع مبالغ صغيرة من الأموال من العديد من الأفراد.",
    "Shariah_Compliance": "منتجاتنا مع الشريعه الاسلامية",
    "Free_promotion_for_your_campaign": " ترويج مجاني لحملتك",
    "withdraw_your_amount_instantly": "السحب الفوري لمبالغك",
    "How_to_start_your": "كيف تبدأ ",
    "fundraiser_on_Compp_Fintect": "لجمع التمويلات على Financial التنافسية.",
    "Easy_Just_Follow": "سهل ، ما عليك سوى اتباع الخطوات البسيطة أدناه",
    "Enter_Details": "ادخل تفاصيل معلوماتك",
    "kyc_answer": " قم بإدخال معلومات محددة ؛ معلومات شخصية ، معلومات عن المشروع ، البيانات الماليه المطلوب فقط وفقًا لشروط الجهة التنظيمية ولغرض دراسة الفرصه",
    "Verify_by_KYC": "التحقق من 'معلومات اعرف عميلك'",
    "verify_answer": "لجهة المنظمة تشترط التحقق من المعلومات والبيانات المقدمه من خلالك بواسطة الطرق الامنه ومن الجهات المرخص لها بذلك",
    "Get_Approval": "الحصول على موافقة",
    "approval_answer": " سوف تحصل على الموافقة واشعارك اليا من خلال نظام  ادارة علاقات العملاء في المنصة مثل البريد الالكتروني  والرسائل النصية.",
    "ready_to_start": "هل انت مستعد لتبدأ رحلة تمويل مشروعك⸮",
    "Get_approval_in_minutes": "احصل على الموافقة في أقل وقت",
    "faq": "أسئلة مكررة",
    "Give_your_dreams_a_boost": "أعط دفعة لأحلامك ،",
    "Start_your_crowdfunding_today": "ابدأ التمويل الجماعي اليوم.",
    "Easy_Funding_options_For_you": "نوفر لك منتجات للتمويل واضحه تناسب مشروعك",
    "Funding_made_simple": "أصبح التمويل بسيطًا",
    "select_registration_type": "حدد نوع التسجيل",
    "Individual": "فرد",
    "Corporate": "شركة",
    "heading": "رؤية مستقبلية واعدة للمساهمة في القطاع المالي في المملكة العربية السعودية",
    "content_one": "من خلال حلول مالية تقنية مبتكرة ومتميزة للاستثمار والتمويل",
    "heading_two": "تأسست شركة التنافسية المالية في سبتمبر 2021م، وحصلت التنافسية على تصريح التقنية المالية في أعمال الأوراق المالية​ من هيئة السوق المالية في يونيه 2022م، لطرح أدوات الدين والاستثمار فيها.",
    "about_content_one": "التنافسية المالية هي منصة إلكترونية للتمويل الجماعي، تهدف إلى وصل المستثمرين بالفرص الاستثمارية لتمويل المشاريع، من خلال ترتيب إصدار وطرح أدوات الدين لتمويل مشاريع الشركات الصغيرة والمتوسطة، اﻟﺘﻲ ﺗﺴﺎﻫﻢ بدورها ﻓﻲ رﻓﻊ اﻟﻨﺎﺗﺞ اﻟﻤﺤﻠﻲ الإجمالي و ﺗﻮﻓﻴﺮ الوظائف، وعرض تلك الفرص في المنصة على المستثمرين عملاء المنصة",
    "about_content_two": "وكانت الهيئة قد إطلقت مختبر التقنية المالية عام 2018م، حرصاً منها على مواكبـــة الثورة التقنية المتســـارعة فـــي الســـوق الماليـــة. حيث تمتاز منظومة التقنية المالية في المملكة بجاذبية عالية مما يتيح للشركات تقديم الخدمات المبتكرة بسهولة",
    "about_content_three": "التنافسية المالية هي أحدى شركات التنافسية الدولية للتقنية وهي مؤسسة وطنية تهدف إلى تقديم الاستشارات التقنية المتكاملة للمنظمات والهيئات الحكومية والمشاركة في إعادة هيكلة الأنظمة والإجراءات لتعزيز الوصول لأهداف رؤية المملكة العربية السعودية ",
    "FINANCIAL_DIFFERENCE": "ويقوم فريق عمل التنافسية المالية بتسخير خبراته في التحليل الائتماني لمشاريع الشركات بناء على التحليل الكمي والتحليل النوعي لجدوى المشروع والشركة وإدارتها وقوائمها المالية، للوصول إلى النطاق التصنيفي لمخاطر الاستثمار. بعد ذلك، يتم إصدار أداة الدين وهي الصكوك، التي يتم الاستثمار فيها",
    "ABOUT_US": "عن التنافسية المالية ",
    "shariah": "التوافق مع الشريعه الاسلامية",
    "What_is_Sukuk": "ما هي الصكوك؟",
    "Sukuk_answer": "الصكوك  هي أوراق مالية تصدرها  الشركات (أو الحكومات)  لجمع الأموال من المستثمرين لفترة زمنية محددة بتاريخ سداد محدد، وخلال هذه الفترة عادةً ما توزع الصكوك معدل ربح (ثابت أو متغير) بشكل دوري. وفي نهاية عمر الصك، المعروفة بفترة الاستحقاق، يقوم مصدر الورقة المالية (المقترض) بسداد رؤوس الأموال التي تم جمعها من المستثمرين.",
    "How_do_I_make_profit": "كيف أحصل على الأرباح من هذه الفرص؟",
    "profit_answer": "لكل ﻓﺮﺻﺔ استثمارية توقيت توزيع مختلف عن الأخرى، كأن يكون رﺑﻊ ﺳﻨﻮي أو ﻧﺼﻒ ﺳﻨﻮي أو تسدد دﻓﻌﺔ واحدة، وهي فترة الاستحقاق في نهاية عمر الصك.",
    "Risk_warning": "التحذيرات من المخاطر",
    "Risk_warning_answer": "إشعار المخاطر: يقر ويدرك المستخدم/المستثمر بعلمه واطلاعه بأن الاستثمارات بجميع أنواعها تنطوي على درجة من المخاطر، وأن الاستثمار في الأوراق المالية عبر منصة التنافسية المالية يعتبر استثمار عالي المخاطر، وأن الصكوك ليست مضمونة أو مؤمن عليها بأي شكل، كما أن استثماره عرضة لجميع أنواع المخاطر والخسارة بشكل كلي أو جزئي، وأن الاستثمار فيها قد يخضع لقيود من حيث المدة وإمكانية البيع أو التسييل.",
    "Investor": "مستثمر",
    "plan": "تخطط لجمع المال لأعمالك؟ تحقق من خياراتنا الخالية من المتاعب لك.",
    "invest": "استثمر في أعمال سريعة النمو معنا ، منصة استثمار آمنة ومأمونة بنسبة 100٪ في المملكة العربية السعودية.",
    "General": "عام",
    "Explore": "استكشف موقع التنافسية المالية للحصول على معلومات واقتراحات ونصائح حول التمويل الجماعي والاستثمار",
    "PRODUCT_FEATURES": "مواصفات المنتج",
    "What_makes_us_different": "ما الذي يجعلنا مختلفين؟",
    "To_Offer": "لعرض أدوات الدين والاستثمار فيها.",
    "Details_answer": "قدم معلومات الاتصال الخاصة بك وقم بتسجيل الدخول إلى حسابك لبدء العملية.",
    "Provide_your_national_ID": "أدخل رقم هويتك الوطنية لغرض التحقق",
    "Submit_your_KYC": "أرسل بياناتك  واحصل على الموافقة في غضون 24 ساعة",
    "Projects": "المشاريع",
    "Total_Raised": "إجمالي ما تم تمويله",
    "Loan_terms": "مدة التمويل من 1 إلى 36 شهرًا",
    "Financing": "تمويل سريع",
    "Customised_loan": "تمويل مخصص يناسب احتياجاتك",
    "Lets_get_in_touch": "نتشرف بتواصلك معنا",
    "Type_your_message_here": "اكتب رسالتك هنا",
    "crafted": " بواسطة Imcrinox Technologies",
    "Register_as_Borrower": "تسجيل طالب التمويل",
    "Register_as_Investor": "تسجيل مستثمر",
    "privacy_policy": "إشعار الخصوصية",
    "terms_head_one": "التمهيد:",
    "terms_head_two": "المادة الأولى: التعريفات:",
    "terms_head_three": "المادة الثانية: التعريف بالمنصة:",
    "terms_head_four": "المادة الثالثة: المشغل والمزود للمنصة:",
    "terms_head_five": "المادة الرابعة: التسجيل:",
    "terms_head_six": "المادة الخامسة: اتفاق الوكالة بالاستثمار:",
    "terms_head_seven": "المادة السادسة: حدود المسؤولية:",
    "terms_head_eight": "المادة السابعة: المخاطر العامة:",
    "terms_content_one": "يرتبط الاستثمار بالشركات الناشئة بمخاطر عالية، وقد يؤدي إلى الخسارة الكاملة لاستثمارك. يجب ألا تستثمر الأموال التي لا يمكنك تحمل خسارتها، وفي حال الخسارة يُقتصر على المبلغ المستثمر فقط. الاستثمار من خلال التنافسية المالية هو استثمار طويل الأجل ومناسب للمستثمرين على المدى الطويل. إن فرص الاستثمار في الوقت الحالي مخصصة للأشخاص المقيمين في المملكة العربية السعودية. يجب على المستخدم قراءة هذه الاتفاقية بعناية حيث توضح تفاصيل الخدمة التي تقدمها شركة التنافسية المالية وتحدد الالتزامات والحقوق بين التنافسية المالية والمستخدم، ويمنع استخدام المنصة في حال عدم فهم واستيعاب كافة مواد الاتفاقية. فهذه هي اتفاقية استخدام منصة التنافسية المالية وجميع صفحاتها الفرعية ولجميع العلاقات التعاقدية بين شركة التنافسية المالية",
    "terms_content_four": "شركة التنافسية المالية هي المشغل والمزود لمنصة التنافسية المالية، والخدمة المقدمة تخضع لشروط التنافسية المالية التالية التي يجب أن تطبق في النسخة السارية وقت تسجيل المستخدم.",
    "privacy_heading": "يصف إشعار الخصوصية هذا كيف شركة التنافسية المالية (يشار إليها فيما بعد باسم 'الشركة')، تجمع البيانات الشخصية وكيفية معالجتها واستخدامها وحمايتها داخل المملكة العربية السعودية.",
    "privacy_heading_one": "تعريفات:",
    "privacy_heading_two": "البيانات الشخصية التي نجمعها:",
    "privacy_heading_three": "الأساس القانوني وأغراض جمع واستخدام بياناتك الشخصية:",
    "privacy_heading_four": "كيف يتم جمع بياناتك الشخصية:",
    "privacy_heading_five": "تخزين بياناتك الشخصية:",
    "privacy_heading_six": "حماية بياناتك الشخصية:",
    "privacy_heading_seven": "الإفصاح عن بياناتك الشخصية:",
    "privacy_heading_eight": "التغييرات على إشعار الخصوصية",
    "privacy_heading_nine": "استخدام ملفات تعريف الارتباط",
    "privacy_heading_ten": "اتصل بنا",
    "privacy_heading_eleven": "تاريخ النفاذ",
    "privacy_heading_tewlve": "إخلاء مسئولية",
    "Settings": "إعدادات",
    "value_cannot_exceed": "لا يمكن أن تتجاوز القيمة أكثر من",
    "characters": "الرموز",
    "User_Name": "اسم االمستخدم",
    "Full_Name": "الاسم بالكامل",
    "investment": "إستثمر الان",
    "setting": "إعدادات",
    //Added By Qaysar For Translate the sit
    "Envist": "إستثمر",
    "Investers": "المستثمرين",
    "Price_Per_Share": "قيمة الصك",
    "Valuation": "مبلغ التمويل",
    "Min_Investment": "الحد الادنى للإستثمار",
    "Max_Investment": "الحد الأعلى للإستثمار",
    "Team": "فريق العمل",
    "Terms": "الاحكام",
    "Reasons_to_Invest": "سبب الاستثمار",
    "Invest": "إستثمر",
    "Enter_Amount": "أدخل المبلغ",
    "All_Opportunities": "جميع الفرص",
    "Closed_Opportunities": "الفرص المغلقة",
    "Sorry_No_data_to_display": "نعتذر , لا يوجد بيانات للعرض!",
    "All_Campaign": "جميع الفرص",
    "Closed_Campaign": "الفرص المغلقة",
    "Raised": "ممول",
    "Modal_title": "شاشة الدفع",
    "Amount": "المبلغ",
    "Close": "إغلاق",
    "Pay": "إدفع",
    "Save_changes": "حفظ التعديلات",
    "Allocation": "مخصص",
    "Updates": "التعديلات",
    "Funds_allocation": "تخصيص التمويل",
    "Please_enter_your_payment_details": "الرجاء إدخال تفاصيل الدفع",
    "Credit_Card": "بطاقة إئتمانية",
    "Card_Number": "رقم البطاقة",
    "Expiry_Month": "شهر الانتهاء",
    "Expiry_Year": "سنة الانتهاء",
    "Security_Code": "رمز الأمان",
    "Cardholder_Name": "اسم حامل البطاقة",
    "Kyc_Details": "تفاصيل المعلومات",
    "Edit_Profiel": "تعديل الملف الشخصي",
    "Number_of_Oppertunity": "عدد الفرص",
    "Total_Amount_Raised": "إجمالي التمويل",
    "Total_Repayment": "إجمالي السداد",
    "Profile_Info": "معلومات الملف الشخصي",
    "Name": "الاسم",
    "Email_ID": "البريد الالكتروني",
    "Contact_Number": "رقم التواصل",
    "View_Opportunity": "استعراض الفرصة",
    "Number_of_Investment": "عدد الاستثمارات",
    "Total_Amount_Invested": "إجمالي المبالغ المستثمره",
    "Account_Number": "رقم الحساب",
    "Retail_And_Sophisticated_Investors": "مستثمرين مؤهلين وأفراد",
    "Total_Opportunities": "إجمالي الفرص",
    "Funded": "المموله",
    "Pledged_Of_SAR": "حجم البرنامج بالريال",
    "Goal": "المستهدف",
    "Fundin_Status": "حالة التمويل",
    "Closedp": "مغلقة",
    "Total_Invested": "إجمالي الاستثمار",
    "Closed_investment": "الاستثمارات المغلقة",
    "PREVIEW": "استعراض",
    "Back": "رجوع",
    "Received_Investment": "استثمارات مستلمة",
    "Date": "تاريخ",
    "Transaction_ID": "رقم العملية",
    "Invested": "قيمة الاستثمار ",
    "Raised_amount": "مبلغ التمويل",
    "Pending_amount": "المبلغ المتبقي",
    "Edit_Profile": "تعديل الملف الشخصي",
    "Approved": "معتمد",
    "Pending": "قيد الاجراء",
    "verify": "تحقق",
    "Check_Data": "تحقق البيانات",
    "Next": "التالي",
    "Password_must_be_8_characters_or_more": "كلمة المرور يجب ان لا تقل عن 8 احرف",
    "Forget_Password": "نسيت كلمة المرور",
    "Investment_opportunities": "الفرص الاستثمارية",
    "Open_and_ongoing_popular_croudfungings_for_you_to_choose_from": "الفرص المتاحة للإستثمار",
    "Close_Date": "تاريخ الاغلاق",
    "Open_Date":"تاريخ الفتح",
    "View_Details": "عرض التفاصيل",
    "EXPLORE_ALL": "إستعراض",
    "Upcoming_opportunities": "الفرص القادمة",
    "WeatherFlow_Tempest_Inc": "WeatherFlow-Tempest, Inc",
    "Controlling_the_Cost_of_Weather": "Controlling the Cost of Weather",
    'Amount_Paid': "المبلغ المدفوع",
    "Transaction_History": "سجلات العمليات",
    "Upcoming_Payments": "الدفعات القادمة",
    "Sort_By_Recent": "الترتيب بالاحدث",
    "Recent": "الاحدث",
    "Monthly_Installment": "الدفعات الشهرية",
    "Amount_paid": "المبلغ المدفوع",
    "Principle_paid": "المبلغ المدفوع-محتسب",
    "Principle_Left": "المبلغ المتبقي-محتسب",
    "Due_payment": "المبلغ المستحق",
    "PAY_NOW": "إدفع الان",
    "Installment_paid": "قيمة الدفعة",
    "Available_cash_in_your_CFC_wallet": "الرصيد المتاح في المحفظة",
    "ADD_AMOUNT": "إضافة مبلغ",
    "Your_active_funds": "التمويلات النشطة",
    "FlyForward_Corp": "FlyForward Corp",
    "The_Next_Tech_Of_Aviation": "The Next Tech Of Aviation",
    "Amount_Raised": "مبلغ التمويل",
    "Due_this_month": "استحقاق هذا الشهر",
    "Share_Price": "سعر الصك",
    "Minimum_Investment": "الحد الادنى للاستثمار",
    "Maximum_Investment": "الحد الاعلى للاستثمار",
    "Invested_Date": "تاريخ الاستثمار",
    "Invested_Amount": "مبلغ الاستثمار",
    "Due_Date": "تاريخ الاستحقاق",
    "Principle_Expected": "المبلغ المتوقع",
    "Interest_Expected": "نسبة المرابحة المتوقعة",
    "Fees_Expected": "الرسوم المتوقعه",
    "Total_Expected": "اجمالي المبالغ المتوقعة",
    "Principle_Paid": "المبلغ المدفوع",
    "Interest_Paid": "نسبة المرابحة المدفوعة",
    "Fees_Paid": "الرسوم المدفوعة",
    "Total_Paid": "اجمالي الدفع",
    "Paid_Date": "تاريخ الدفع",
    "Principle_Due": "المبلغ المستحق",
    "Interest_Due": "نسبة المرابحة المستحقة",
    "Fees_Due": "الرسوم المستحقة",
    "Total_Due": "اجمالي المستحق",
    "Profit": "نسبة المرابحة",
    "Priciple": "المبلغ المحتسب",
    "Total": "الاجمالي",
    "MyProfile": "ملفي الشخصي",
    "change_password": "تغيير كلمة المرور",
    "Old_Passsword": "كلمة المرور القديمة",
    "New_Password": "كلمة المرور الجديدة",
    "Save": "حفظ",
    "CopyWrightCfC": "حقوق النشر @ التنافسية المالية |جميع الحقوق محفوظة",
    "Principle_Amount": "المبلغ المحتسب",
    "Profit_Amount": "قيمة المرابحة",
    "Total_Amount": "المبلغ الاجمالي",
    "Enter_Valid_Mobile_Number_Ex": "أدخل رقم هاتف جوال صالح (مثال: 0551234567 أو 551235678)",
    "Debit_History": "سجلات مدينة",
    "Credit_History": "سجلات دائنة",
    "Amount_Raised_Intrese": "مبلغ نسبة المرابحة",
    "Final_Amount": "المبلغ الكلي",
    "Upvoming_Transaction_History": "العمليات القادمة",
    "Installment_To_Pay": "القسط المستحق للدفع",
    "Total_Amount_to_be_Paid": "المبلغ الاجمالي المستحق",
    "amountYetToReceive": "المبالغ المتبقية",
    "Withdraw_on": "سحب المبلغ",
    "Final_Reciveable": "اجمالي الاستلام",
    "Recieved_Amount": "المبلغ المستلم",
    "Withdrawl_Amount": "المبلغ المسحوب",
    "Profit_Received": "المرابحة المستلمة",
    "Credited_Amount": "المبلغ المودع",
    "My_Wallet": "محفظتي",
    "amountYetToPay": "رصيد المحفظة",
    "Enter_the_Amount": "أدخل المبلغ",
    "Amount_Received": "المبلع المستلم",
    "Thank_You_Application_recieved": "شكرا - تم استلام طلبك",
    "Review_profile_msg": "ملفك قيد التحقق سيقوم ممثل التنافسية المالية بالتواصل معكم",
    "OK_Thanks_Btn": "شكرا لك",
    "Competitiveness_Financial":"التنافسية المالية",
    "Investment":"الاستثمار",
    "Raise":"التمويل",
    "Legal":"القانونية",
    "Account":"الحساب",
    "Sign_Out":"تسجيل الخروج",
    "Wallet":"المحفظة",
    "Payments":"المدفوعات",
    "Opportunity_List":"قائمة الفرص",
    "Operation":"العمليات",
    //Added for sukuk documents page
    "tar7_document_note_title_1_a":" مستند الطرح – صكوك المرابحة 1-111-22 ",
    "tar7_document_note_title_1_b":" والمطروحة على منصة شركة التنافسية المالية ",
    "tar7_document_note_1_1":" تحتوي النشرة على معلومات المصدر والمستفيد ",
    "tar7_document_note_1_2":" والمعلومات المتعلقة بالإصدار الأول ",
    "tar7_document_note_1_3":" يعمل المستفيد وفقا للرقم الموحد رقم ",
    "tar7_document_note_1_3_1":" تجاوزت مبيعات المستفيد حسب القوائم المالية ",
    "tar7_document_note_1_4":" لعامي ",
    "tar7_document_note_1_5":" وهامش صافي أرباح ",
    "tar7_document_note_1_6":" على التوالي من إجمالي المبيعات ",
    "tar7_document_note_1_7":" لدى المستفيد نسبة سيولة جارية تبلغ ",
    "tar7_document_note_1_8":" وعائد على الاصول يبلغ ",
    "tar7_document_note_1_9":" وإجمالي الديون على الاصول ",
    "tar7_document_note_1_10":" حسب القوائم المالية لعام ",
    "tar7_document_note_1_11":" يعتزم المستفيد طرح برنامج لإصدار صكوك مرابحة بقيمة ",
    "tar7_document_note_1_12":" ريال سعودي، بناء عليه، سيكون طرح الإصدار الأول من البرنامج بقيمة ",
    "tar7_document_note_1_13":" ريال سعودي تستحق بتاريخ ",
    "tar7_document_note_1_14":" بعائد سنوي ",
    "tar7_document_note_1_15":" على القيمة الاسمية للصك ",
    "tar7_document_note_1_16":" ريال سعودي ويتم توزيع الأرباح بشكل دوري، كما سيتم إطفاء صكوك كل إصدار ذي صلة دفعة واحدة في تاريخ الإطفاء ",
    "tar7_document_note_1_17":" على المستثمرين الراغبين بالاستثمار في الإصدار التسجيل كمستثمر في منصة التنافسية المالية للاستثمار على الرابط التالي ",
    "tar7_document_note_1_18":" الحد الأعلى للمستثمرين المؤهلين هو تغطية كامل قيمة الإصدار، بينما الحد الأعلى للمستثمر الفرد هو ( 20,000 ) عشرون ألف ريال سعودي لكل 'مستفيد' للسنة الواحدة، علماً أن الحد الأدنى للاستثمار هو صك واحد بقيمة (1,000) ألف ريال سعودي.",
    "tar7_document_note_title_2":"إشعار هام",
    "tar7_document_note_2_1":"تحتوي نشرة الإصدار 'النشرة' على معلومات يتحمل المستفيد والراعي الذي يظهر اسمه في فقرة الراعي من ملخص معلومات الإصدار مجتمعًا مع المستفيد أو منفردًا كامل المسؤولية عن دقة المعلومات الواردة في نشرو الإصدار هذه، ويؤكد المستفيد والراعي بحسب علمهما واعتقادهما، بعد إجراء جميع الدراسات الممكنة وإلى الحد المعقول، أنه لاتوجد أي وقائع أخرى يمكن أن يؤدي عدم تضمينها في النشرة إلى جعل أي إفادة واردة فيها مضللة. ولا تتحمل هيئة السوق المالية أو شركة التنافسية المالية للاستثمار مجتمعين أو منفردين أي مسؤولية عن محتويات هذه النشرة، ولا تعطيان أي تأكيدات تتعلق بدقتها أو اكتمالها، وتخليان نفسيهما صراحة من أي مسؤولية مهما كانت عن أي خسارة تنتج عما ورد في هذه النشرة أو عن الاعتماد على أي جزء منها.",
    "tar7_document_note_2_2":"الأوراق المالية المطروحة صادرة عن منشأة ذات أغراض خاصة مرخص لها من قبل هيئة السوق المالية. وتحتفظ هيئة السوق المالية بسجل للمنشأة ذات الأغراض الخاصة وتنظمها. ولا تصدر هيئة السوق المالية موافقة على، ولاتكون مسؤولة عن، مستندات الطرح ولا الموافقة عليها ، ولا أحكام الأوراق المالية التي تصدرها المنشأة ذات الأغراض الخاصة أو هياكل التمويل التي تستخدمها، أو مخاطر الاستثمار أو العوائد المرتبطة بالأوراق المالية. ولا تنظم هيئة السوق المالية ولا تراقب قيمة أصول المنشأة ذات الأغراض الخاصة أو قدرتها على الوفاء بالتزاماتها، ولا تقدم أي اعتمادات أو توصيات عن الأوراق المالية.",
    "tar7_document_note_title_3" :"برنامج إصدار صكوك المرابحة",
    "tar7_document_note_3_1_a" :"سيمكن برنامج إصدار صكوك المرابحة",
    "tar7_document_note_3_1_b" :"من طرح مجموعة من إصدارات الصكوك من حين لآخر و ذلك وفقاً للأنظمة والتعليمات ذات الصلة",
    "tar7_document_note_3_2" :"تُصدر الصكوك وتسجل إلكترونياً بالقيمة الاسمية المحددة للصك الواحد وفقاً للشروط النهائية الخاصة بالإصدار.",
    "tar7_document_note_3_3" :"كما هو موضح في الشروط والأحكام للطرح، فإن الصكوك تمنح لحملتها الحق في الحصول على مبالغ مالية تتولد من أصول الصكوك الخاصة بالإصدار ذي الصلة. ويمثل كل صك حصة ملكية مشاعة في أصول الصكوك، وتُرتب هذه الصكوك لحملتها حقوقاً متساوية فيما بينهم طوال الوقت دون تفضيل.",
    "tar7_document_note_3_4" :"ستحدد الشروط النهائية لكل إصدار القيمة الاسمية للصكوك ذات الصلة، وسعر إصدارها، ومعدل العائد وغيرها من المعدومات المتعدقة بالإصدار ذي الصلة.",
    "tar7_document_note_3_5" :"أجازت اللجنة الشرعية لشركة التنافسية المالية للاستثمار نموذج عمل الصكوك المصدرة من خلال منصة التنافسية المالية للاستثمار. ولن تكون قابدة للتداول على منصة الصكوك، وذلك بحسب أنظمة هيئة السوق المالية، وأحكام الشريعة الإسلامية المتعلقة بصكوك المرابحة، إلا من خلال آلية التخارج في ضوء الإجراءات الداخلية لشركة التنافسية المالية للاستثمار المتوافقة مع الضوابط المعتمدة من اللجنة الشرعية لشركة التنافسية المالية للاستثمار.",
    "tar7_document_note_3_6" :"عند قراءة هذا المستند وتفسيره يجب مراعاة أي تعديل أو إضافة تطرأ عليه ويجب كذلك مراعاة أي معلومات خارجية مشار إليها فيه. وفيما يخص كل إصدار ضمن البرنامج، فيجب مراعاة وقراءة الشروط النهائية المتعلقة بالإصدار ذي الصلة.",
    "this_document_prepared":"صدرت مذكرة المعلومات هذه في ",
    "On_Date":"الموافق ",
    "ID":"الرمز",
    "Attachment":"المرفق",

    //Investment agency agreement
    "investment_agency_agreement_title":" اﺗﻔﺎﻗﻴﺔ وﻛﺎﻟﺔ ﺑﺎﻻﺳﺘﺜﻤﺎر ",
    "inves_agency_intruduction": "اﻟﻤُﻘﺪﻣﺔ",
    "inves_agency_ThanksGod":" اﻟﺤﻤﺪ ﻟﻠﻪ، واﻟﺼﻼة واﻟﺴﻼم ﻋﻠﻰ ﻧﺒﻴﻨﺎ ﻣﺤﻤﺪ، وﻋﻠﻰ آﻟﻪ وﺻﺤﺒﻪ، وﺑﻌﺪ ",
    "inves_agency_inDay":" إﻧﻪ ﻓﻲ ﻳﻮم ",
    "inves_agency_in":" اﻟﻤﻮاﻓﻖ ",
    "inves_agency_doingThis": " أُﺑﺮﻣﺖ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﺑﻴﻦ ﻛﻞ ﻣﻦ: ",
    "inves_agency_Competitiveness_info": " ﺷﺮﻛﺔ التنافسية اﻟﻤﺎﻟﻴﺔ وﻫﻲ ﺷﺮﻛﺔ ﻗﺎﺋﻤﺔ ﺑﻤﻮﺟﺐ ﻗﻮاﻧﻴﻦ اﻟﻤﻤﻠﻜﺔ اﻟﻌﺮﺑﻴﺔ اﻟﺴﻌﻮدﻳﺔ، وﻋﻨﻮان ﻣﻘﺮﻫﺎ اﻟﺮﺋﻴﺴﻲ: اﻟﻤﻤﻠﻜــﺔ اﻟﻌﺮﺑﻴــﺔ اﻟﺴــﻌﻮدﻳﺔ، ﻣﺪﻳﻨــﺔ اﻟﺮﻳــﺎض ﻃﺮﻳــﻖ الأمير عبدالعزيز بن مساعد بن جلوي ﺣــﻲ المربع، ص. ب. 12626، وﻫــﻲ ﺷﺮﻛــﺔ ﻣﺼـﺮﺣﺔ ﻣـﻦ ﻗﺒـﻞ ﻫﻴﺌـﺔ اﻟﺴـﻮق اﻟﻤﺎﻟﻴـﺔ ﻹﻧﺸـﺎء ﻣﻨﺼـﺔ ﻃـﺮح أدوات اﻟـﺪﻳﻦ واﻻﺳـﺘﺜﻤﺎر ﻓﻴﻬـﺎ ﻓـﻲ ﻣﺨﺘـﺒﺮ اﻟﺘﻘﻨﻴـﺔ اﻟﻤﺎﻟﻴﺔ. وﻳُﺸﺎر إﻟﻴﻬﺎ ﻓﻲ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﺑـــــــــ)اﻟﺸﺮﻛﺔ. ",
    "inves_agency_Mr": " السيد ",
    "inves_agency_Saudi": " (سعودي) ",
    "inves_agency_national_id" : " رقم الهوية ",
    "inves_agency_in_date":" بتاريخ ",
    "inves_agency_invester_address":" وعنوانه الرئيسي :المملكة العربية السعودية - ",
    "inves_agency_indicate_data":" وﻳُﺸﺎر إﻟﻴﻪ ﻓﻲ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﺑــأي من المصطلحات التالية:)اﻟﻄﺮف اﻟﺜﺎﻧﻲ-اﻟﻌﻤﻴﻞ، اﻟﻤﻮﻛﱢﻞ-اﻟﻤﺴﺘﺜﻤﺮ.( وﻳُﺸﺎر إﻟﻰ اﻟﻄﺮف اﻷول واﻟﻄﺮف اﻟﺜﺎﻧﻲ ﻣﺠﺘﻤﻌﻴﻦ ﻓﻴﻤﺎ ﺑﻌﺪ ﺑـــــــ)اﻟﻄﺮﻓﺎن-اﻟﻄﺮﻓﻴﻦ( ",
    "inves_agency_definition_appendex":" ملحق التعريفات: ",
    "inves_agency_definition_appendex_word" :" ﻳﻘﺼﺪ ﺑﺎﻟﻌﺒﺎرات اﻟﺘﺎﻟﻴﺔ أﻳﻨﻤﺎ وردت ﻓﻲ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ",
    "inves_agency_defin_appen_1":" اﺗﻔﺎﻗﻴﺔ اﻟﻮﻛﺎﻟﺔ ﺑﺎﻻﺳﺘﺜﻤﺎر : ﻋﻼﻗﺔ ﺗﻌﺎﻗﺪﻳﺔ ﺑﻴﻦ ﻣﻮﻛﱢﻞ ووﻛﻴﻞ ﻳﻘﻮم اﻟﻤﻮﻛﱢﻞ ﺑﻤﻮﺟﺒﻬﺎ ﺑﺘﻌﻴﻴﻦ اﻟﻮﻛﻴﻞ ﻟﻠﻘﻴﺎم ﺑﺄﻋﻤﺎل ﻣﺤﺪدة ﻧﻴﺎﺑﺔ ﻋﻨﻪ، وﻓﻘٍﺎ ﻟﻤﺎ ﺟﺎء ﻓﻲ اﻟﺘﻤﻬﻴﺪ واﻟﻤﺎدة اﻟﺜﺎﻟﺜﺔ ﻣﻦ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ، ﻓﻲ ﻣﻘﺎﺑﻞ أﺟﺮة ﻣﺤﺪدة ﻳﺪﻓﻌﻬﺎ اﻟﻤﻮﻛﻞ ﻟﻠﻮﻛﻴﻞ ",
    "inves_agency_defin_appen_2":" أﺟﺮة اﻟﻮﻛﻴﻞ :  ﻧﺴﺒﺔ ﻣﺌﻮﻳﺔ ﻣﻦ ﺻﺎﻓﻲ اﻟﺮﺑﺢ اﻟﻔﻌﻠﻲ ﻟﻺﺻﺪار.، وذﻟﻚ ﻣﻘﺎﺑﻞ ﻗﻴﺎم اﻟﻮﻛﻴﻞ ﺑﺈدارة اﻹﺻﺪار ﻋﻠﻰ ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك ",
    "inves_agency_defin_appen_3":" إﺟﻤـﺎﻟﻲ ﺣﺼـﻴﻠﺔ اﻻﻛﺘﺘـﺎب: ﻣﺠﻤـﻮع اﻟﻤﺒـﺎﻟﻎ اﻟﻤﺴـﺘﻠﻤﺔ ﻣـﻦ اﻟﻤﺴـﺘﺜﻤﺮﻳﻦ ﻓـﻲ اﻟﻤﻨﺼـﺔ، ﻟﻼﺳـﺘﺜﻤﺎر ﻓـﻲ إﺻـﺪار ﺻﻜﻮك اﻟﻤﺮاﺑﺤﺔ ",
    "inves_agency_defin_appen_4":" إﺻـﺪار اﻟﺼـﻜﻮك: اﺳـﺘﺜﻤﺎر ﻣُﻌﻠـﻦ ﻋﻨـﻪ ﻣـﻦ ﻗﺒـﻞ اﻟﺸﺮﻛـﺔ، ﻣـﻦ ﺧﻼل ﻣﻨﺼـﺔ إﺻـﺪار اﻟﺼـﻜﻮك، وﻳﻘـﻮم إﺻـﺪار اﻟﺼﻜﻮك ﻋﻠﻰ أﺳﺎس ﻋﻤﻠﻴﺔ ﻣﺮاﺑﺤﺔ ﻣﺘﻮاﻓﻘﺔ ﻣﻊ أﺣﻜﺎم اﻟﺸﺮﻋﻴﺔ اﻹﺳﻼﻣﻴﺔ ",
    "inves_agency_defin_appen_5":" اﻟﺘﺎرﻳﺦ اﻟﻔﻌﻠﻲ ﻟﻠﺴﺪاد: ﻫﻮ اﻟﺘﺎرﻳﺦ اﻟﺬي ﻳﺘﻌﺪى ﺗﺎرﻳﺦ اﻻﺳﺘﺤﻘﺎق اﻟﻤﻌﻠﻦ ﻋﻨﻪ ﻓﻲ إﺻﺪار اﻟﺼﻜﻮك",
    "inves_agency_defin_appen_6":" اﻟﺴﺪاد اﻟﻤﺒﻜﺮ: ﻫﻲ ﻋﻤﻠﻴﺔ ﺗﺴﺪﻳﺪ ﻛﺎﻣﻞ اﻟﻤﺒﻠﻎ ﻣﻦ ﻗﺒﻞ اﻟﻤﺴﺘﻔﻴﺪ ﻗﺒﻞ ﺗﺎرﻳﺦ اﻻﺳﺘﺤﻘﺎق. ",
    "inves_agency_defin_appen_7":" اﻟﻌﺎﺋـﺪ اﻟﻤﺴـﺘﺤﻖ: اﻟﻌﺎﺋـﺪ اﻟﻤﺴـﺘﺤﻖ ﻟﻠﻤﻮﻛـﻞ ﺑﺤﺴـﺐ ﺣﺼـﺘﻪ ﻓـﻲ إﺟﻤـﺎﻟﻲ رﺑـﺢ اﻟﺘﻤﻮﻳـﻞ اﻟﻨـﺎﺗﺞ ﻋـﻦ اﻟﺼـﻔﻘﺔ اﻻﺳﺘﺜﻤﺎرﻳﺔ ﺑﺎﻟﻨﻈﺮ إﻟﻰ إﺟﻤﺎﻟﻲ ﺣﺼﻴﻠﺔ اﻻﻛﺘﺘﺎب ",
    "inves_agency_defin_appen_8":" اﻟﻤﺴﺘﺜﻤﺮون: اﻷﺷﺨﺎص اﻟﺮاﻏﺒﻮن ﺑﺎﻻﺳﺘﺜﻤﺎر ﻓﻲ اﻟﺼﻜﻮك اﻟﻤﻄﺮوﺣﺔ ﻣﻦ ﺧﻼل ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك ",
    "inves_agency_defin_appen_9":" اﻟﻤﺴﺘﻔﻴﺪ: اﻟﻌﻤﻴﻞ اﻟﻤﺘﻤﻮل ﻣﻦ ﺣﺼﻴﻠﺔ اﻻﻛﺘﺘﺎب ﻓﻲ اﻟﺼﻜﻮك ﺑﻤﻮﺟﺐ ﻋﻘﺪ اﻟﻤﺮاﺑﺤﺔ.",
    "inves_agency_defin_appen_10":" ﺗﺎرﻳﺦ اﻻﺳﺘﺤﻘﺎق: ﺗﺎرﻳﺦ ﺳﺪاد ﺛﻤﻦ اﻟﺒﻴﻊ اﻟﻤﺆﺟﻞ ﻓﻲ ﺣﺴﺎﺑﺎت وﻛﻴﻞ اﻟﺪﻓﻊ وﻓﻘًﺎ ﻟﻤﺎ ﻫﻮ ﻣﻌﻠﻦ ﻓﻲ ﻧﺸﺮة اﻹﺻﺪار اﻟﻤﺘﺎﺣﺔ ﻋﻠﻰ اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ ﻟﻠﻤﻨﺼﺔ. ",
    "inves_agency_defin_appen_11": " ﺗﺎرﻳﺦ اﻟﺘﻮزﻳﻊ اﻟﺪوري: ﻫﻮ ﻋﻤﻠﻴﺔ إﻳﺪاع اﻟﻤﺒﺎﻟﻎ اﻟﻤﺴﺘﺤﻘﺔ ﻓﻲ ﺣﺴﺎﺑﺎت اﻟﻤﺴﺘﺜﻤﺮﻳﻦ ﺧﻼل(5) ﺧﻤﺴﺔ أﻳﺎم ﻋﻤﻞ ﻣﻦ ﺗﺎرﻳﺦ إﻳﺪاع أي ﻗﺴﻂ ﻣﺤﺼﱠﻞ ﻣﻦ ﺛﻤﻦ اﻟﺒﻴﻊ اﻟﻤﺆﺟﻞ ﻣﻦ ﻗﺒﻞ اﻟﻤﺴﺘﻔﻴﺪ ﻓﻲ ﺣﺴﺎﺑﺎت وﻛﻴﻞ اﻟﺪﻓﻊ",
    "inves_agency_defin_appen_12":" ﺣﺴﺎب اﻟﻤﺴﺘﺜﻤﺮ اﻻﻓﺘﺮاﺿﻲ: ﺣﺴﺎب ﻣﺎﻟﻲ إﻟﻜﺘﺮوﻧﻲ، ﻳﻘﺮ اﻟﻤﺴﺘﺨﺪم ﺑﻤﻮﺟﺒﻪ ﺑﺄﻧﻪ ﻟﻴﺲ ﺣﺴﺎﺑًﺎ ﻣﺼﺮﻓﻴًﺎ وﻻ ﻳﻮﻓﺮ اﻟﺨﺪﻣﺎت اﻟﻤﺼﺮﻓﻴﺔ ﻏﻴﺮ اﻟﺘﻲ ﺗﻨﺺ ﻋﻠﻴﻬﺎ اﺗﻔﺎﻗﻴﺔ ﻓﺘﺢ اﻟﺤﺴﺎب ﻋﻠﻰ اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ ﻟﻠﻤﻨﺼﺔ ",
    "inves_agency_defin_appen_13":" ﺻﺎﻓﻲ اﻟﺮﺑﺢ اﻟﻔﻌﻠﻲ: ﻣﻘﺪار اﻟﺮﺑﺢ اﻟﺤﻘﻴﻘﻲ اﻟﺬي ﺗﻢ ﺗﺤﻘﻴﻘﻪ ﻣﻦ اﻟﺼﻜﻮك ",
    "inves_agency_defin_appen_14":" ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر: اﻟﻤﺒﻠﻎ اﻟﺬي ﻳﻮد اﻟﻄﺮف اﻟﺜﺎﻧﻲ اﺳﺘﺜﻤﺎره وﻓﻘًﺎ ﻟﺸﺮوط وأﺣﻜﺎم ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﻓﻲ ﺻﻜﻮك إﺳﻼﻣﻴﺔ ﺧﻼل اﻟﻤﻨﺼﺔ",
    "inves_agency_defin_appen_15":" ﻣﻌﺪﱠل اﻟﺮﺑﺢ اﻟﻤﺘﻮﻗﻊ: ﻣﻌﺪل اﻟﺮﺑﺢ اﻟﺬي ﻳﺘﻮﻗﻊ اﻟﻤﺴﺘﺜﻤﺮ اﺳﺘﻼﻣﻪ ﻓﻲ ﺗﺎرﻳﺦ اﻟﺘﻮزﻳﻊ اﻟﺪوري، واﻟﻤﻌﻠﻦ ﻣﻦ ﻗﺒﻞ ﻣﺴﺆول اﻟﻤﻨﺼﺔ ﻋﻠﻰ ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك ",
    "inves_agency_defin_appen_16":" ﻧﺸﺮة اﻹﺻﺪار: ﻣﻠﻒ اﻟﻤﻌﻠﻮﻣﺎت اﻟﺮﺋﻴﺴﺔ ﻟﻜﻞ ﻓﺮﺻﺔ اﺳﺘﺜﻤﺎرﻳﺔ ﻣﻌﻠﻦ ﻋﻨﻬﺎ ﻓﻲ اﻟﻤﻮﻗﻊ اﻻﻟﻜﺘﺮوﻧﻲ ",
    "inves_agency_defin_appen_17":" ﺻﻜﻮك اﻟﻤﺮاﺑﺤﺔ: ﻫﻲ وﺛﺎﺋﻖ ﻣﺘﺴﺎوﻳﺔ اﻟﻘﻴﻤﺔ ﻳﺘﻢ إﺻﺪارﻫﺎ ﻟﺘﻤﻮﻳﻞ ﺷﺮاء ﺳﻠﻌﺔ اﻟﻤﺮاﺑﺤﺔ وﺑﻴﻌﻬﺎ ﻟﻠﻤﺴﺘﻔﻴﺪ، وﻳﻤﺜﻞ اﻟﺼﻚ ﺣﺼﺔ ﺷﺎﺋﻌﺔ ﻓﻲ ﻣﻠﻜﻴﺔ ﺳﻠﻌﺔ اﻟﻤﺮاﺑﺤﺔ ﺑﻌﺪ ﺷﺮاﺋﻬﺎ وﻗﺒﻞ ﺑﻴﻌﻬﺎ وﺗﺴﻠﻴﻤﻬﺎ ﻟﻤﺸﺘﺮﻳﻬﺎ وﻓﻲ ﺛﻤﻨﻬﺎ ﺑﻌﺪ ﺑﻴﻌﻬﺎ ﻟﻠﻤﺴﺘﻔﻴﺪ، وﻋﺎﺋﺪ ﻫﺬه اﻟﺼﻜﻮك ﻫﻮ اﻟﻔﺮق ﺑﻴﻦ ﺛﻤﻦ ﺷﺮاء ﺳﻠﻌﺔ اﻟﻤﺮاﺑﺤﺔ وﺛﻤﻦ ﺑﻴﻌﻬﺎ ﻟﻠﻤﺴﺘﻔﻴﺪ ",
    "inves_agency_defin_appen_18":" اﻟﻘﻴﻤﺔ اﻻﺳﻤﻴﺔ ﻟﻠﺼﻚ: ﺛﻤﻦ ﺑﻴﻊ اﻟﺼﻚ ﻟﻠﻤﺴﺘﺜﻤﺮ واﻟﻤﻌﻠﻦ ﻋﻨﻪ ﻓﻲ ﻧﺸﺮة اﻹﺻﺪار ",
    "inves_agency_defin_appen_19":" ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك (اﻟﻤﻨﺼﺔ:( اﻟﻤﻨﺼﺔ اﻹﻟﻜﺘﺮوﻧﻴﺔ ﻟﺸﺮﻛﺔ التنافسية اﻟﻤﺎﻟﻴﺔ اﻟﻤﺘﺎﺣﺔ ﻟﻼﺳﺘﻌﻤﺎل ﻣﻦ ﺧﻼل اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ واﻟﺘﻲ ﺗﻘﺪم ﻣﻦ ﺧﻼﻟﻬﺎ ﺷﺮﻛﺔ التنافسية اﻟﻤﺎﻟﻴﺔ ﺧﺪﻣﺎت إﺻﺪار اﻟﺼﻜﻮك ",
    "inves_agency_defin_appen_20":" وﻛﻴﻞ ﺣﻤﻠﺔ اﻟﺼﻜﻮك/اﻟﻮﻛﻴﻞ: ﺷﺮﻛﺔ التنافسية اﻟﻤﺎﻟﻴﺔ ",

    "inves_agency_preface_title":" اﻟﺘﻤﻬﻴﺪ ",
    "inves_agency_preface_1" :" ﺣﻴﺚ إن اﻟﻄﺮف اﻷول ﺷﺮﻛﺔ ﻣﺼﺮﺣﺔ ﻣﻦ ﻗﺒﻞ ﻫﻴﺌﺔ اﻟﺴﻮق اﻟﻤﺎﻟﻴﺔ ﻹﻧﺸﺎء ﻣﻨﺼﺔ ﻃﺮح أدوات اﻟﺪﻳﻦ واﻻﺳﺘﺜﻤﺎر ﻓﻴﻬﺎ ﻓﻲ ﻣﺨﺘﺒﺮ اﻟﺘﻘﻨﻴﺔ اﻟﻤﺎﻟﻴﺔ، وﻣﺘﻮاﻓﻘﺔ ﻣﻊ اﻷﻧﻈﻤﺔ اﻟﻤﻌﻤﻮل ﺑﻬﺎ ﻓﻲ اﻟﻤﻤﻠﻜﺔ اﻟﻌﺮﺑﻴﺔ اﻟﺴﻌﻮدﻳﺔ. ",
    "inves_agency_preface_2" :" وﺣﻴﺚ ﻳﺮﻏﺐ اﻟﻄﺮف اﻟﺜﺎﻧﻲ ﻓﻲ اﺳﺘﺜﻤﺎر أﻣﻮاﻟﻪ ﻣﻦ ﺧﻼل ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك اﻟﺘﻲ ﻳﺪﻳﺮﻫﺎ اﻟﻄﺮف اﻷول وﻓﻖ ﺷﺮوط وأﺣﻜﺎم ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ",
    "inves_agency_preface_3" :" ﻟﺬا ﻓﻘﺪ اﺗﻔﻖ اﻟﻄﺮﻓﺎن وﻫﻤﺎ ﺑﻜﺎﻣﻞ أﻫﻠﻴﺘﻬﻤﺎ اﻟﻤﻌﺘﺒﺮة ﺷﺮﻋًﺎ وﻧﻈﺎﻣًﺎ ﻋﻠﻰ اﻟﺪﺧﻮل ﻓﻲ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ اﻟﺘﻲ ﺗﺤﺪد ﺷﺮوط وأﺣﻜﺎم اﺗﻔﺎﻗﻴﺔ اﻟﻮﻛﺎﻟﺔ ﺑﺎﻻﺳﺘﺜﻤﺎر، وذﻟﻚ ﻋﻠﻰ اﻟﻨﺤﻮ اﻵﺗﻲ ",
    "inves_agency_article1" :" اﻟﻤﺎدة اﻷوﻟﻰ: ﺣﺠﻴﺔ اﻟﻤﻘﺪﻣﺔ واﻟﺘﻤﻬﻴﺪ واﻟﻤﻼﺣﻖ ",
    "inves_agency_article1_1" :" ﺗُﻌﺪ اﻟﻤﻘﺪﻣﺔ واﻟﺘﻤﻬﻴﺪ أﻋﻼه ﺟﺰءًا ﻻ ﻳﺘﺠﺰأ ﻣﻦ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ وﻣﺘﻤﻤﺔً ﻟﻬﺎ ",
    "inves_agency_article2" :" اﻟﻤﺎدة اﻟﺜﺎﻧﻴﺔ: ﻣﺤﻞ اﻻﺗﻔﺎﻗﻴﺔ ",
    "inves_agency_article2_1" :" وﻛﱠﻞ اﻟﻤﺴﺘﺜﻤﺮُ ﺑﻤﻮﺟﺐ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ اﻟﺸﺮﻛﺔَ ﺑﺎﺳﺘﺜﻤﺎر اﻟﻘﻴﻤﺔ اﻻﺳﻤﻴﺔﻟﻠﺼﻚ/اﻟﺼﻜﻮك اﻟﻤﻤﻠﻮﻛﺔ ﻟﻠﻤﺴﺘﺜﻤﺮ ﻓﻲ ﺷﺮاء ﺳﻠﻊ ﻗﺎﺑﻠﺔ ﻟﻠﺘﺴﻴﻴﻞوﺑﻴﻌﻬﺎ ﻣﺮاﺑﺤﺔ ﻟﻠﻤﺴﺘﻔﻴﺪ ﺑﺎﺳﻢ اﻟﺸﺮﻛﺔ وﻟﺼﺎﻟﺢ اﻟﻤﺴﺘﺜﻤﺮ وﻧﻴﺎﺑﺔً ﻋﻨﻪ، وﺑﻤﺎ ﻻ ﻳﺘﻌــﺎرض ﻣــﻊ أﺣﻜــﺎم وﻣﺒــﺎدئ اﻟﺸﺮﻳﻌــﺔ اﻹﺳﻼﻣﻴــﺔ، ﻛﻤــﺎ ﻳﺨــﻮل اﻟﻤﺴــﺘﺜﻤﺮُ اﻟﺸﺮﻛــﺔَ ﺑﻤﻤﺎرﺳــﺔ ﺟﻤﻴــﻊ اﻟﺤﻘــﻮق واﻟﺴﻠﻄﺎت واﻟﺼﻼﺣﻴﺎت اﻷﺧﺮى ذات اﻟﻌﻼﻗﺔ، واﻟﺘﻲ ﻣﻦ ﺑﻴﻨﻬﺎ ﺗﺤﺼﻴﻞ ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎرﻣﻦ اﻟﻤﺴﺘﻔﻴﺪ، ورﻓﻊ اﻟﺪﻋﺎوى ﻧﻴﺎﺑﺔً ﻋﻨﻪ، وذﻟﻚ ﻟﻴﺘﻤﻜﻦ ﻣﻦ اﻟﻮﻓﺎء ﺑﺎﻟﺘﺰاﻣﺎﺗﻪ اﻟﻨﺎﺷﺌﺔ ﺑﻤﻮﺟﺐ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ، وﻗﺒﻞ اﻟﻄﺮف اﻷول ذﻟﻚ ",
    "inves_agency_article3" :" اﻟﻤﺎدة اﻟﺜﺎﻟﺜﺔ: ﻃﺒﻴﻌﺔ اﻟﻨﺸﺎط اﻻﺳﺘﺜﻤﺎري وإدارﺗﻪ: ",
    "inves_agency_article3_1" :" اﺗﻔـﻖ اﻟﻄﺮﻓـﺎن ﻋﻠـﻰ أن ﻳُﻘﻴﱠـﺪ ﻧﺸـﺎط اﻻﺳـﺘﺜﻤﺎر ﻓـﻲ ﻋﻤﻠﻴـﺎت ﺗﻤﻮﻳـﻞ ﻣﺮاﺑﺤـﺔ ﺑﺎﻵﺟـﻞ ﻣـﻊ اﻟﻤﺴـﺘﻔﻴﺪ ﺑﺎﺳـﺘﺨﺪام ﺣﺼﻴﻠﺔ اﻻﻛﺘﺘﺎب ﻓﻲ اﻟﺼﻜﻮك، وذﻟﻚ ﻣﻦ ﺧﻼل ﻣﻨﺼﺔ إﺻﺪار اﻟﺼﻜﻮك، وذﻟﻚ ﻓﻲ أي إﺻﺪار ﻣﺘﺎح ﻋﻠﻰ اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ ﻟﻠﺸﺮﻛﺔ ﻳﺤﺪده اﻟﻌﻤﻴﻞ. وﻳﻜﻮن اﻟﺘﻤﻮﻳﻞ ﺑﺎﻵﺟﻞ ﻣﻦ ﺧﻼل ﻗﻴﺎم اﻟﺸﺮﻛﺔ ﺑﺸﺮاء ﺳﻠﻊ وﺑﻴﻌﻬﺎ ﺑﺎﻵﺟﻞ ﻣﺮاﺑﺤـﺔً ﻟﻠﻤﺴـﺘﻔﻴﺪ، وﻻ ﻳﺤـﻖ ﻟﻠﺸﺮﻛـﺔ اﻟﺘﺼـﺮف ﺑﻤﺒﻠـﻎ اﻻﺳـﺘﺜﻤﺎر ﻓـﻲ ﻏﻴـﺮ اﻟﻨﺸـﺎط اﻟﻤﻨﺼـﻮص ﻋﻠﻴـﻪ ﻓـﻲ ﻫـﺬه اﻻﺗﻔﺎﻗﻴﺔ ",
    "inves_agency_article3_2" :" ﺗﺘﻌﻬﺪ اﻟﺸﺮﻛﺔ ﻟﻠﻤﺴﺘﺜﻤﺮ ﺑﻤﻮﺟﺐ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ أﻧﻬﺎ ﺳﺘﺪﻳﺮ ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر ﺑﺎﻟﻜﻔﺎءة واﻟﻌﻨﺎﻳﺔ اﻟﻼزﻣﺔ، وذﻟﻚ وﻓﻘًﺎ ﻟﻠﺴﻴﺎﺳﺎت اﻻﺋﺘﻤﺎﻧﻴﺔاﻟﻤﻌﺘﻤﺪة ﻟﺪى اﻟﺸﺮﻛﺔ ",
    "inves_agency_article3_3" :" يفويض الموكل  اﻠﺸﺮﻛﺔ ﻓﻲ اﺗﺨﺎذ اﻹﺟﺮاءات اﻟﻼزﻣﺔ ﻟﻼﺳﺘﺜﻤﺎر  بحرية مطلقة ودون الرجوع للموكل ، ﺑﻤﺎ ﻓﻲ ذﻟﻚ: ﺗﻮﻗﻴﻊ اﻟﻌﻘــﻮد، واﻟﺘﻔــﺎوض ﻣــﻊ اﻵﺧﺮﻳــﻦ، ودﻓــﻊ ﻗﻴﻤــﺔ اﻟﻌﻤﻠﻴــﺎت واﻟﻤﺼــﺎرﻳﻒ اﻟﻼزﻣــﺔ ﻟﺘﻨﻔﻴﺬﻫــﺎ، وﺗﺤﺼــﻴﻞ اﻟﻤﺒــﺎﻟﻎ ودﻓﻌﻬﺎ، وأﻳﺔ إﺟﺮاءات أﺧﺮى ﻳﺘﻄﻠﺒﻬﺎ اﺳﺘﺜﻤﺎر أﻣﻮال اﻟﻤﺴﺘﺜﻤﺮ، وﻟﻠﺸﺮﻛﺔ اﻟﺤﻖ ﻓﻲ إﺳﻨﺎد وﺗﻔﻮﻳﺾ ﺑﻌﺾ أو ﻛﻞ اﻟﺼﻼﺣﻴﺎت إﻟﻰ ﻃﺮف آﺧﺮ إذا دﻋﺖ اﻟﺤﺎﺟﺔ ﻟﺬﻟﻚ، ووﻓﻘًﺎ ﻟﺘﻘﺪﻳﺮﻫﺎ اﻟﻤﻄﻠﻖ ",
    "inves_agency_article3_4" :" اﺗﻔﻖ اﻟﻄﺮﻓﺎن ﺑﺄﻧﱠ وكالة الطرف الاول مطلقة فيما اوكل فيه و ﻟﻴﺲ ﻟﻠﻤﻮﻛﱢﻞ اﻟﺤﻖ ﻓﻲ ﻣﺮاﺟﻌﺔ اﻟﻮﻛﻴﻞ ﻹﻟﺰاﻣﻪ ﺑﺒﻌﺾ اﻷﻋﻤﺎل، أو اﺷﺘﺮاط أﺧﺬ ﻣﻮاﻓﻘﺔ اﻟﻤﻮﻛﻞ ﻋﻠﻰ ﺑﻌﺾ اﻟﺘﺼﺮﻓﺎت ﺑﻌﺪ اﻟﺘﻮﻗﻴﻊ ﻋﻠﻰ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ، ﻛﻤﺎ ﻻ ﻳﺤﻖ ﻟﻠﻤﻮﻛﱢﻞ اﻟﺘﻮاﺻﻞ ﻣﻊ اﻟﻤﺴﺘﻔﻴﺪ ﻹﻟﺰاﻣﻪ ﺑﺎﻟﺪﻓﻊ أو رﻓﻊ دﻋﻮى ﻗﻀﺎﺋﻴﺔ أو أي إﺟﺮاءات أﺧﺮى دون اﻟﺮﺟﻮع ﻟﻠﻮﻛﻴﻞ ",
    "inves_agency_article3_5" :" اﺗﻔﻖ اﻟﻄﺮﻓﺎن ﺑﺄنﱠ ﻟﻠﻮﻛﻴﻞ اﻟﺤﻖ اﻟﻤﻄﻠﻖ ﻓﻲ اﻟﺘﻮاﺻﻞ ﻣﻊ اﻟﻤﺴﺘﻔﻴﺪ واﻟﻤﺴﺘﺜﻤﺮﻳﻦ اﻵﺧﺮﻳﻦ اﻟﻤﺸﺎرﻛﻴﻦ ﻓﻲ إﺻﺪار اﻟﺼﻜﻮك، وﻟﻴﺲ ﻟﻠﻤﻮﻛﱢﻞ اﻟﺤﻖ ﻓﻲ ﻣﺮاﺟﻌﺔ اﻟﻤﺴﺘﺜﻤﺮﻳﻦ اﻵﺧﺮﻳﻦ أو اﻟﻤﺴﺘﻔﻴﺪ ",
    "inves_agency_article4" :" اﻟﻤﺎدة اﻟﺮاﺑﻌﺔ: ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر ",
    "inves_agency_article4_1" :" ﻋﻠـﻰ اﻟﻤﺴـﺘﺜﻤﺮ إﻳـﺪاع رأس اﻟﻤـﺎل ﻓـﻲ ﺣﺴـﺎﺑﻪ اﻻﺳـﺘﺜﻤﺎري ﺣﺴـﺎب اﻟﻤﺴـﺘﺜﻤﺮ اﻻﻓﺘﺮاﺿـﻲ اﻟﻤﺴـﺠﻞ ﻓـﻲ ﺻﻔﺤﺘﻪ اﻟﺸﺨﺼﻴﺔ ﻋﻠﻰ اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ ﻟﻠﻤﻨﺼﺔ ",
    "inves_agency_article4_2" :" تلتزم شركة التنافسية المالية بأحكام الفصلين الثاني والثالث من الباب السابع من لائحة مؤسسات السوق المالية المتعلقة بأصول وأموال العملاء ",
    "inves_agency_article5" :" اﻟﻤﺎدة اﻟﺨﺎﻣﺴﺔ: ﻣﺪة اﻻﺳﺘﺜﻤﺎر ",
    "inves_agency_article5_1" :" ﻳﺠﺐ أﻻ ﻳﻜﻮن إﻧﻬﺎء اﻻﺗﻔﺎﻗﻴﺔ أو اﻧﺘﻬﺎﺋﻬﺎ ﻣﺆﺛﱢﺮًا ﻋﻠﻰ ﺣﻘﻮق واﻟﺘﺰاﻣﺎت أيﱟ ﻣﻦ اﻟﻄﺮﻓﻴﻦ، ﻓﻴﻤﺎ ﻳﺘﻌﻠﻖ ﺑﺄي إﺻﺪار ﺻـﻜﻮك ﻗـﺎﺋﻢ وﻣﺴـﺘﺤﻖ ﻗﺒـﻞ اﻧﺘﻬـﺎء ﻫـﺬه اﻻﺗﻔﺎﻗﻴـﺔ، ﺣﻴـﺚ ﺳـﺘﻈﻞ ﺷـﺮوط وأﺣﻜـﺎم ﻫـﺬه اﻻﺗﻔﺎﻗﻴـﺔ ﺳﺎرﻳـﺔ ﺣﺘـﻰ اﻻﻧﺘﻬﺎء ﻣﻦ ﺗﺴﻮﻳﺔ اﻟﺼﻜﻮك اﻟﻘﺎﺋﻤﺔ ",
    "inves_agency_article6" :" اﻟﻤﺎدة اﻟﺴﺎدﺳﺔ: أﺟﺮة اﻟﺸﺮﻛﺔ ",
    "inves_agency_article6_1" :" اﺗﻔﻖ اﻟﻄﺮﻓﺎن ﻋﻠﻰ أنﱠ اﻟﺸﺮﻛﺔ ﺗﺴﺘﺤﻖ رﺳﻮﻣًﺎ ﻣﻘﺎﺑﻞ ﻋﻤﻠﻬﺎ ﻧﻴﺎﺑﺔً ﻋﻦ اﻟﻤﺴﺘﺜﻤﺮ ﺗﻘﺪﱠر ﺑﻨﺴﺒﺔ ﻣﺌﻮﻳﺔ ﻣﻦ ﺻﺎﻓﻲ اﻟﺮﺑﺢ اﻟﻔﻌﻠﻲ، ﺗُﺤﺪدﻫﺎ اﻟﺸﺮﻛﺔ ﻓﻲ اﻟﻨﺸﺮة اﻟﺨﺎﺻﺔ ﺑﻜﻞ إﺻﺪار ",
    "inves_agency_article7" :" اﻟﻤﺎدة اﻟﺴﺎﺑﻌﺔ: ﻋﻮاﺋﺪاﻟﺼﻜﻮك ",
    "inves_agency_article7_1" :" ﻳﺘﻌﻬﺪ اﻟﻮﻛﻴﻞ ﺑﻌﺪ اﺳﺘﻼم ﻣﺒﺎﻟﻎ اﻟﺘﻮزﻳﻌﺎت اﻟﺪورﻳﺔ اﻟﻤﺤﺪدة ﻓﻲ ﺟﺪول اﻟﺴﺪاد اﻟﺨﺎص ﺑﺎﻹﺻﺪار وﻓﻘًﺎ ﻟﻤﺎ ﻫﻮ ﻣﻌﻠﻦ ﻋﻨﻪ ﻓﻲ ﻧﺸﺮة اﻹﺻﺪار اﻟﺨﺎﺻﺔ ﺑﺎﻹﺻﺪار. وذﻟﻚ ﻣﻦ اﻟﻤﺴﺘﻔﻴﺪ ﺑﺈﻳﺪاع اﻟﻤﺒﻠﻎ ﻓﻲ ﺣﺴﺎب اﻟﻤﺴﺘﺜﻤﺮ ﺑﻌﺪ ﺧﺼﻢ أﺟﺮة اﻟﻮﻛﻴﻞ أو أي ﻣﺼﺎرﻳﻒ ﺗﺘﻌﻠﻖ ﺑﺎﻟﺘﺤﺼﻴﻞ واﻟﻤﺤﺎﻣﺎة ",
    "inves_agency_article7_2" :" ﻓﻲ ﺣﺎل ﺣﺼﻮل ﺧﺴﺎرة ﻓﻲ إﺻﺪار اﻟﺼﻜﻮك ﻓﻴﺘﻌﻬﺪ اﻟﻮﻛﻴﻞ ﺑﺈﻋﺎدة ﻣﺎ ﺗﺒﻘﻰ ﻣﻦ ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر إﻟﻰ اﻟﻤﻮﻛﱢﻞ، وذﻟﻚ ﻣﻊ ﻣﺮاﻋﺎة ﻣﺎ ورد ﻓﻲ اﻟﻔﻘﺮة اﻟﺜﺎﻧﻴﺔ ﻟﻠﻤﺎدة اﻟﺘﺎﺳﻌﺔ ﺑﻌﺪ ﺧﺼﻢ ﻛﺎﻓﺔ ﻣﺼﺎرﻳﻒ اﻟﺘﺤﺼﻴﻞ واﻟﻤﺤﺎﻣﺎة ",
    "inves_agency_article7_3" :" ﻓــﻲ ﺣــﺎل اﻟﺴــﺪاد اﻟﻤﺒﻜــﺮ ﻓﻴﺘــﻢ إﻋــﺎدة اﺣﺘﺴــﺎب اﻟﻌﺎﺋــﺪ اﻟﻤﺴــﺘﺤﻖ ﻟﻠﻤﺴــﺘﺜﻤﺮ ﺑﻨــﺎءً ﻋﻠــﻰ اﻟﺘــﺎرﻳﺦ اﻟﻔﻌﻠــﻲ ﻟﻠﺴﺪاد ",
    "inves_agency_article8" :" اﻟﻤﺎدة اﻟﺜﺎﻣﻨﺔ: ﻧﻄﺎق اﻟﻤﺴﺆوﻟﻴﺔ: ",
    "inves_agency_article8_1" :" ﻳﻘﺮ اﻟﻤﺴﺘﺜﻤﺮ وﻳﻌﻲ ﻛﺎﻣﻞ اﻟﻤﺨﺎﻃﺮ اﻟﻨﺎﺷﺌﺔ ﻋﻦ ﻋﻤﻠﻴﺎت اﻟﺘﻤﻮﻳﻞ ﻣﻦ ﺧﻼل اﻟﻤﻨﺼﺔ، واﺣﺘﻤﺎل ﺧﺴﺎرة ﻛﺎﻣﻞ ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر أو ﺟﺰء ﻣﻨﻪ ",
    "inves_agency_article8_2" :" ﻳﻘﺮ اﻟﻤﻮﻛﱢﻞ ﺑﺄن اﻟﻮﻛﻴﻞ أﻣﻴﻦ ﻋﻠﻰ ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر وإدارﺗﻪ، ﻻ ﻳﻀﻤﻨﻪ ﻓﻲ ذﻣﺘﻪ ﻣﺎ ﻟﻢ ﻳﺘﻌﺪ أو ﻳﻔﺮط أو ﻳﺨﺎﻟﻒ ﺷﺮوط ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ، وﻋﻠﻴﻪ ﻓﻘﺪ واﻓﻖ اﻟﻤﻮﻛﱢﻞ ﺑﺄن ﺣﺪود اﻟﻤﺴﺆوﻟﻴﺔ اﻟﻘﺎﻧﻮﻧﻴﺔ ﻟﻠﻮﻛﻴﻞ وﻣﺪﻳﺮﻳﻪ وﻣﻮﻇﻔﻴﻪ ﻋﻦ اﻟﺨﺴﺎﺋﺮ أو اﻟﺘﻜﺎﻟﻴﻒ أو اﻷﺿﺮار الناتجة عن التفريط او التعدي  ﻣﻬﻤﺎ ﻛﺎﻧﺖ ﻃﺒﻴﻌﺘﻬﺎ أو اﻟﻤﻄﺎﻟﺒﺎت أو اﻟﻤﺼﺮوﻓﺎت ﻷي ﺳﺒﺐ ﻛﺎن، ﺑﻤﺎ ﻓﻲ ذﻟﻚ اﻷﺗﻌﺎب اﻟﻘﺎﻧﻮﻧﻴﺔ، ﻻ ﺗﺘﺠﺎوز ﺑﺤﺎل ﻣﻦ اﻷﺣﻮال ﻣﻘﺪار ﻣﺒﻠﻎ اﻻﺳﺘﺜﻤﺎر اﻟﻤﺪﻓﻮع ﻟﻠﻮﻛﻴــﻞ ﺑﻤــﻮﺟﺐ ﻫــﺬه اﻻﺗﻔﺎﻗﻴــﺔ، ﻋﻠــﻰ أن ﻻ ﻳﺘــﻢ ﺗﻌــﻮﻳﺾ اﻟﻤﻮﻛﱢــﻞ إﻻ ﺑﻤــﻮﺟﺐ ﺣﻜــﻢ ﻗﻀــﺎﺋﻲ ﻣﻜﺘﺴــﺐ اﻟﻘﻄﻌﻴﺔ ",
    "inves_agency_article8_3" :" ﻓــﻲ ﺣــﺎل اﻟﺴــﺪاد اﻟﻤﺒﻜــﺮ ﻓﻴﺘــﻢ إﻋــﺎدة اﺣﺘﺴــﺎب اﻟﻌﺎﺋــﺪ اﻟﻤﺴــﺘﺤﻖ ﻟﻠﻤﺴــﺘﺜﻤﺮ ﺑﻨــﺎءً ﻋﻠــﻰ اﻟﺘــﺎرﻳﺦ اﻟﻔﻌﻠــﻲ ﻟﻠﺴﺪاد ",
    "inves_agency_article8_4" :" ﻓﻲ ﺣﺎل ﺣﺼﻮل ﺧﺴﺎرة-ﻻ ﻗﺪر ﷲ- ﻓﻲ إﺻﺪار اﻟﺼﻜﻮك ﻓﺈن اﻟﺨﺴﺎرة ﺗﻮزﱠع ﻋﻠﻰ ﺟﻤﻴﻊ اﻟﻤﺴﺘﺜﻤﺮﻳﻦ ﻓﻲ اﻹﺻﺪار ﺑﺤﺴﺐ ﺣﺼﺔ ﻛﻞ ﻃﺮف ﻓﻲ إﺟﻤﺎﻟﻲ ﺣﺼﻴﻠﺔ اﻻﻛﺘﺘﺎب، وﻻ ﻳﺤﻖ ﻟﻠﺸﺮﻛﺔ ﻣﻄﺎﻟﺒﺔ اﻟﻤﺴﺘﺜﻤﺮ ﺑﺄي ﺗﻌﻮﻳﺾ ﻋﻦ ﺟﻬﺪه وﻋﻤﻠﻪ ﻓﻲ ﻫﺬه اﻟﺤﺎل ",
    "inves_agency_article9" :" اﻟﻤﺎدة اﻟﺘﺎﺳﻌﺔ: ﻋﺪم ﻣﻤﺎرﺳﺔ اﻟﺤﻘﻮق ",
    "inves_agency_article9_1" :" ﻻ ﻳُﻌــﺪ ﻋــﺪم ﻗﻴــﺎم اﻟﻄــﺮف اﻷول أو ﺗــﺄﺧﺮه ﺑﺎﻟﻤﻄﺎﻟﺒــﺔ ﺑﺤﻘــﻮﻗﻪ أو ﻣﻤﺎرﺳــﺘﻪ ﻷي ﺣــﻖ ﻣــﻦ ﺣﻘــﻮﻗﻪ اﻟﻨﺎﺷﺌــﺔ ﺑﻤﻮﺟﺐ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﺗﻨﺎزﻟًﺎ ﻣﻦ ﺟﻬﺘﻪ، وﻳﺤﻖ ﻟﻠﻄﺮف اﻷول أن ﻳﺘﺨﺬ ﻛﺎﻓﺔ اﻹﺟﺮاءات اﻟﺘﻲ ﺗﻜﻔﻞ ﻟﻪ ﺗﺤﺼﻴﻞ ﺣﻘﻮﻗﻪ ﻣﻦ اﻟﻄﺮف اﻟﺜﺎﻧﻲ ﻓﻲ أي وﻗﺖ ",
    "inves_agency_article9_2" :" ﻟﻦ ﻳﻜﻮن اﻟﻄﺮف اﻷول ﻣﺴﺆوﻟًﺎ ﻋﻦ أيﱢ ﺧﺴﺎﺋﺮ أو أﺿﺮار ﻳﺘﻌﺮض ﻟﻬﺎ اﻟﻄﺮف اﻟﺜﺎﻧﻲ ﺑﺴﺒﺐ ﻣﻤﺎرﺳﺔ أو ﻋﺪم ﻣﻤﺎرﺳﺔ اﻟﻄﺮف اﻷول ﻷي ﻣﻦ ﺣﻘﻮﻗﻪ اﻟﻨﺎﺷﺌﺔ ﻋﻦ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ أو اﻻﺗﻔﺎﻗﻴﺎت اﻟﻤﺮﺗﺒﻄﺔ ﺑﻬﺎ ",
    "inves_agency_article9_3" :" ﻓــﻲ ﺣــﺎل اﻟﺴــﺪاد اﻟﻤﺒﻜــﺮ ﻓﻴﺘــﻢ إﻋــﺎدة اﺣﺘﺴــﺎب اﻟﻌﺎﺋــﺪ اﻟﻤﺴــﺘﺤﻖ ﻟﻠﻤﺴــﺘﺜﻤﺮ ﺑﻨــﺎءً ﻋﻠــﻰ اﻟﺘــﺎرﻳﺦ اﻟﻔﻌﻠــﻲ ﻟﻠﺴﺪاد ",
    "inves_agency_article10" :" اﻟﻤﺎدة اﻟﻌﺎﺷﺮة: ﺗﺤﻮﻳﻞ اﻟﺤﻘﻮق ",
    "inves_agency_article10_1" :" يحق ﻟﻠﻄــﺮف اﻷول اﻟﺘﻨــﺎزل أو ﺗﺤﻮﻳﻞ ﻛــﻞ أو ﺑﻌــﺾ ﺣﻘــﻮﻗﻪ واﻟﺘﺰاﻣــﺎﺗﻪ اﻟﻨﺎﺗﺠـﺔ ﻋـﻦ ﻫـﺬه اﻻﺗﻔﺎﻗﻴـﺔ واﻻﺗﻔﺎﻗﻴـﺎت اﻟﻤﺮﺗﺒﻄـﺔ ﺑﻬـﺎ إﻟـﻰ ﻣـﻦ ﻳﺸـﺎء، ويقر الطرف الثاني أن توقيغه على هذه الاتفاقية بمثابة الموافقة المسبقة على حق الطرف الأول في احالة حقوقه دون ﺗﻮﻗـﻒ ذﻟـﻚ ﻋﻠـﻰ رﺿـﺎ اﻟﻄـﺮف اﻟﺜﺎﻧﻲ ",
    "inves_agency_article10_2" :" ﻻ ﻳﺤﻖ ﻟﻠﻄﺮف اﻟﺜﺎﻧﻲ أن ﻳﺘﻨﺎزل ﻋﻦ ﻛﻞ أو ﺑﻌﺾ أو أن ﻳﺤﻮل اﻟﺘﺰاﻣﺎﺗﻪ اﻟﻤﺘﺮﺗﺒﺔ ﻋﻠﻴﻪ ﺑﻤﻮﺟﺐ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ إﻟﻰ أي ﺟﻬﺔ أﺧﺮى دون ﻣﻮاﻓﻘﺔ ﺧﻄﻴﺔ ﻣﺴﺒﻘﺔ ﻣﻦ اﻟﻄﺮف اﻷول ",
    "inves_agency_article11" :" اﻟﻤﺎدة اﻟﺤﺎدﻳﺔ ﻋﺸﺮة: اﻟﻨﻈﺎم واﺟﺐ اﻟﺘﻄﺒﻴﻖ وﺗﺴﻮﻳﺔ اﻟﻤﻨﺎزﻋﺎت ",
    "inves_agency_article11_1" :" ﺗﺨﻀﻊ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ وﺗﻔﺴﺮ وﻓﻘًﺎ ﻟﻸﻧﻈﻤﺔ واﻟﻠﻮاﺋﺢ اﻟﻤﻌﻤﻮل ﺑﻬﺎ ﻓﻲ اﻟﻤﻤﻠﻜﺔ اﻟﻌﺮﺑﻴﺔ اﻟﺴﻌﻮدﻳﺔ ",
    "inves_agency_article11_2" :" ﻛﻞ ﺧﻼف ﻳﻨﺸﺄ ﺑﻴﻦ اﻟﻄﺮﻓﻴﻦ ﺣﻮل ﺗﻔﺴﻴﺮ أو ﺗﻨﻔﻴﺬ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ أو أي ﺑﻨﺪ ﻣﻦ ﺑﻨﻮدﻫﺎ ﻳﺘﻢ ﺣﻠﻪ ﺑﺎﻟﻄﺮق اﻟﻮدﻳﺔ، ﻓﺈذا ﺗﻌﺬﱠر ذﻟﻚ ﻓﻴﺘﻢ ﺣﻠﻪ ﻋﻦ ﻃﺮﻳﻖ اﻟﻠﺠﻮء إﻟﻰ اﻟﺠﻬﺎت اﻟﻘﻀﺎﺋﻴﺔ اﻟﻤﺨﺘﺼﺔ ﻓﻲ اﻟﻤﻤﻠﻜﺔ اﻟﻌﺮﺑﻴﺔ اﻟﺴﻌﻮدﻳﺔ، ﺑﻤﺪﻳﻨﺔ اﻟﺮﻳﺎض ",
    "inves_agency_article12" :" اﻟﻤﺎدة اﻟﺜﺎﻧﻴﺔ ﻋﺸﺮة: أﺣﻜﺎم ﻋﺎﻣﱠﺔ ",
    "inves_agency_article12_1" :" ﺗﺴـﺮي اﻷﺣﻜـﺎم واﻟﺸـﺮوط اﻟـﻮاردة ﻓـﻲ ﻫـﺬه اﻻﺗﻔﺎﻗﻴـﺔ ﻋﻠـﻰ أﻃﺮاﻓﻬـﺎ اﻟﻤﻮﺿﺤـﺔ ﺑﻴﺎﻧـﺎﺗﻬﻢ ﻓـﻲ ﺻـﺪرﻫﺎ، ﻛﻤـﺎ ﺗﺴـﺮي ﻋﻠـﻰ ﺧﻠﻔـﺎﺋﻬﻢ اﻟﺸﺮﻋﻴﻴـﻦ واﻟﻘـﺎﻧﻮﻧﻴﻴﻦ، وﺑﻤـﺎ ﻻ ﻳﺘﻌـﺎرض أو ﻳﺨـﺎﻟﻒ اﻷﺣﻜـﺎم واﻟﺸـﺮوط اﻟـﻮاردة ﻓـﻲ اﺗﻔﺎﻗﻴﺔ ﻓﺘﺢ اﻟﺤﺴﺎب ﻋﻠﻰ اﻟﻤﻮﻗﻊ اﻹﻟﻜﺘﺮوﻧﻲ ﻟﻠﺸﺮﻛﺔ ",
    "inves_agency_article12_2" :" تاريخ النفاذ: تم التعديل في ديسمبر 2022 ",
    "inves_agency_article12_3" :" ﻳﻘــﺮ اﻟﻄﺮﻓــﺎن ﺑﺄﻧﻬﻤــﺎ ﻗــﺪ اﻃﻠﻌــﺎ ﻋﻠــﻰ ﻛﺎﻓــﺔ ﺑﻨــﻮد ﻫــﺬه اﻻﺗﻔﺎﻗﻴــﺔ وﻣــﺎ ﻳﺮﺗﺒــﻂ ﺑﻬــﺎ ﻣــﻦ اﺗﻔﺎﻗﻴــﺎت، وﻓﻬﻤــﺎ ﻣﺤﺘﻮﻳﺎﺗﻬﺎ، وأﻧﻬﻢ ﻣﻠﺘﺰﻣﻮن ﺑﻜﻞ ﻣﺎ ورد ﻓﻴﻬﺎ ﻣﻦ ﺷﺮوط وأﺣﻜﺎم ",
    "inves_agency_article12_4" :" إذا ﺗﺒﻴﻦ أن أيﱠ ﺣﻜﻢ ﻣﻦ أﺣﻜﺎم ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﻣﺨﺎﻟﻒ ﻟﻸﻧﻈﻤﺔ اﻟﻤﻌﻤﻮل ﺑﻬﺎ أو أﺻﺒﺢ ﻛﺬﻟﻚ ﺑﻤﻮﺟﺐ أي ﻧﻈﺎم أو ﺣﻜﻢ ﻗﻀﺎﺋﻲ ﻓﺈن اﻟﺒﻄﻼن ﻳﺮد ﻋﻠﻰ ذﻟﻚ اﻟﺤﻜﻢ أو اﻟﺸﺮط، وﻻ ﻳﺆﺛﺮ ذﻟﻚ ﻋﻠﻰ ﺳﺮﻳﺎن ﺑﺎﻗﻲ اﻷﺣﻜﺎم واﻟﺸﺮوط اﻟﻮاردة ﻓﻲ اﻻﺗﻔﺎﻗﻴﺔ ",
    "inves_agency_article12_5" :" ﻳﺘﻢ ﺗﻨﻔﻴﺬ اﻟﻌﻤﻠﻴﺎت ﺧﻼل أﻳﺎم وأوﻗﺎت اﻟﻌﻤﻞ اﻟﺮﺳﻤﻴﺔ، وﻻ ﺗﺪﺧﻞ أﻳﺎم اﻟﻌﻄﻞ واﻹﺟﺎزات اﻟﺮﺳﻤﻴﺔ ﺿﻤﻦ أﻳﺎم اﻟﻌﻤﻞ ﻫﺬه ",
    "inves_agency_article12_6" :" ﻓﻲ ﺣﺎﻟﺔ وﻓﺎة اﻟﻤﻮﻛﻞ ﻓﻠﻮرﺛﺘﻪ اﻟﺤﻖ ﻓﻲ إﻣﻀﺎء اﻟﻮﻛﺎﻟﺔ أو ﻓﺴﺨﻬﺎ ﺑﻤﻮﺟﺐ إﺷﻌﺎر ﺧﻄﻲ ﻟﻠﻮﻛﻴﻞ، ﻋﻠﻰ أن ﺗُﺮاﻋﻰ اﻷﺣﻜﺎم اﻟﻮاردة اﻟﻤﺎدة اﻟﺴﺎدﺳﺔ ﻣﻦ ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ",
    "inves_agency_article12_7" :" ــﺪرك وﻳﻘــﺮ اﻟﻤﻮﻛﱢــﻞ أﻧﱠــﻪ ﻓــﻲ ﺣــﺎل ﺗــﻢ اﻟﺘﺤﻘــﻖ أو اﻻﺷﺘﺒــﺎه ﺑــﺄي ﻋﻤﻠﻴــﺔ ﻣﺘﻌﻠﻘــﺔ ﺑﻐﺴــﻞ اﻷﻣــﻮال وﺗﻤﻮﻳــﻞ اﻹرﻫــﺎب، ﻓﺴــﻴﺘﻢ إﻳﻘــﺎف اﻟﺤﺴــﺎب اﻻﺳــﺘﺜﻤﺎري ﻣﺆﻗﺘًــﺎ أو ﺑﺸﻜــﻞ داﺋــﻢ، وﻓــﻖ ﺳــﻴﺎﺳﺎت اﻹﺑﻼغ ﻋــﻦ ﺗﻠــﻚ اﻟﻮاﻗﻌﺔ، وذﻟﻚ ﺑﻤﻮﺟﺐ ﻧﻈﺎم ﻣﻜﺎﻓﺤﺔ ﻏﺴﻞ اﻷﻣﻮال اﻟﺼﺎدر ﺑﺎﻟﻤﺮﺳﻮم اﻟﻤﻠﻜﻲ رﻗﻢ)م(20/ ﻋﺎم1439ه، وﻧﻈـﺎم ﻣﻜﺎﻓﺤـﺔ اﻹرﻫـﺎب وﺗﻤـﻮﻳﻠﻪ اﻟﺼـﺎدر ﺑـﺎﻟﻤﺮﺳﻮم اﻟﻤﻠﻜـﻲ رﻗـﻢ)م(21/ وﺗـﺎرﻳﺦ12/02/1439ﻫــ، واﻟﻼﺋﺤـﺔ اﻟﺘﻨﻔﻴﺬﻳﺔ ﻟﻨﻈﺎم ﻣﻜﺎﻓﺤﺔ اﻹرﻫﺎب وﺗﻤﻮﻳﻠﻪ اﻟﺼﺎدرة ﺑﻘﺮار ﻣﺠﻠﺲ اﻟﻮزراء رﻗﻢ(228) وﺗﺎرﻳﺦ02/05/1440ﻫـ،وﻧﻈﺎم ﻣﻜﺎﻓﺤﺔ ﺟﺮاﺋﻢ اﻟﻤﻌﻠﻮﻣﺎﺗﻴﺔ: اﻟﺼﺎدر ﺑﺎﻟﻤﺮﺳﻮم اﻟﻤﻠﻜﻲ رﻗﻢ)م(17/ ﻋﺎم1428ﻫ ",
    "inves_agency_article13" :" اﻟﻤﺎدة اﻟﺜﺎﻟﺜﺔ ﻋﺸﺮة: اﻹﺧﻄﺎرات واﻟﻤﺮاﺳﻼت ",
    "inves_agency_article13_1" :" اﻟﻌﻨﺎوﻳﻦ اﻟﻤﺒﻴﻨﺔ ﺑﺼﺪر ﻫﺬه اﻻﺗﻔﺎﻗﻴﺔ ﻟﻜﻞ ﻃﺮف ﻫﻲ ﻋﻨﻮاﻧﻪ اﻟﻨﻈﺎﻣﻲ، وﺗﺘﻢ ﺟﻤﻴﻊ اﻟﻤﺮاﺳﻼت ﻣﻦ ﻃﻠﺒﺎت أو إﺷﻌﺎرات أو إﻗﺮارات أو ﻣﻮاﻓﻘﺎت أو أي ﻣﺴﺘﻨﺪات أﺧﺮى ﻋﻦ ﻃﺮﻳﻘﻬﺎ، أو ﻋﻦ ﻃﺮﻳﻖ اﻟﺒﺮﻳﺪ اﻟﻤﺴﺠﻞ أو اﻟﻔﺎﻛﺲ أو اﻟﺒﺮﻳﺪ اﻹﻟﻜﺘﺮوﻧﻲ أو ﺗﺴﻠﻢ ﺑﺎﻟﻴﺪ أو ﺑﺄي ﻃﺮﻳﻘﺔ ﻣﻦ اﻟﻄﺮق اﻟﻤﻌﺘﻤﺪة ﻟﺪى اﻟﻄﺮف اﻷول، وﺗﻌﺪ اﻟﻤﺮاﺳﻼت اﻟﺘﻲ ﺗﺘﻢ ﻋﻦ ﻃﺮﻳﻖ ﻫﺬه اﻟﻌﻨﺎوﻳﻦ ﻣُﻠﺰﻣﺔ ﻟﻠﻄﺮف اﻟﺜﺎﻧﻲ، وﻻ ﻳُﻌﺘﺪ ﺑﺄي ﺗﻐﻴﻴﺮ ﻟﻬﺬه اﻟﻌﻨﺎوﻳﻦ إﻻ ﺑﻤﻮﺟﺐ ﺧﻄﺎب ﻛﺘﺎﺑﻲ ﺳﺎﺑﻖ إﻟﻰ ﻣﻮﺟﻪ إﻟﻰ اﻟﻄﺮف اﻷول ",


    "prog_info_program_number":"رقم البرنامج",
    "prog_info_sukuk_murabha":"صكوك المرابحة",
    "prog_info_mansha2a_private":"المنشأة ذات الغرض الخاص 'المصدر'",
    "prog_info_Allowance":"الترخيص",
    "prog_info_Reason_Allowance":"الغرض من الترخيص",
    "prog_info_Provider_Name":"وصي المنشأة ذات الغرض الخاص",
    "prog_info_Borrower_teams":"أعضاء مجلس إدارة المنشأة ذات الغرض الخاص",
    "prog_info_Member_relation":"العلاقة",
    "prog_info_Nationality":"الجنسية",
    "prog_info_Sukuk_Form":"هيكل الصكوك",
    "prog_info_Sukuk_Paid_Agent":"وكيل حملة الصكوك ووكيل الدفع",
    "prog_info_Portal_Admin":"مسؤول المنصة",
    "prog_info_Sukuk":"الصكوك",
    "prog_info_value_of_instrument":"القيمة الاسمية للصك",
    "prog_info_total_instrument_prog_value":"إجمالي القيمة الاسمية للبرنامج",
    "prog_info_m7slat_tar7_uses":"استخدام متحصلات الطرح",
    "prog_info_Investor_Applied_Condition":"شروط تقديم الخدمات للمستثمرين",
    "prog_info_borrowing_reason":"الغرض من الحصول على التمويل",
    "prog_info_shepherd":"الراعي",
    "prog_info_shepherd_responsibility":"وصف دور الراعي",
    "prog_info_shepherd_Comitment":"التزام الراعي",
    "prog_info_shepherd_representative":"ممثل الراعي",
    "prog_info_Company_Beneficiary":"الشركة (المستفيد)",
    "prog_info_Beneficiary_Legal_Entity":"الكيان القانوني للمستفيد",
    "prog_info_Beneficiary_Activity":"نشاطات المستفيد",
    "prog_info_Beneficiary_Capital":"رأس مال المستفيد",
    "prog_info_Company_Owners":"ملاك الشركة",
    "prog_info_Ektetab_Type":"طريقة الاكتتاب",
    "prog_info_Min_Max_Ektetab":"الحد الأدنى والأعلى للاكتتاب",
    "prog_info_Allocation_Subtraction_Limitations":"قيود التخصيص والطرح",
    "prog_info_early_refund_right":"حق الاسترداد المبكر",
    "prog_info_terminate_sukuk_date":"تاريخ إطفاء الصكوك",
    "prog_info_Periodic_destribution_amount":"مبلغ التوزيع الدوري",
    "prog_info_desc_role_custodian":"وصف دور أمين الحفظ",
    "prog_info_restriction_sukuk":"القيود المفروضة على الصكوك",
    "prog_info_sukuk_assets":"موجودات الصكوك",
    "prog_info_murabaha_contract":"عقد المرابحة",
    "prog_info_sanad_owners_beneficiary":"السند لأمر على ملاك المستفيد",
    "prog_info_bond_order_beneficiary_owner":"السند لامر على المستفيد",
    "prog_info_instrument_doc":"وثيقة الصك",
    "prog_info_regime":"النظام الحاكم",
    "prog_info_Refund_Muktatbeen":"اعادة الاموال للمكتتبين",
    "prog_info_risk_factor":"عوامل المخاطرة",
    "MustanadAltarh":"مستند الطرح",
    "Campaign_Attachements":"مرفقات الفرصة",
    "Program_Information":"معلومات البرنامج",
    "Investment_Agreement":"اﺗﻔﺎﻗﻴﺔ وﻛﺎﻟﺔ ﺑﺎﻻﺳﺘﺜﻤﺎر",
    "Sukuk_Murabaha":"صكوك المرابحة",
    "Annual_return_rate":"نسبة العائد السنوي",
    "Please_Fill_your_information":"الرجاء استكمال بياناتك او انتظار الاعتماد",
    "Be_Qualified_Investor":"كن مؤهلاً",
    //End Add by Qaysar

  },
};

/*
 * For easier debugging in development mode, you can import the following file
 * to ignore zone related error stack frames such as `zone.run`, `zoneDelegate.invokeTask`.
 *
 * This import should be commented out in production mode because it will have a negative impact
 * on performance if an error is thrown.
 */
// import 'zone.js/plugins/zone-error';  // Included with Angular CLI.
