export class CampaginWithKyc {
  constructor(
    public company_name: string,
    public id: string,
    public user_id: string,
    public product_id: string,
    public approved_status: string,
    public approve_loan: string,
    public note: string,
    public tagline: string,
    public share_price: string,
    public total_valuation: string,
    public min_investment: string,
    public max_investment: string,
    public close_date: string,
    public fundriser_investment: string,
    public duration_id: string,
    public returns_type_id: string,
    public company_bio: string,
    public reason_to_invest: string,
    public investment_planning: string,
    public terms: string,
    public introduce_team: string,
    public status: string,
    public created_by: string,
    public created_at: string,
    public updated_by: string,
    public updated_at: string,
    public program_number: string,
    public version_number: string,
    public open_date: string,
    public net_sales: string,
    public net_sales_years: string,
    public net_profit: string,
    public net_profit_years: string,
    public cash_flow: string,
    public return_on_assets: string,
    public debt_of_assets: string,
    public fin_statement_year: string,
    public due_date: string,
    public APR: string,
    public info_Statement_date_G: string,
    public info_Statement_date_h: string,
    public national_id: string
  ) {}
}
